### ISSUE TITLE
wdi5 specific JS syntax for UI5 test recorder

### ISSUE THREAD

**Issue by vobu** [ui5-community/wdi5#149]

**Comment by vobu** [comment]
in the works by @Siolto

**Comment by Siolto** [comment]
will be finished soon :)

**Comment by dominikfeininger** [comment]
@Siolto status? ;)

**Comment by vobu** [comment]
aaalmost in to UI5 core :)

**Comment by Siolto** [comment]
[Pull Request](https://github.com/SAP/openui5/pull/3512) was merged and the testrecorder dialect will be available with OpenUI5  Version 1.105.

The dialect is already available in the current [nightly](https://openui5nightly.hana.ondemand.com/) build.
