### ISSUE TITLE
Native methods of UI5 aggregation items cannot be invoked for SmartFilterBar

### ISSUE THREAD

**Issue by rwnbiad** [ui5-community/wdi5#181]
**Describe the bug**
Similar to something what is described [here](https://js-soft.github.io/wdi5/#/usage?id=getaggregation), doesn't work for SmartFilterBar. Invoking `listItem.getTitle` doesn't work
```
const control = await browser.asControl(oListSelector)
const ui5ListItems = await control.getAggregation("items")
for (const listItem of ui5ListItems) {
  expect(await listItem.getTitle()).not.toBe("")
}
```
[SmartFilterBar](https://sapui5.hana.ondemand.com/#/api/sap.ui.comp.smartfilterbar.SmartFilterBar%23overview) has an aggregation called '[filterGroupItems](https://sapui5.hana.ondemand.com/#/api/sap.ui.comp.smartfilterbar.SmartFilterBar%23aggregations)' of type [sap.ui.comp.filterbar.FilterGroupItem](https://sapui5.hana.ondemand.com/api/sap.ui.comp.filterbar.FilterGroupItem). Each FilterGroupItem has a property called [label](https://sapui5.hana.ondemand.com/#/api/sap.ui.comp.filterbar.FilterItem%23methods/getLabel)

The below is my code. I'm just invoking the getLabelMethod
<img width="468" alt="image" src="https://user-images.githubusercontent.com/93357515/158013554-b4e34b0a-6ff7-4472-bfe2-3d4f51c77db7.png">

This doesn't work, because the native UI5 methods of FilterGroupItem don't seem to be available on each of the items in aggregation.
<img width="312" alt="image" src="https://user-images.githubusercontent.com/93357515/158013685-eace3d03-6f09-4c76-9f32-95e0b878042e.png">

This leads to a type error about missing function
<img width="324" alt="image" src="https://user-images.githubusercontent.com/93357515/158013745-62b6d6bb-b2cd-4e63-8a56-72fe2420b24e.png">

This seems broken in other places (other than SmartFilterBar) as well.
getRows on sap.ui.table.Table also has the same problem

**To Reproduce**
Invoke getLabel on items of filterGroupItems aggregation of SmartFilterBar

**Expected behavior**
The label of the filter item

**Logs/Console Output**
TypeError: item.getLabel is not a function

```shell
$> TypeError: item.getLabel is not a function
```

**Screenshots**
above

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 0.9.0-alpha.1
- `UI5` version: 1.98.0
- `wdio`-version (output of `wdio --version`): @wdio/cli (version: 7.16.16)
- `node`-version (output of `node --version`): v16.14.0
- OS: MacOS Monterey (12.2.1)
- Browser + Version [Chrome: Version 99.0.4844.51 (Official Build) (arm64)]

**Comment by vobu** [comment]
hi, thanks again for the detailed description of the issue 👍 
have you tried adding `interaction: "root"` to the selector? 
as in 
```javascript
const filterbar = {
  selector: {
     //...
    interaction: "root"
  }
}
```
`interaction: root` is a malevolent property from OPA5 land - we're currently collecting all controls requiring that property in order to eventually add it on the fly; so that in the code of the test, it can go away from the `selector`

**Comment by borceacristiann** [comment]
Hi, I have the same problem.
I tried to add **interaction: root**, but it still doesn't work.

Runtime Env:
- wdio-ui5-service-version: 0.9.10
- UI5 version: 1.96.0
- wdio-version (output of wdio --version): @wdio/cli (version: 7.20.5)
- node-version (output of node --version): v14.17.3
- OS: MacOS Monterey (12.5)
- Browser + Version [Chrome: Version 103.0.0 (Official Build) (arm64)]

**Comment by vobu** [comment]
I guess we'll have to look at the `SmartFilterBar` specifically, meaning we'll include exactly that use case in our own tests.
We'll get back to you two here!

**Comment by borceacristiann** [comment]
Sorry, I missed the fact that it was about the **SmartFilterBar**, in fact I have the same problem with **sap.ui.comp.filterbar.FilterBar**.
