### ISSUE TITLE
Login for real e2e tests

### ISSUE THREAD

**Issue by dominikfeininger** [ui5-community/wdi5#207]

**Comment by vobu** [comment]
yep, see https://github.com/orgs/js-soft/projects/1/views/4?filterQuery=extension

**Comment by dominikfeininger** [comment]
added script in this branch: https://github.com/js-soft/wdi5/tree/feature/e2eLogin 

maybe is misunderstood the requirements?

**Comment by vobu** [comment]
in the works

**Comment by dominikfeininger** [comment]
might be contributed by QMate Team

**Comment by T1mey** [comment]
What's the actual state ? Will this roadmap step provide authentication for testing of users with differnent permissions / roles ?

**Comment by vobu** [comment]
still WIP, with generic BTP login coming first. 
This also means that the roles/permissions for the UI5 app depend on the roles/permissions the logged in user has.

**Comment by T1mey** [comment]
> still WIP, with generic BTP login coming first. This also means that the roles/permissions for the UI5 app depend on the roles/permissions the logged in user has.

That means that the testuser will authenticate against the BTP and must exist there. As we're using an own IDP with certificate based login this will be a bit tricky, right? Will this scenario be supported?

**Comment by APatrina** [comment]
Hello colleagues, @vobu @dominikfeininger @T1mey, the priority of this ticket for our project is high now. It was raise on March,  and we are unable to integrate our e2e tests in an automated jenkins job.
Could you please increase the priority and provide information regarding deadlines of resolving this? Thank you very much.

**Comment by vobu** [comment]
there's been some back and forth on this topic - originally we thought that some SAP colleagues will contribute the authentication part, but that got stalled into the void.
so it's back to square one on this, albeit the original plans have not changed; meaning:
`wdi5` will support:
- standard BTP IdP login (w/ username + password)
- SAP Universal ID based login (w/ selector on what User Id to use)
- FLP login

with the standard IdP coming first.

given the current track record, I'll refrain from promising any delivery dates.
but hey, here's an idea: if it's super urgent for you @APatrina, why don't you give it a shot yourself? A good starting point would be to provide the login capability on the `wdi5` object itself https://github.com/js-soft/wdi5/blob/main/src/wdi5.ts - for usage in a WebdriverIO `before()`.

**Comment by dnzxy** [comment]
Hi, this issue has now been open for almost 7 months, with the last mention of it "being in the works" dating back to end of June. Very recently, during your [Devtoberfest session on wdi5](https://www.youtube.com/watch?v=f-0ztSnb2-c), @vobu, you reiterated that authentication features are "in the works". Is there any update on this? Any roadmap?

**Comment by vobu** [comment]
@monavari-lebrecht is leading the dev effort for this and still on it.
given that he's doing it in his spare time, things take longer than as if it'd be a paid dev effort.
that being said, would you have capacity to help? or a sponsorship opportunity?

**Comment by dominikfeininger** [comment]
solved with https://github.com/ui5-community/wdi5/releases/tag/v1.0.0-pre.1
