### ISSUE TITLE
Cannot find control when it's inside another control with `id="app"`

### ISSUE THREAD

**Issue by nicogeburek** [ui5-community/wdi5#259]
Hi all, I think I stumbled across something weird. When running the below test, it fails as soon a I add `id="app"` to the `<App />` control. If I remove it, the test passes again.

The error message is `button.getText is not a function`.

Chances are high I am just missing some crucial routing configuration or something regarding nested controls, but I couldn't find anything in the docs.

uimodule/webapp/test/basic.test.js
```JavaScript
const { wdi5 } = require("wdio-ui5-service")

const views = {
    Main: {
        _viewName: "com.sap.strokesgained.view.Main"
    }
}

describe("main page", () => {
    before(async () => {
        await wdi5.goTo("#/RouteMain")
    })

    it("should have button with text 'Capture'", async () => {
        const button = await browser.asControl({
            selector: {
                viewName: views.Main._viewName,
                properties: {
                    text: "Capture"
                }
            }
        })
        const buttonText = await button.getText()
        expect(buttonText).toEqual("Capture")
    })
})
```

uimodule/webapp/view/Main.view.xml
```XML
<mvc:View
    controllerName="com.sap.strokesgained.controller.Main"
    xmlns:mvc="sap.ui.core.mvc"
    displayBlock="true"
    xmlns="sap.m" >
    <App id="app"> <!-- remove id to make the test pass -->
        <Page title="{i18n>title}">
            <Button text="Capture" />
        </Page>
    </App>
</mvc:View>
```

uimodule/webapp/manifest.json (parts of it)
```JSON
    "routing": {
      "config": {
        "routerClass": "sap.m.routing.Router",
        "viewType": "XML",
        "async": true,
        "viewPath": "com.sap.strokesgained.view",
        "controlAggregation": "pages",
        "controlId": "app",
        "clearControlAggregation": false
      },
      "routes": [
        {
          "name": "Main",
          "pattern": "RouteMain",
          "target": [
            "TargetMain"
          ]
        }
      ],
      "targets": {
        "TargetMain": {
          "viewType": "XML",
          "transition": "slide",
          "clearControlAggregation": false,
          "viewId": "Main",
          "viewName": "Main"
        }
      }
    },
    "rootView": {
      "viewName": "com.sap.strokesgained.view.Main",
      "type": "XML",
      "async": true,
      "id": "app"
    }
```

- `wdi5/wdio-ui5-service`-version: 0.9.0
- `UI5` version: 1.96.0
- `wdio`-version (output of `wdio --version`): 7.19.7
- `node`-version (output of `node --version`): v16.9.1
- OS: MacOs 12.13.1
- Browser + Version Chrome 101.0.4951.64

**Comment by dominikfeininger** [comment]
Can you please test your app with the `#RouteMain` route and see whats beeing displayed.

Your routing config has `"controlId": "app",` so if you remove it it wont work as expected. Then I guess it navigates to the Main route automatically.

**Comment by nicogeburek** [comment]
Hi @dominikfeininger, `#/RouteMain` is always getting displayed and works fine, because it's the `rootView`, regardless of whether if have `id="app` in there. Removing `id="app"` obviously breaks the navigation, but seems to be the only way to make the test pass.

**Comment by nicogeburek** [comment]
To add to this: The test always passes "visually", I can see the `<Button text="Capture" />` in any case. It's just that the actual test fails as long is I have `id="app"` in there.

**Comment by dominikfeininger** [comment]
Would be happy to do a deep investigation myself. Can you please provide a full minimal example? Thx

**Comment by nicogeburek** [comment]
Sure! ▶️ https://github.com/nicogeburek/wdi5-test

Here are my observations so far:
- The test passes if I remove `id="app"` in the main view.
- The test passes if I set the pattern of the main route to `""` and leave the test as it is, which means keeping the `await wdi5.goTo("#/RouteMain")`, even if that route doesn't exist then.

**Comment by nicogeburek** [comment]
Correction: My second bullet point there is wrong. Test is still failing. Only way to make it pass is remove `id="app"`.

**Comment by nicogeburek** [comment]
Update: I moved the `<App id="app" />` shell into a separate `App.view.xml`, which is now the `rootView` and everything works as expected. Not sure why it didn't work with another file name (like `Main.view.xml`). Anyways, copying the structure of [your example](/https://github.com/js-soft/wdi5/tree/main/examples/ui5-js-app/webapp) works. I'm fine with closing the issue, but you can keep it open in case you want to investigate further - your call 😃

**Comment by dominikfeininger** [comment]
Hi, sry for the delay, quite busy here right now. Good to know and good you found a solution. Yes, will keep this issue open, hope I find some time in the future.
