### ISSUE TITLE
Cannot find type definition - (TS Types)

### ISSUE THREAD

**Issue by ddNils** [ui5-community/wdi5#273]
I was not able to reference the ts types in tsconfig like i would usually do. (by adding wdio-ui5-service to types)

I had to reference the types through
```
    "types": [
      "node",
      "webdriverio/async",
      "wdio-ui5-service/dist"
    ],         
```

which is inconvenient. It would be nice, if the types would be accessible directly in the wdio-ui5-service project.

**Comment by tompaulusch** [comment]
Hey, we'll take a look into it. :)

**Comment by vobu** [comment]
Would be cool to _not_ have to explicitly specify the types, but as we're transpiling into `/dist` of the `wdio-ui5-service` module, I currently don't know of a way to tell the TS compiler in a project "hey, please look for type definitions in `/dist` of the module"... @ddNils do you?
