### ISSUE TITLE
Fiori Elements test is failing

### ISSUE THREAD

**Issue by T1mey** [ui5-community/wdi5#290]
Hello,

we're testing a FE app and have a simple testcase which is failing.

```
Given.onTheMainPage.onTable().iExecuteCreate()
Then.onTheDetailPage.iSeeThisPage().and.iSeeObjectPageInEditMode()
```

If we're executing it a failure is occouring:

```
[chrome 102.0.5005.115 windows #0-0] 1) FE basics should see an object page
[chrome 102.0.5005.115 windows #0-0] javascript error: Cannot read properties of undefined (reading 'waitForUI5')
JavaScript stack:
TypeError: Cannot read properties of undefined (reading 'waitForUI5')
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:5:14)
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:17:8)
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:17:33)
    at executeAsyncScript (<anonymous>:552:47)
    at <anonymous>:567:29
    at callFunction (<anonymous>:446:22)
    at <anonymous>:460:23
    at <anonymous>:461:3
  (Session info: chrome=102.0.5005.115)
[chrome 102.0.5005.115 windows #0-0] javascript error: javascript error: Cannot read properties of undefined (reading 'waitForUI5')
[chrome 102.0.5005.115 windows #0-0] JavaScript stack:
[chrome 102.0.5005.115 windows #0-0] TypeError: Cannot read properties of undefined (reading 'waitForUI5')     
[chrome 102.0.5005.115 windows #0-0]     at eval (eval at executeAsyncScript (:552:26), <anonymous>:5:14)      
[chrome 102.0.5005.115 windows #0-0]     at eval (eval at executeAsyncScript (:552:26), <anonymous>:17:8)      
[chrome 102.0.5005.115 windows #0-0]     at eval (eval at executeAsyncScript (:552:26), <anonymous>:17:33)     
[chrome 102.0.5005.115 windows #0-0]     at executeAsyncScript (<anonymous>:552:47)
[chrome 102.0.5005.115 windows #0-0]     at <anonymous>:567:29
[chrome 102.0.5005.115 windows #0-0]     at callFunction (<anonymous>:446:22)
[chrome 102.0.5005.115 windows #0-0]     at <anonymous>:460:23
[chrome 102.0.5005.115 windows #0-0]     at <anonymous>:461:3
[chrome 102.0.5005.115 windows #0-0]   (Session info: chrome=102.0.5005.115)
[chrome 102.0.5005.115 windows #0-0]     at getErrorFromResponseBody (C:\develop\javascript\onboarding-tool-cap\node_modules\webdriver\build\utils.js:197:12)
[chrome 102.0.5005.115 windows #0-0]     at NodeJSRequest._request (C:\develop\javascript\onboarding-tool-cap\node_modules\webdriver\build\request\index.js:166:60)
[chrome 102.0.5005.115 windows #0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5) 
[chrome 102.0.5005.115 windows #0-0]     at async Browser.wrapCommandFn (C:\develop\javascript\onboarding-tool-cap\node_modules\@wdio\utils\build\shim.js:137:29)
[chrome 102.0.5005.115 windows #0-0]     at async Browser.wrapCommandFn (C:\develop\javascript\onboarding-tool-cap\node_modules\@wdio\utils\build\shim.js:137:29)
[chrome 102.0.5005.115 windows #0-0]     at async emptyQueue (C:\develop\javascript\onboarding-tool-cap\node_modules\wdio-ui5-service\client-side-js\testLibrary.js:33:12)
```

Seems that the error is coming from the second line, because a draft record is created.

Another question is when to use which object (Given, When and Then) .... is there a more detailed documentation for FE?

**Comment by Siolto** [comment]
Hi,

could you maybe share you're whole spec file, that we can see that you initialized the FE test library the right way. Unfortunately the documentation about the integration of the test library in wdi5 is not merged yet but there is already a [PR](https://github.com/js-soft/wdi5/pull/279) available.

In wdi5 itself we do not use the Given(arrangements), When(actions), Then(assertions) pattern. This comes from OPA5 itself. Maybe you can have a more detailed look [here](https://sapui5.hana.ondemand.com/#/topic/2696ab50faad458f9b4027ec2f9b884d).

Best regards,
Simon

**Comment by T1mey** [comment]
This is our configuration:
```
const { join } = require("path")

exports.config = {
    wdi5: {
        screenshotPath: join("app", "onboarding_tool", "webapp", "wdi5-test", "__screenshots__"),
        logLevel: "verbose", // error | verbose | silent
        url: "/tool/webapp/index.html",
        waitForUI5timeout: 30000,
    },
    //// wdio runner config
    specs: [join("app", "tool", "webapp", "wdi5-test", "**/*.test.js")],
    // Patterns to exclude.
    exclude: [],
    //// capabilities ("browser") config
    maxInstances: 10,
    capabilities: [
        {
            // overwrite global "maxInstances"
            maxInstances: 5,
            browserName: "chrome",
            acceptInsecureCerts: true,
            "goog:chromeOptions": {
                args:
                    process.argv.indexOf("--headless") > -1
                        ? ["window-size=1440,800", "--headless"]
                        : process.argv.indexOf("--debug") > -1
                        ? ["window-size=1920,1280", "--auto-open-devtools-for-tabs"]
                        : ["window-size=1440,800"]
            }
        }
    ],
    //// test config
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: "error",
    bail: 0,
    baseUrl: "http://localhost:4004",

    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,

    services: ["chromedriver", "ui5"],

    framework: "mocha",
    mochaOpts: {
        ui: "bdd",
        timeout: 120000
    },
    reporters: ["spec"]
}
```

**Comment by Siolto** [comment]
At first look your configuration looks fine. Did you initialized the test library the same way we did it in one of our [examples](https://github.com/js-soft/wdi5/blob/main/examples/fe-app/app/incidents/webapp/wdi5-test/Journey.test.js)?

**Comment by T1mey** [comment]
Yes, the same way...

**Comment by Siolto** [comment]
Hi,

just replaced our first test with your coding
![image](https://user-images.githubusercontent.com/32054457/175276928-91320d6b-4c75-40d4-b5e5-ed2c476e6029.png)
And it seems to work:
![image](https://user-images.githubusercontent.com/32054457/175277410-209011c8-f62d-4a11-997a-1baf0e841203.png)

**Comment by T1mey** [comment]
Yes .. the `npm run build`  didi it ... I'm able to run your samples ...
So I will try to compare the configuration & execution ... as our apps are similar this sould solve the problems...

Let's see... I will update onthe results.

**Comment by vobu** [comment]
here's -hot off the press- the docs for the test lib integration in `wdi5`: https://js-soft.github.io/wdi5/#/fe-testlib

**Comment by T1mey** [comment]
@Siolto @vobu 

We found the problem ... the code is only working if in manifest.json the table on the main page is having the option

` "initialLoad": false`

if we change it to true the above mentioned code is failing...
Why this have inflence on the object page... we don't know.

Seems to be a bug.

**Comment by vobu** [comment]
excellent! ain't testing great?! you actually find (and fix!) bugs through it 😄

**Comment by T1mey** [comment]
> excellent! ain't testing great?! you actually find (and fix!) bugs through it 😄

@vobu 
In that case not really ... as we want to have the list loaded on startup. So I think it's a bug in testing wdi5

**Comment by T1mey** [comment]
@vobu 

Just add 

`"initialLoad": true`

to

https://github.com/js-soft/wdi5/blob/84e36240af92d69439cafcdc2109ce63acaa909a/examples/fe-app/app/incidents/webapp/manifest.json#L113

in cobination with 

```
Given.onTheMainPage.onTable().iExecuteCreate()
Then.onTheDetailPage.iSeeThisPage().and.iSeeObjectPageInEditMode()
```

**Comment by T1mey** [comment]
> Hi @T1mey,
> 
> cool that you found the issue! But I am not sure if this is a bug in wdi5 itself or on the actual test library. Maybe @ARiesterer could help us here.

Maybe keep the ticket open

**Comment by ARiesterer** [comment]
I´ll have a look if this test sequence with the initialLoad leads to any issues on our internal OPA tests.

**Comment by ARiesterer** [comment]
I just tested the following sequence with a RAP application (manifest setting InitialLoad=true):

            opaTest('#0: ListReport: Check creating a new item with setting InitialLoad=true', function(Given, When, Then) {
                When.onTheMainPage.onTable().iExecuteCreate();
                Then.onTheDetailPage.iSeeThisPage().and.iSeeObjectPageInEditMode();
                When.onTheShell.iNavigateBack();
                When.onTheDetailPage.onMessageDialog().iSelectDraftDataLossOption("draftDataLossOptionDiscard");
                When.onTheDetailPage.onMessageDialog().iConfirm();
                Then.onTheMainPage.iSeeThisPage();
           });

got this result:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/9048637/175541072-983ac9ab-a19e-47b1-94c5-40b3653a0ec7.png">

So from test-lib side it should be ok. Pressing the Create button to go to the ObjectPage should be independent from the InitialLoad parameter.

**Comment by T1mey** [comment]
> I just double checked our example (with and without `initialLoad: true`) and both cases run green for me. There has to be something else that is causing the issue. Maybe some weird side effects with the `initialLoad` flag.

I can offer a live demo via teams...

**Comment by T1mey** [comment]
> > I just double checked our example (with and without `initialLoad: true`) and both cases run green for me. There has to be something else that is causing the issue. Maybe some weird side effects with the `initialLoad` flag.
> 
> I can offer a live demo via teams... no I can't because now it's working with true as well.
> 
> What I did in the meantime is to update chromedriver to 103 (I think from 102) ...

@Siolto  @ARiesterer 

I did a mistake by adding the initial load property again... so even with 103 it is not working for us and reproducable.

**Comment by Siolto** [comment]
@T1mey we can schedule a call if you want. Can you send me your email?
