### ISSUE TITLE
Calling press() on control that was not found leads to follow up errors

### ISSUE THREAD

**Issue by brunohaller** [ui5-community/wdi5#304]
**Describe the bug**
I am using the .press() method as mentioned in https://ui5-community.github.io/wdi5/#/usage?id=press
When the control was not found, the press() method keeps on looping (in native wdio until timeout?) and producing errors in the log not finding an "undefined" control:

**To Reproduce**

```
    const control = await browser
      .asControl({
        selector: {
          id: "controlThatDoesNotExist",
        },
      });
    await control.press();
```

**Expected behavior**
The press method should immediately fail, if the control could not be found instead of trying to look up an element with undefined id.

**Logs/Console Output**

```
[0-0] 2022-07-08T19:15:45.873Z INFO webdriver: COMMAND findElements("xpath", "//*[@id="undefined"]")
[0-0] 2022-07-08T19:15:45.874Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/efcd66f31c05c1ff148fe1fd10cf738f/elements
[0-0] 2022-07-08T19:15:45.874Z INFO webdriver: DATA { using: 'xpath', value: '//*[@id="undefined"]' }
[0-0] 2022-07-08T19:15:45.885Z INFO webdriver: RESULT []
```

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version:  0.9.9
- `UI5` version:  1.102.0
- `wdio`-version (output of `wdio --version`): 7.20.5
- `node`-version (output of `node --version`): v14.19.3
- OS: Windows 10
- Browser + Version Chrome 103

**Comment by brunohaller** [comment]
Additional information: Basically this is a general issue with all methods that are called after a control has not been found / not been successfully initialized. In the case of a press event() it is special, as it causes the above error.


But generally, if for example calling a method like "getText()" on a control that was not found, you will get follow up errors like
`getText() is not a function`. Native WDIO seems to handles this situation slightly different and tells you in a generic way something like `Can not call getText(), because element ... could not be found`.

**Comment by vobu** [comment]
thanks for providing detailed insight into failed control localization 👍
and you're right, the retries on not-located controls is something wdio-native - i am not aware of an option to short-circuit this. 
however we sure could improve the error message on non-existent and/or failed API-calls. 
Source is here: https://github.com/ui5-community/wdi5/blob/2f0f95bba03f631739312cb8a041fe37b6ff9ca6/client-side-js/executeControlMethod.js#L41
want to give it a shot 🤗 ?

**Comment by brunohaller** [comment]
I think the error message is not the main problem. 

In our environment for some weird reason we have a huge wdio timeout of 2 minutes, that means after a failed control location and invoking press(), we get 2 minutes long the above error message that no control with id undefined can be found. This is distracting a lot from the actual problem, which is correctly reported.

I think the code is here.

https://github.com/ui5-community/wdi5/blob/027300e673c94f93ad85581131f1a6b6fe214169/src/lib/wdi5-control.ts#L199-L201

Could that be improved somehow to not even try finding an element if the control is not initialized? I am not sure how that should be done exactly and at which places, but I assume at least for `press()` or `enterText()` it would be helpful

**Comment by vobu** [comment]
> I think the code is here.
> https://github.com/ui5-community/wdi5/blob/027300e673c94f93ad85581131f1a6b6fe214169/src/lib/wdi5-control.ts#L199-L201
> Could that be improved somehow to not even try finding an element if the control is not initialized? I am not sure how that should be done exactly and at which places, but I assume at least for `press()`` it would be helpful, as looking for an id 'undefined' never makes sense

good idea - makes absolute sense, we'll do that 👍
might take a couple of days though as almost all of the core contributors are on vacation 🏝😁
