### ISSUE TITLE
How to prevent rare timing issue with busy indicator

### ISSUE THREAD

**Issue by brunohaller** [ui5-community/wdi5#305]
**Describe the bug**

We are in the process to migrating to WDI5.
We still have some WDIO native logic, which interacts with the launchpad and clicks on a tile.using something like this

```
        await tile.waitForDisplayed({ timeout: 20000, timeoutMsg:`Launchpad tile is not visible for ${tileName}` });
        await tile.scrollIntoView();
        await tile.click();
```

Immediately after that we try to find a navigation menu in the app that should open, using WDI5:

```
    const control = await browser
      .asControl({
        selector: {
          id: "application-SystemConfig-maintain-component---fcl--navigationcustomerTagffs",
        },
      });
    await control.press();
```

Now for some reason, this works 90%, but rarely fails immediately (no waiting for timeout) with 

```
{
	"status": 1,
	"messsage": "Error: No DOM element found using the control selector {\"id\":\"application-SystemConfig-maintain-component---fcl--navigationcustomerTags\"}"
}
```

In the recorded video, I can see that at the time of the failure the launchpad is still visible with busy indicator and the app has not loaded.

How can we troubleshoot it? It brings some flakiness into our tests, which we do not want obviously.

**Screenshots**

![image](https://user-images.githubusercontent.com/73822257/178093646-55c17738-e7c7-4962-93ef-7ee08087ba5d.png)

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version:  0.9.9
- `UI5` version:  1.102.0
- `wdio`-version (output of `wdio --version`): 7.20.5
- `node`-version (output of `node --version`): v14.19.3
- OS: Windows 10
- Browser + Version Chrome 103

**Comment by vobu** [comment]
thanks for providing detailed context for your issue 👍
my hunch for the cause of the observed behavior is on slow performance of the app itself - we have seen similar behavior in FE apps. Increasing the timeout (`waitForUI5Timeout`, https://ui5-community.github.io/wdi5/#/configuration) might be a remedy.

**Comment by brunohaller** [comment]
It is already at 60 seconds, but the error occurs after 1 sxecond or so...

But interestingly it has not occured now for a week or so, so I consider it solved for now
