### ISSUE TITLE
get Control Properties not working in MS Edge

### ISSUE THREAD

**Issue by MGuentherGits** [ui5-community/wdi5#306]
When selecting a control and trying to access the properties (like getText() on a sap.m.Text-Control) is not working when executing the test in Microsoft edge.
You can easily verify when cloning this repository and changing the wdio.conf in the examples to use the edge browser.

I tried it with wdio-ui5tooling.conf.js and adding the capabilities -> browserName: 'edge'. Here is the full config:

const { join } = require("path")
const { baseConfig } = require("./wdio.base.conf")
const merge = require("deepmerge")

const _config = {
    wdi5: {
        url: "index.html"
    },
    capabilities: [{
        browserName: 'edge'
    }],
    specs: [join("webapp", "test", "e2e", "basic.test.js"), join("webapp", "test", "e2e", "hash-nav.test.js")],
    baseUrl: "http://localhost:8080"
}

exports.config = merge(baseConfig, _config)

When executing the test (run "npm run test:ui5tooling") I am facing the error
Evaluation failed: script timeout

The control itself seems to be selected correctly, because for example the press()-Function is working.

Could you please check what is going on there?

Microsoft Edge Version: 103.0.1264.49

Thanks a lot and best regards,
Michael

**Comment by vobu** [comment]
pardon my naïve question: you do have the EdgeDriverService https://webdriver.io/docs/wdio-edgedriver-service/ installed and configured, right?

**Comment by MGuentherGits** [comment]
Hi @vobu ,

I am so sorry, you are right. I missed the egedriver part in the services. When entering that, everything works fine.

I will close the issue. Sorry again.

Best regards,
Michael

**Comment by vobu** [comment]
no worries, glad you have it working 👍
