### ISSUE TITLE
Cannot use ui5 methods on sap.m.Table

### ISSUE THREAD

**Issue by Mic4mi** [ui5-community/wdi5#308]
Hello everyone!

I cannot get sap.m.Table control to use UI5 methods like getItems(). Trying to call it throws "getItems is not a function". Tried to use id of the control and controlType without success. 

Does anyone have any idea what I might be doing wrong? Thanks in advance.
![tablecontrol](https://user-images.githubusercontent.com/61918959/179798653-47c3279e-b040-4831-8776-39e67db091b5.png)

Fragment of my code

`        const Table = await browser.asControl({
            selector: {
                viewName: Main._viewName,
                id: "idProductsTable",
                controlType: "sap.m.Table"
            }
        })`

**Comment by Siolto** [comment]
Hi Micaela,

It looks like the table wasn't actually found. As seen with an **undefined** value for the `_domId` and the **false** value for the `_initialistion`. There should be another error message that indicates, that the control was not found. 

We know that the error message is a little bit misleading currently. There is already an [issue](https://github.com/ui5-community/wdi5/issues/304) opened to improve the message output when you try to execute a method on a control that was not found.
