### ISSUE TITLE
contact https://github.com/msg-systems/ui5-testrecorder/ for introducing wdi5 dialect

### ISSUE THREAD

**Issue by vobu** [ui5-community/wdi5#313]

**Comment by nicogeburek** [comment]
mail sent out

**Comment by nicogeburek** [comment]
I talked to @martenAdrian, who is currently working on refactoring the ui5-testrecorder and building a more solid backbone. The goal is to be able to republish it to the Chrome Web Store. Once a first dev version is ready to be checked out, the wdi5 community is welcome to contribute and possibly enhance the testrecorder with new test dialects and features.

**Comment by vobu** [comment]
i'll close this one as it happened and co-op will happen :)
