### ISSUE TITLE
Extend recipes documentation with multi browser examples

### ISSUE THREAD

**Issue by maiargu** [ui5-community/wdi5#316]
**Describe the bug**
We have a rather complicated end to end test case scenario, but nothing not manageable with an e2e test framework (in my opinion).
Let me explain:
- we have 2 frontends: 
  -  `frontendA` is coded with UI5 (for managing business partners)
  -  `frontendB` is coded with angular (a webshop where business partners can login and order items)
- we have an admin user `userA` that will login into `frontendA` (by using the chrome browser for example) and create a new business partner by typing first name, last name, email address and click save button
- in the backend the magic starts happening and the new business partner is persisted in the DB with a default initial login password
- `userB` will be able to login into `frontendB` (by using the firefox browser for example) by using the email address and the default initial password
- `userB` will place an order in `frontendB` webshop
-  a live statistic notification with number of orders increased +1 will be visible in `frontendA`

To be able to implement this test case scenario we wanted to use the _capabilities_ configuration option from webdriverIO https://webdriver.io/docs/options/#capabilities-1 and have multiremote 2 browser instances.

And here the whole configuration hell started.

For one browser instance we want to `skipInjectUI5OnStart` and after a successful login (the login page from the authentication provider service does not contain UI5 controls) we want to inject wdi5 service.
For the other browser instance we don't even need wdi5, since it's written in angular.

**Expected behavior**
I would have wished for a better documentation regarding the whole multi browser configuration for wdi5.
Please think about extending the documentation here, since this kind of recipe might be also helpful for developers trying to test chatbot applications.

I also see that "login for e2e real test cases" is on the road map https://github.com/ui5-community/wdi5/issues/207 with the first intention to add support for standard BTP IdP login (w/ username + password).
Please also take into consideration extending the documentation how it's supposed to work with multi remote configuration when one browser instance would use the BTP IdP login and the other browser instance won't.

**Comment by vobu** [comment]
the scenario/use-case you describe is spot-on for the multi-remote feature of `wdi5` 👍 
and I take it you've gained quite some experience with coding multi-remote tests in `wdi5`!
given [that it's pretty easy to contribute to the documentation](https://ui5-community.github.io/wdi5/#/contributing?id=work-on-the-docs), would you mind giving this a shot?
as you stated, many would benefit from that.
thanks in advance!
