### ISSUE TITLE
List.getItems() is not a function

### ISSUE THREAD

**Issue by Mic4mi** [ui5-community/wdi5#319]
Hello experts! I am currently writing a test that should allow to validate the number of items that a list can have. However, I am encountering the error "List.getItems is not a function", which is strange to me, since the selector is perfectly capable of finding the list.

This is my test
![image](https://user-images.githubusercontent.com/61918959/182234065-280ca5d5-83ec-4fa0-abff-f73afe86b04c.png)

These are the results of the 'List' variable, so you can see that the **domId** was found
![image](https://user-images.githubusercontent.com/61918959/182234322-b21a8a6c-a1e5-4587-9575-e5755c5c17d9.png)

This is my output
![image](https://user-images.githubusercontent.com/61918959/182234827-63ba3fc2-982f-4c66-b4b4-a71bd310687d.png)

I also tried with 'getAggregation("items")', but it returns 0, which can't be feasible since it seems to return the correct value when I get the 'StandardListItem'. 
![image](https://user-images.githubusercontent.com/61918959/182235714-ae5e2af2-aa58-4016-b2be-af7c11365bf7.png)

![image](https://user-images.githubusercontent.com/61918959/182235846-c1710465-5013-44c2-9717-917dac18872b.png)

![image](https://user-images.githubusercontent.com/61918959/182236065-588dff38-907d-4a4d-80ba-90276db731de.png)

![image](https://user-images.githubusercontent.com/61918959/182236809-f8970af3-b932-42f1-8d36-70a9809b7472.png)

![image](https://user-images.githubusercontent.com/61918959/182236227-b7803ca7-bf0c-49c9-9871-766a15427aee.png)

My team and I started using wdi5 very recently, so we are still learning. I look forward to your comments!

Thank you in advance.

**Comment by vobu** [comment]
> the selector is perfectly capable of finding the list.

try adding `interaction: "root"` to the selector:
```js
selector: {
   interaction: "root",
   controlType: "sap.m.List",
  // …
}
```
this property stems from the OPA5 matchers we‘re using and is a well know trap 🪤 😄
documentation for this is upcoming in #285

**Comment by Mic4mi** [comment]
That seems to have worked out perfectly! Thank you very much for resolving my questions so quickly. 
I will keep an eye out for further updates and will follow your advice. 

Best regards!
