### ISSUE TITLE
WDI5 Installation Procedure Fails

### ISSUE THREAD

**Issue by marco-paciucci** [ui5-community/wdi5#322]
Hello everyone,

as per the official documentation I've run the command:

`npm init wdi5`
and it copies `wdio.conf.js` into place, installs `wdio+wdi5 `and adds them as dev dependencies.

However there's a subsequent step which fails:

` adding wdi5 start command ("wdi5") to package.json...`
with this output:

```
Usage: npm <command>
where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami
npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview
Specify configs in the ini-formatted file:
    C:\Users\xxxx\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config
npm@6.14.14 C:\Program Files\nodejs\node_modules\npm
Did you mean this?
    run-script
(node:17496) UnhandledPromiseRejectionWarning: Error: Command failed: npm set-script wdi5 "wdio run wdio.conf.js"
    at checkExecSyncError (child_process.js:760:11)
    at execSync (child_process.js:833:15)
    at C:\Users\xxxx\AppData\Roaming\npm-cache\_npx\28096\node_modules\create-wdi5\dist\index.js:41:38
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\paciucma\AppData\Roaming\npm-cache\_npx\28096\node_modules\create-wdi5\dist\index.js:5:58)
```
I have tried many times to no avail.

Can anybody help?

**Comment by vobu** [comment]
please make sure you're using a LTS version of `node` along with at least `npm` >= 7

**Comment by marco-paciucci** [comment]
Node v14.17.4, 
npm {
  'openui5-sample-app': '0.2.0',
  npm: '6.14.14',
  ares: '1.17.1',
  brotli: '1.0.9',
  cldr: '39.0',
  icu: '69.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.17.4',
  openssl: '1.1.1k',
  tz: '2021a',
  unicode: '13.0',
  uv: '1.41.0',
  v8: '8.4.371.23-node.76',
  zlib: '1.2.11'
}

**Comment by marco-paciucci** [comment]
That's now better however there's still an issue.
There's no such [npm run test:ui5tooling](url)
I've created a test folder into [openui5-sample-app ](url)which contains [wdio.conf.ts ](url)and t[sconfig.json ](url)along with another subfolder specs containing [sample.spec.ts](url)
When I run [wdio ](url)wdio.conf.js I get ['wdio' is not recognized as an internal or external command,](url)

How can I move along?

**Comment by marco-paciucci** [comment]
I will open up a new issue then. That one can be considered closed
