### ISSUE TITLE
object is not iterable

### ISSUE THREAD

**Issue by marco-paciucci** [ui5-community/wdi5#325]
Hello,
I've coded this test here:

```
		const listSelector = { 
			 selector: {
					controlType: "sap.m.List",
					viewName: "sap.ui.demo.todo.view.App" 
			 }
		}
		  
		const checkedItems = await browser.asControl(listSelector).getItems();
		const checked = 0
		for (const item of checkedItems) {
		  if (await item.getChecked()) { checked++ }
		}
		expect(checked).toBe(2);
```

But I'm getting: `checkedItems is not iterable`
The list is displayed on the screen and I don't know why I am getting that error.
I have added `await browser.debug();` which stops the execution but in the console I cannot type [await browser.asControl(listSelector).getItems();](url) because the console is not attached to the current flow of execution and I don't know if it's ever possible to debug and to what extent (I don't want to debug the original javascript file but the spec js).

**Comment by vobu** [comment]
debuggin a `wdi5` test is pretty easy as it adheres to Node.js debugger/`--inspect` setting.
E.g. in VS Code, start a "JavaScript Debug Terminal"...
![image](https://user-images.githubusercontent.com/6573426/183587734-a401fa90-633a-42c8-9acf-6bb9c90da1d7.png)
...and run `wdi5` from there, e.g. via `npm run wdi5` (or whatever npm script you've chosen).
Then add breakpoints in the test source...
![image](https://user-images.githubusercontent.com/6573426/183588279-7084cda3-b938-4831-8a02-2ee3db11abe7.png)
...and `wdi5` will halt execution at that point.
(Reminds me: we'll still need a [recipe](https://ui5-community.github.io/wdi5/#/recipes) for debugging, will put it in the issues list.)
Then you can look at `checkedItems` in the debugger and examine why it's not iterable.

**Comment by marco-paciucci** [comment]
Hello, 
thank you very much for giving the recipe to debug.
I don't know why but it seems that the list of items is empty even though in the last image you can see that it's not.
What could the issue be?
![image](https://user-images.githubusercontent.com/47173467/183649849-6f65d17f-cb36-4473-9e0a-38a8da67cd5e.png)
![image](https://user-images.githubusercontent.com/47173467/183650007-b0d25680-5ba4-4e30-b6c9-a8ea129f43cd.png)

**Comment by vobu** [comment]
i guess you're missing `interaction: "root"` on the selector - see #319 
```js
selector: {
  controlType: "...",
  interaction: "root"
}
```

**Comment by marco-paciucci** [comment]
Thank you very much, that did the trick.
One more question.
If I need to add some text to sap.m.input and fire the change event, how can this be done? Do I need to raise a separate issue?

![image](https://user-images.githubusercontent.com/47173467/183673416-366613a9-53e8-47fe-8ba0-a88821b418d3.png)

![image](https://user-images.githubusercontent.com/47173467/183673591-c21fd969-a0e0-492a-b573-6395b4789225.png)

The statement I've added doesn't raise the change event. How can this be done in wdi5?

**Comment by marco-paciucci** [comment]
Hello,
I've managed to find a solution:
 		`await oControl.enterText("Restart the server");`
I think that you should enhance the "Recipe" sections with more examples.
Thanks .

**Comment by vobu** [comment]
> I've managed to find a solution:
> `await oControl.enterText("Restart the server");`
> I think that you should enhance the "Recipe" sections with more examples.

given [how easy it is to contribute to the documentation](https://ui5-community.github.io/wdi5/#/contributing?id=work-on-the-docs), would you mind giving this a shot? 
as you stated, many would benefit from that.
thanks in advance!
