### ISSUE TITLE
Testing with different user & roles

### ISSUE THREAD

**Issue by T1mey** [ui5-community/wdi5#334]
Hello @all,

after update from 

```
"chromedriver": "^103.0.0", --> "^104.0.0"
"wdio-ui5-service": "^0.9.4" --> "^0.9.10"
```

we're not able to test with differnt users & roles anymore.
Before adding credentials to the baseUrl in wdi5.conf did the trick...

`baseUrl: "http://user:pass@localhost:4004",`

After the update chrome console is logging 

![image](https://user-images.githubusercontent.com/10464878/186595965-96d7803b-253b-4683-9f9f-8ce6fb29e483.png)

`Failed to execute 'fetch': Request cannot be constructed from a URL that includes credentials:./manifest.json`

Is there any support for calling the application with credentiasl in the meantime within wdi5 ? 
Or is there any way to influence the chrome behaviour ?

**Comment by vobu** [comment]
there's nothing we're fiddling around with regarding credentials in `wdi5`.
Is that `fetch` done manually by the app or is it within UI5? If the latter, a UI5 upgrade might be the root cause.

**Comment by T1mey** [comment]
You're right ... this is a new feature in SAPUI5... So from 104 upwards it is not working anymore.
Last version where this is working is 1.103.1 ... 

So maybe they added a configuration for that behaviour ... Will start searching
