### ISSUE TITLE
Table.selectAll is not a function

### ISSUE THREAD

**Issue by ZhanJohnny** [ui5-community/wdi5#336]
**Describe the bug**
After geting the table object using browser.asControl(), the table is a UI table. In UI5 API, there is a selectAll method , but when try to call table.selectAll() method in WDI5, it show below error message: **TypeError: oTable.selectAll is not a function**
Checkbox of selectAll in table UI is invisible , So i had to use selectAll method.

**To Reproduce**

**Expected behavior**

**Logs/Console Output**
if applicable, please copypasta _code-fenced_ log output, e.g.

```shell
$> ...
```

**Screenshots**
if applicable, add screenshots to help explain your problem.

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: [e.g. 0.8.1]
- `UI5` version: [e.g. 1.98.0]
- `wdio`-version (output of `wdio --version`): [e.g. 7.16.12]
- `node`-version (output of `node --version`): [e.g. v17.3.0]
- OS: [e.g. Linux openSuSE]
- Browser + Version [e.g. chrome 97.0.4692.71]

**Additional context**
Add any other context about the problem here,
e.g. any options the target browser is started with like `--headless` or
if the tests run in a CI environment

**Comment by vobu** [comment]
Hi, could you please fill in the additional info that is asked for in the template.
It makes tracking down things easier. Thanks in advance!

**Comment by vobu** [comment]
even though you provided no additional information, I coded a minimal reproducible sample:

(typescript)
```ts
const table: Table = await browser.asControl({
      selector: {
          id: "sap.m.Table",
          viewName: "test.Sample.tsapp.view.Main",
          interaction: "root"
      }
  })
  await table.selectAll() // <-- works just fine
```

After locating the `sap.m.Table` successfully, `selectAll()` works as intended in `wdi5`.
So I suspect you're control locator didn't work, so subsequently, `selectAll()` can't be called.
