### ISSUE TITLE
Can't retrieve Control by Id using selector

### ISSUE THREAD

**Issue by fIannazzo** [ui5-community/wdi5#343]
**Describe the bug**
I have added the wdi5 framework to the openui5 sample app to play around with the framework.
I'm trying to select the List Item by using an selector on id field

`const selector = {
			forceSelect: true,
			selector: {
				id: "container-todo---app--todoList",
			},
};`

const oList = await browser.asControl(selector);
console.log("List ID " + (await oList.getId()));

**To Reproduce**
Steps to reproduce the behaviour:

Clone https://github.com/fIannazzo/openui5-sample-app and run 

`node_modules/.bin/wdio run wdio.conf.js` in Debug console.

**Expected behavior**
I would expect oList.getId() to be something like "container-todo---app--todoList" but ID is "container-todo---app--todoList-trigger".  Seems the selector for id does not work correctly.

**Logs/Console Output**
<img width="950" alt="Screenshot 2022-09-14 at 10 28 57" src="https://user-images.githubusercontent.com/6567750/190103045-c6dee270-7b50-4357-8351-765d85362d75.png">

**Screenshots**
<img width="1092" alt="Screenshot 2022-09-14 at 10 16 37" src="https://user-images.githubusercontent.com/6567750/190100123-c2662a90-71af-4e4d-8b34-e92e133ff990.png">

Expected the green as id, but getting the red one with trigger at the end. 

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 0.9.12
- `UI5` version: 1.106.0
- `wdio`-version (output of `wdio --version`):  7.24
- `node`-version (output of `node --version`): 18.8.0
- OS: Mac OS on M1
- Browser + Version : Chrome 105.0.5195.102

**Additional context**
Add any other context about the problem here,
e.g. any options the target browser is started with like `--headless` or
if the tests run in a CI environment

**Comment by vobu** [comment]
you're most likely missing `interaction: "root"` in the selector.
it's a UI5 core/OPA5 thingie for retrieving controls that we documented at https://ui5-community.github.io/wdi5/#/recipes?id=using-interaction-on-a-selector

**Comment by Siolto** [comment]
As @vobu already written: The `interaction: "root"` selector is missing. I also had a look at your test and saw that you use the _lateInjection_ of `wdi5` even though you are directly starting the tests in an UI5 Application. I updated your script a little bit and this works fine:

```javascript
describe("My Login application", () => {
	it("before", async () => {
		const selector = {
			forceSelect: true,
			selector: {
				id: "container-todo---app--todoList",
				interaction: "root"
			},
		};
		const oList = await browser.asControl(selector);
		expect((await oList.getItems()).length).toEqual(2)
	});
});
```
