### ISSUE TITLE
Error: stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by marco-paciucci** [ui5-community/wdi5#345]
Hello, 
I have implemented a pretty complex scenario and I've coded this:

```
		let oRiskInputSelector = {
			selector: {
				controlType: "sap.m.Input",
				id: "RiskOpp",
				viewName: "Risk",
				interaction: "focus"
			}
		}
		let oRiskInput2 = await browser.asControl(oRiskInputSelector); 
                await oRiskInput2.setValue("test");
```
The command setValue returns the error above. What am I doing wrong?

**Comment by vobu** [comment]
`oRiskInput2` vs `$oRiskInput2` ?!?

**Comment by marco-paciucci** [comment]
There was a type in the code I copied in, without $ sign. I tried to getWebElement and use $ but that doesn't work either

**Comment by Siolto** [comment]
Hi @marco-paciucci,

a little bit more context and your error message would be nice to have! Why can't you just use `enterText`?

```javascript
let oRiskInputSelector = {
			selector: {
				controlType: "sap.m.Input",
				id: "RiskOpp",
				viewName: "Risk",
				interaction: "focus"
			}
		}
		await browser.asControl(oRiskInputSelector).enterText("test"); 
```

The [UI5 Testrecorder](https://blogs.sap.com/2020/01/23/test-recording-with-ui5-test-recorder/) could also help you to improve the performance of writing your tests. There is now also a dedicated [`wdi5`](https://blogs.sap.com/2022/08/11/wdi5-dialect-in-ui5s-test-recorder/) dialect.

**Comment by marco-paciucci** [comment]
I've tried your suggestion but I'm getting this error:

`[wdi5] reusing internal control with id RiskOpp.ibp.ibpbaseplanningobjectmanagement-v2.view.Risksap.m.Input
[0-0] [wdi5] Can not call "enterText,_controlSelector,selector,interactWithControl,_browserInstance,executeAsync,options,beforeCommand,options,beforeCommand,apply", because control could not be found
[0-0] [wdi5] Can not call "enterText,_controlSelector,selector,interactWithControl,_browserInstance,executeAsync,options,beforeCommand,options,beforeCommand,apply,executeAsyncScript,options,beforeCommand,options,beforeCommand,apply", because control could not be found`

What's wrong?

**Comment by vobu** [comment]
the message clearly states 
**`control could not be found`**
so please check whether your selector is working

**Comment by marco-paciucci** [comment]
There is definitely a bug somewhere, the control is there. 
What I am doing is the following:
- Worklist Screen->Click on Add Object Button-->displays a new form in place with an input field (whose selector is the one shown above and works perfectly-->click on save button which creates the business object-->returns to the worklist and in here I select the newly created object-->the object displays in a form, click on edit button which makes fields editable, try to modify the input field with the selector above and "the control could not be found".

This means that the first time the selector works perfect, the second time it does not, it's like it's not attached to the page DOM.
This looks like a bug to me.
What could I do?

**Comment by Siolto** [comment]
Hi @marco-paciucci,

thank you for the additional context. This sounds more or less the same as this [issue](https://github.com/ui5-community/wdi5/issues/346). Try to use `forceSelect` in your selector to tell wdi5 to retrieve the control again from the browser scope.

Regards,
Simon

**Comment by marco-paciucci** [comment]
Hello,
I coded this:
 

`	await browser.asControl({
			forceSelect: true,
			selector: {
				id: "application-IBPBPOV2-Manage-component---risk--RiskOpp",
			
				interaction: {
						idSuffix: "inner"
				}
		}}).enterText(sNewText);`
but I am still getting this:
`] Can not call "enterText,_controlSelector,selector,interactWithControl,_browserInstance,executeAsync,options,beforeCommand,options,beforeCommand,apply", because control could not be found
[0-0] [wdi5] Can not call "enterText,_controlSelector,selector,interactWithControl,_browserInstance,executeAsync,options,beforeCommand,options,beforeCommand,apply,executeAsyncScript,options,beforeCommand,options,beforeCommand,apply", because control could not be found`


I then coded this:
`		await browser.execute((a) => {
			sap.ui.getCore().byId("application-IBPBPOV2-Manage-component---risk--RiskOpp").setValue(a);
		}, sNewText);`

and this works but I don't like this dirty solution.
What am I doing wrong in the first solution?
