### ISSUE TITLE
Cannot read data from sap.m.Table

### ISSUE THREAD

**Issue by mocsa** [ui5-community/wdi5#349]
**Describe the bug**
During my test I sort a sap.m.Table. I want to assert that the data displayed is indeed sorted ascending. I try to read the data from row 1 and compare it to data from row 2.
After sorting the table I read the first row:
```js
firstrow = await mytable.getItems(0)
```
Then I obtain the context of that row:
```js
rowcontext = await firstrow.getBindingContext('myModel')
```
Then I try to get part of the model bound to this row, so that I can read data from it:
```js
myobject = await rowcontext.getObject()
```
Here I get the error:
```shell
rowcontext.getObject is not a function
```

**To Reproduce**
Use a sap.m.Table in your app, bound to a model, and try the above code to read data from it.

**Expected behavior**
I expect rowcontext.getObject() to return part of the model (in my case, JSON model) which is bound to the first table row. In the browser the above code works.

If the above is not the correct way to read data from a sap.m.Table in a wdi5 test then please describe the correct way.

**Runtime Env:**
- `wdi5/wdio-ui5-service`-version: 0.9.12
- `UI5` version: 1.96.0
- `wdio`-version: 7.24.0
- `node`-version: v14.18.1
- OS: Windows 10
- Browser + Version chrome 101.0.5150.0

**Additional context**
Test is run manually with `npm run wdi5` from VSCode JS debug terminal.

**Comment by vobu** [comment]
yeah, calling methods on a UI5 plain object currently break, see #234 #269.
in your case, `rowcontext` is not a control anymore and the `wdi5` api breaks.
but we (aka @dominikfeininger) are on it :)

**Comment by mocsa** [comment]
Still waiting for #269 to complete.

**Comment by dominikfeininger** [comment]
https://github.com/ui5-community/wdi5/pull/366

**Comment by dominikfeininger** [comment]
@mocsa can you please check if https://github.com/ui5-community/wdi5/releases/tag/v1.0.0-pre.1 solves your issue

**Comment by mocsa** [comment]
I tried to run my test. It finds the table control, it can retrieve the first item but now it fails at the getBindingContext step.  The error I get is:

`[wdi5] call of getBindingContext failed because of: Error: waitAsync is already running and cannot be called again at this moment`

**Comment by mocsa** [comment]
I forgot to mention that before I get the getBindingContext error the test hangs for about 10 seconds at the getBindingContext step.

Also, I didn't mention in my original post that the way I obtain the reference to the table is the following. Maybe it matters:

```js
const mytable = await browser.asControl({
    selector: {
        id: "idMyTable",
        viewName: "com.test.view.Myview",
        interaction: 'root'
        }
    })
```

**Comment by dominikfeininger** [comment]
Hi @mocsa, can you please provide a full working example.

You can find my working (green) test in this branch: https://github.com/ui5-community/wdi5/tree/fix/349

added this test in `aggregation.test.js`

```javascript    
it.only("check the getBinding of a table", async () => {
        const mytable = await Other.getList()
        const firstrow = await mytable.getItems(0)
        const rowcontext = await firstrow.getBindingContext()
        const myobject = await rowcontext.getObject()
        expect(myobject.FirstName).toEqual("Nancy")
    })```

**Comment by mocsa** [comment]
I'm not allowed to upload the app I'm testing and it would take a lot of effort to find and strip it down to the part where the test fails.

I thought about the opposite: to make your test fail. But I'd need your help on how I can run your (currently green) test locally on my computer. I don't know GitHub Actions enough to decipher how you execute your tests.

I downloaded the branch you mentioned and I see that Other.view.xml contains a simple sap.m.List with a sap.m.StandardListItem. If I were able to run your tests, my first idea to (hopefully) make it fail would be to replace this with sap.m.Table with a sap.m.ColumnListItem, because that is what I'm using.

Another difference in my test is that I don't have a default (nameless) Model, therefore I cannot use getBindingContext() without a model name. I must specify it. I'm not sure if this can cause any problems.

**Comment by mocsa** [comment]
I did some further debugging and noticed that when my test executes this step:

```js
rowcontext = await firstrow.getBindingContext('myModel')
```

I get the following error in the browser console:

```
Uncaught TypeError: crypto.randomUUID is not a function        VM1100:39
    at Object.window.wdi5.saveObject (eval at executeAsyncScript (index.html:552:26), <anonymous>:39:37)
    at eval (eval at executeAsyncScript (index.html:552:26), <anonymous>:55:58)
    at eval (eval at executeAsyncScript (index.html:552:26), <anonymous>:61:29)
    at a (_autoWaiterAsync-dbg.js:72:5)
    at _autoWaiterAsync-dbg.js:58:7
    at t (_timeoutWaiter-dbg.js:120:6)
```

I think it is coming from the code you added in 2bca472c792c7. If you need any more info about this, please send me instructions how can I obtain it.

Also, when my test executes this step:

```js
firstrow = await mytable.getItems(0)
```

I get the following debug message in the browser console:

```
2023-01-29 12:00:52.629899 Found a DOM reference for the control 'Element
sap.m.ColumnListItem#__item28-container-myapp---mytable--idProductsTable-2'.
Executing 'sap.ui.test.actions.Press' on the DOM element with ID '__item28-container
-myapp---mytable--idProductsTable-2' -  sap.ui.test.actions.Press
```

Why is it executing sap.ui.test.actions.Press? I did not instruct wdi5 to do that.
