### ISSUE TITLE
Inner Analytic table in Smart Table couldn't be located

### ISSUE THREAD

**Issue by ZhanJohnny** [ui5-community/wdi5#350]
**Describe the bug**
I had a analytic table in smart table, and try to locate this analytic table by smart table id. it always return the column instead of analytic table

**To Reproduce**
XML view as below:
![image](https://user-images.githubusercontent.com/50702068/192479663-08c4e1ba-3d5b-429a-a0f5-11ce27736cff.png)

UI5 inspector structure:
![image](https://user-images.githubusercontent.com/50702068/192479794-d9adb34a-773b-4064-955e-7f7f134749e0.png)

WDI5 code & ascontrol result:
![image](https://user-images.githubusercontent.com/50702068/192480180-50432d90-f2cc-4ff2-83a5-2ced8f91d094.png)
![image](https://user-images.githubusercontent.com/50702068/192479426-55bc048a-bde4-4628-9c86-c7fcaffd556a.png)

**Expected behavior**
The analytic table should be located with ancestor ID 

**Logs/Console Output**
if applicable, please copypasta _code-fenced_ log output, e.g.

```shell
$> ...
```

**Screenshots**
if applicable, add screenshots to help explain your problem.

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: [^0.9.10]
- `UI5` version: [e.g. 1.98.0]
- `wdio`-version (output of `wdio --version`): [e.g. 7.16.12]
- `node`-version (output of `node --version`): [e.g. v17.3.0]
- OS: [e.g. Linux openSuSE]
- Browser + Version [e.g. chrome 105.0.5195.127]

**Additional context**
Add any other context about the problem here,
e.g. any options the target browser is started with like `--headless` or
if the tests run in a CI environment

**Comment by vobu** [comment]
just out of curiosity, can you try adding `interaction: "root"` to the selector?
https://ui5-community.github.io/wdi5/#/recipes?id=using-interaction-on-a-selector

**Comment by ZhanJohnny** [comment]
> just out of curiosity, can you try adding `interaction: "root"` to the selector? https://ui5-community.github.io/wdi5/#/recipes?id=using-interaction-on-a-selector

Hi Vobu,
   Thanks, Adding interaction:root is working .
