### ISSUE TITLE
Native methods of UI5 aggregation filterGroupItems cannot be invoked for sap.ui.comp.filterbar.FilterBar

### ISSUE THREAD

**Issue by borceacristiann** [ui5-community/wdi5#353]
**Describe the bug**
Similar to something what is described in this [issue](https://github.com/ui5-community/wdi5/issues/181), none of the filterGroupItems methods can be used.

FilterBar has an aggregation called filterGroupItems of type sap.ui.comp.filterbar.FilterGroupItem.
Each FilterGroupItem has a property called label.

The below is my code. I'm just invoking the getLabel method
```
const filterBar = await browser.asControl({
            selector: {
                id: /.*id$/,
                controlType: "sap.ui.comp.filterbar.FilterBar",
                interaction: "root"
            },
            forceSelect: true
        })

const fiterGroupItems = await filterBar.getFilterGroupItems();

const firstLabel = await fiterGroupItems[0].getLabel();

expect(fisrtLabel).toBeTruthy()
```

This doesn't work, because the native UI5 methods of FilterGroupItem don't seem to be available on each of the items in aggregation. This leads to a type error about missing function

**To Reproduce**
Invoke getLabel on items of filterGroupItems aggregation of FilterBar

**Expected behavior**
The label of the filter item

**Logs/Console Output**
getLabel is not a function

**Screenshots**

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 0.9.13
- `UI5` version: 1.96.0
- `wdio`-version: 7.25.0 
- `node`-version: 14.17.3
- OS: macOS Monterey 12.6
- Browser + Version: Chrome 106.0.0

**Comment by borceacristiann** [comment]
Hello, do you have any news related to this issue?

**Comment by dominikfeininger** [comment]
Hi @borceacristiann, sry for late response.

I am litte confused. Your selector indicates you try to select an `sap.ui.table.Table`.

Can you please double check the length of the result array of `await filterBar.getFilterGroupItems()` so we are sure the elements are retuned in the first place.

Can you please try the shorthand https://ui5-community.github.io/wdi5/#/usage?id=getshorthand-conveniences 
`await filterBar.getFilterGroupItems(0)`

Thank you

**Comment by borceacristiann** [comment]
Hi, sorry for the wrong selector, I have updated the description with the correct code.

The answers to your questions:

**1) Can you please double check the length of the result array of await filterBar.getFilterGroupItems() so we are sure the elements are retuned in the first place.**

The length of the array is equal to 6.

![image](https://user-images.githubusercontent.com/40524367/201382229-72293d6d-b755-43ce-bfeb-11bf6a9d4818.png)

2) **Can you please try the shorthand https://ui5-community.github.io/wdi5/#/usage?id=getshorthand-conveniences
await filterBar.getFilterGroupItems(0)**

Even so, native UI5 methods are missing.

![image](https://user-images.githubusercontent.com/40524367/201384708-8a396e7e-4651-498f-84c7-8046ff7cc962.png)

**Comment by borceacristiann** [comment]
Hello colleagues, please reopen this issue because the problem still persists.

**Comment by vobu** [comment]
re-opening this, but the issue seems clearer thanks to @dominikfeininger's investigation in https://github.com/ui5-community/wdi5/issues/353#issuecomment-1330921123: there's an issue with the UI5 control implementation not always having true DOM counterparts.
