### ISSUE TITLE
Native methods of UI5 aggregation items cannot be invoked for sap.m.MultiComboBox

### ISSUE THREAD

**Issue by borceacristiann** [ui5-community/wdi5#354]
**Describe the bug**
Similar to something what is described in this [issue](https://github.com/ui5-community/wdi5/issues/181), none of the items methods can be used.

MultiComboBox has an aggregation called items of type sap.ui.core.Item.
Each Items has a property called text.

The below is my code. I'm just invoking the getText method
```
const multicomboBox =  await browser.asControl({
            selector: {
                id: /.*id$/,
                controlType: "sap.m.MultiComboBox",
                interaction: "root"
            },
            forceSelect: true
        })
await multiComboBox.open();

const items = await multiComboBox.getItems();

const firstItemText = await items[0].getText()

expect(firstItemText).toBeTruthy()
```

This doesn't work, because the native UI5 methods of sap.ui.core.Item don't seem to be available on each of the items in aggregation. This leads to a type error about missing function

**To Reproduce**
Invoke getText on items of items aggregation of multiComboBox

**Expected behavior**
The text of the item

**Logs/Console Output**
getText is not a function

**Screenshots**

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 0.9.13
- `UI5` version: 1.96.0
- `wdio`-version: 7.25.0 
- `node`-version: 14.17.3
- OS: macOS Monterey 12.6
- Browser + Version: Chrome 106.0.0

**Comment by dominikfeininger** [comment]
Added a test in PR.

Also note the rendered Item is type `sap.m.StandardListItem` -> `getText()` needs to be `getTitle()`. This is a UI5 flaw and will be documented in the wdi5 documentation.

**Comment by borceacristiann** [comment]
Hi @dominikfeininger, thanks for pointing me to the correct method. (_**getTitle**_)

However, the problem persists because no UI5 method is generated for the combobox items. I have attached some screenshots that I took while debugging, please take a look.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/40524367/198287241-a065707c-b5d2-4369-912b-e75d77236ea8.png">

![Screenshot 2022-10-27 at 15 35 54](https://user-images.githubusercontent.com/40524367/198286403-cbe08637-b4ae-4c31-8c0d-58750ff2d7ab.png)

![image](https://user-images.githubusercontent.com/40524367/198286619-a687e3cf-5eb5-41bc-87eb-645bb6be3e85.png)

**Comment by borceacristiann** [comment]
Hello colleagues, please reopen this issue because as I mentioned in the previous message the problem still persists.

**Comment by vobu** [comment]
happy to reopen this, but FTR: we included a test just for this bug and its fix:
https://github.com/ui5-community/wdi5/blob/c3293971d2deff46ef36103e0c72b975dfa1d217/examples/ui5-js-app/webapp/test/e2e/prop-array.test.js#L30
...where we're doing essentially the same thing as you: open a multi combo box and operate on an aggregation item.
maybe the referenced test can help you as a blueprint, specifically the `interaction: "root"` as part of the combox box selector?

**Comment by borceacristiann** [comment]
Hello, I tested once more and everything seems to work fine.
Thanks
