### ISSUE TITLE
WebdriverIO V8 enablement

### ISSUE THREAD

**Issue by dominikfeininger** [ui5-community/wdi5#384]
Thing to do to upgrade to WebdriverIO V8:
- drop support for Node 14
- update imports for types
![image](https://user-images.githubusercontent.com/4546829/206407481-25f94c2f-cebf-40be-9435-0799acadd2bc.png)

**Comment by vybiralpetr** [comment]
Hello, I would like to ask if there are any plans to support WDIO v8.

**Comment by vobu** [comment]
yes, there are, and it is in the top prio list → https://github.com/orgs/ui5-community/projects/2
currently, getting #447 is the priority. 
if you have some Node.js ESM experience, it‘d be great if you could give it a shot!

**Comment by vobu** [comment]
done in `2.0.0`! 🥳
