### ISSUE TITLE
Transition to the ui5 element breaks is incorrect using interaction idSuffix: treeicon

### ISSUE THREAD

**Issue by melissaxd96** [ui5-community/wdi5#394]
**Describe the bug**
Transition to the ui5 element breaks is incorrect using interaction idSuffix: treeicon

It is a tree table and I'm trying to access the expand icon, however looking at the _domId, it is not pointing to treeicon.

**Expected behavior**
It should point to the treetable's expand icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/73872266/210229237-a05dc403-a84c-4474-8799-2988ce5b345c.png)
![image](https://user-images.githubusercontent.com/73872266/210229260-70ac3fdf-c0d0-4615-8f1b-3835065f39b5.png)
![image](https://user-images.githubusercontent.com/73872266/210229271-2c744668-f682-4ea3-8a53-51df8f8c64c8.png)

**Runtime Env :**

- `wdi5/wdio-ui5-service`-version: v1.0.2
- `UI5` version: v2.14.1
- `wdio`-version (output of `wdio --version`): v7.27.0
- `node`-version (output of `node --version`): v18.12.1
- Browser + Version : Chrome Version 108.0.5359.125

Internal Function: getUI5CtlForWebObj

**Comment by dominikfeininger** [comment]
Hi @melissaxd96 the controlSelector does not have an `interaction` property. https://sapui5.hana.ondemand.com/sdk/#/api/sap.ui.test.RecordReplay.ControlSelector

Anyways, you already receive the row for your selector. 
You can expand the row using the `expand` method on the UI5 `row` control. https://sapui5.hana.ondemand.com/sdk/#/api/sap.ui.table.TreeTable%23methods/expand

```
const row = await browser.asControl(<your row selector>)
// expand
await row.expand()
```

**Comment by dominikfeininger** [comment]
maybe @hmanchev can say something about the issue with the `interaction` selector.

**Comment by hmanchev** [comment]
Hi all, 

I am not sure that this can be related as an issue to the interaction selector. However I will forward this to our experts and will provide feedback as soon as they have any opinion. 

Please note that it is still vacations period and you can expect some delays.

**Comment by kineticjs** [comment]
Hi @melissaxd96,

I checked that the selected icon (with idSuffix "treeicon") is only an element and **not a UI5 control**. 
(The table may not always create UI5 controls for its internal elements if it does not need to). 
The closest control containing the icon element is the parent row.

I tested the proposal of @dominikfeininger to use the table's **expand** method, so I can also confirm that it is a possible alternative solution, see e.g. https://jsbin.com/duwaxuqohe/edit?html,js,output

**Comment by hmanchev** [comment]
Did you manage to look at the answer from the OPA expert (kineticjs)?

**Comment by Siolto** [comment]
This issue has the same root cause as #355. For more explanation have a look at following [comment](https://github.com/ui5-community/wdi5/issues/355#issuecomment-1416063589).

**Comment by jdichev** [comment]
Hello @melissaxd96,

Which version of UI5 are you using? 

Thanks and best regards,
Jordan
