### ISSUE TITLE
oText.getText is not a function

### ISSUE THREAD

**Issue by VoskanGrigoryan** [ui5-community/wdi5#403]
Hello experts! I am currently writing a simple test in a ui5 application that should allow to check if there's a text component in a view and what string it displays. This is very similar to the https://github.com/ui5-community/wdi5/issues/319 issue however the only difference I can find between the two applications is that mine is a split app with two views being displayed at once.
![image](https://user-images.githubusercontent.com/71737745/212896396-89684b77-5b1f-4d28-b4db-d32b1490c68e.png)

This is the path referencing the view that has the Text component:
![image](https://user-images.githubusercontent.com/71737745/212896707-d7525356-f957-4950-b44f-24b5bc95fe3f.png)

This is the test:
![image](https://user-images.githubusercontent.com/71737745/212896838-2da0cbb3-e870-4942-a143-b6a4a40aedb0.png)

When I call the Text component I get undefined as a response, but if I replicate the test in a simple app with a single view it works fine.
![image](https://user-images.githubusercontent.com/71737745/212898212-28d6b1e5-73d2-4b23-9dd6-2777a16b4636.png)

![image](https://user-images.githubusercontent.com/71737745/212900264-9028dc9d-2d37-456e-ac08-e294ca7b8c32.png)

Thanks in advance for any help!

**Comment by Siolto** [comment]
Hi @VoskanGrigoryan,

In your screenshot of the `WDI5Control` we can see that `_initialisation` property is `false` which indicates, that the control was not found
![2023-01-17_13-39-32](https://user-images.githubusercontent.com/32054457/212901412-8e9b2e2e-b119-4697-911e-5daebcd1733d.png)

Is there some message in the terminal that indicates that a DOM element was not found? Maybe you can also double check with the help of the [TestRecorder](https://sapui5.hana.ondemand.com/#/topic/2535ef9272064cb6bd6b44e5402d531d) that your current selector is correct.

Regards,
Simon

**Comment by VoskanGrigoryan** [comment]
Hi Simon, thanks for reaching out.

You're right actually, I found in the terminal the following error:
![image](https://user-images.githubusercontent.com/71737745/212915649-d1fee9c6-787c-4ce8-bd0d-c256c243af17.png)

However I'm not sure where the problem is, maybe it's referencing that the path com.acc.cio.zerotouchbillingrequestor.view.Master or comacc.cio.zerotouchbillingrequestor.view.Mastersap.m.Text doesn't find anything? I'm not sure how to proceed from here

**Comment by VoskanGrigoryan** [comment]
Closing the issue so I can open a new one

**Comment by LukasHeimann** [comment]
Hi everyone,

we ran into the same problem. It seems like even though `control.isInitialized()` is `false` when the control is not found, even though `expect(table).toBePresent()` does not fail. In case the control is not found, `control.$()` also does not return a `WebdriverIO.Element`, but an empty object, it seems, so checking `control.$().isExisting()` results in a TypeError at runtime (but not at TypeScript compiletime.

I'll be digging a bit deeper here, but this feels like an oversight... Could wdi5 controls perhaps check for initialization when an unknown method is called? It feels a bit weird to have to safeguard this myself...

Kind regards
Lukas

**Comment by LukasHeimann** [comment]
This also seems to affect interaction, if I see this correctly. When the control is not found, `control.press()` passes, but no interaction happens.

**Comment by LukasHeimann** [comment]
Okay, that `expect(control).toBePresent()` doesn't work is really twisted. So this is the expectation: https://github.com/webdriverio/expect-webdriverio/blob/v3/src/matchers/element/toBeExisting.ts

Relevant snippet:
```ts
    const browser = await getBrowserObject(await received)
    return browser.call(async () => {
```

There is a helper function `getBrowserObject` that takes in the received object, the WDI5 control representation. What does this helper function? https://github.com/webdriverio/expect-webdriverio/blob/v3/src/utils.ts#L228-L231

```ts
async function getBrowserObject (elem: WebdriverIO.Element | WebdriverIO.ElementArray | WebdriverIO.Browser): Promise<WebdriverIO.Browser> {
    const elemObject = elem as WebdriverIO.Element
    return (elemObject as WebdriverIO.Element).parent ? getBrowserObject(await elemObject.parent) : elem as WebdriverIO.Browser
}
```

It treats the given object as wdio element, tries to traverse the `.parent` tree of it, and if there is no `.present`, it assumes the object to be the `browser`, which is returned and can be called.

In our case, this is still the WDI5 control, though, as it doesn't have a `.parent`. I'm not sure what it does exactly, but whatever is within the callback passed to `browser.call(...)` is not executed, and thus the actual expectation is never run and the expectation falsely passes. This is terrible! There is no safeguards or type safety to prevent this.

**Comment by LukasHeimann** [comment]
As for pressing a control, there _is_ error handling for it in the code: https://github.com/ui5-community/wdi5/blob/main/src/lib/wdi5-control.ts#L262

```ts
            // interact via wdio
            try {
                await ((await this._getWebElement()) as unknown as WebdriverIO.Element).click()
            } catch (error) {
                if (logging) {
                    Logger.error(`cannot call press(), because ${error.message}`)
                }
            }
```

It tries to retrieve the wdio element and click it. `_getWebElement` eventually throws: https://github.com/ui5-community/wdi5/blob/eb44619cf7251c8767bf34e7fe9d5aa076b66b00/src/lib/wdi5-control.ts#L371

This triggers the catch, which only logs (but does not fail the tests). This is very unfortunate -- there are test cases that only have navigation and thus pass, so a developer will assume the navigation happened correctly and will search the issue in later test cases -- where there is none. I know, there is logging that informs about the error, but still the test passes, which (to me) is rather unexpected.

**Comment by LukasHeimann** [comment]
Trying to summarize my suggestions:

1. make `expect(control).toBePresent()` fail the test with a specific error message, disable it in via typescript types or at least discourage it's usage in the documentation, pointing towards `expect(control.isInitialized()).toBeTruthy()` -- `isInitialized()` is not in the docs at all, and it seems really crucial!
2. make wdi5-native methods fail the test when the control is not found instead of just logging (this is not just `press`, but also `enterText` etc.
3. Make sure that `.$()` always behaves according to the types and not be `{}` at runtime (https://github.com/ui5-community/wdi5/blob/main/src/lib/wdi5-control.ts#L33) -- having it return `null` in case the element is not found (and that null being part of the interface) would be vastly better then the current implementation
4. Be more helpful when running the generated proxy methods. This is probably really hard (but could be achieved via a JS Proxy), but you could check if an unknown method is called at runtime and the control is not initialized, fail the test because the control is not there.
5. Instead of all of the above, fail the test if the control was not found. I'm not sure if this is idiomatic to wdio (and that may be the problem with my other suggestions above as well), but it would immediately solve all the problems (and from the issues, it seems there's people running into this regularly)

Thank you for having a look at this!

**Comment by Siolto** [comment]
Hi @LukasHeimann,

first of all thanks a lot for analyzing this issue to it's roots! I think we can all agree that the current state is not sufficient enough. Your suggestions (1-4) sound all very reasonable and should be considered.

> Instead of all of the above, fail the test if the control was not found. I'm not sure if this is idiomatic to wdio (and that may be the problem with my other suggestions above as well), but it would immediately solve all the problems (and from the issues, it seems there's people running into this regularly)

This one I would not put into consideration as we also have use cases where we want to check, that a control is not visible/not found. With that approach all these "negative" test cases would fail.

The core [contributors](https://github.com/ui5-community/wdi5/graphs/contributors) currently have a lot on their plate, would you mind if you could do the first steps in the right direction and create a PR?

Thanks in advance!
