### ISSUE TITLE
Access nested views inside UI5 app

### ISSUE THREAD

**Issue by VoskanGrigoryan** [ui5-community/wdi5#406]
Hi, I'm currently facing an issue with a UI5 application where I have two views, Master & Details nested inside an App view. The views are encased inside an flexible column layout and are being injected from the manifest.json file

![image](https://user-images.githubusercontent.com/71737745/213772065-09d98168-6b6c-4c76-95c1-3d51886d8cd2.png)
![image](https://user-images.githubusercontent.com/71737745/213772871-0a35fc96-1e13-489a-af00-e44499d16ddc.png)

This is the test file, I'm running a simple test to see if it can find a Text, which I know works if I put the Text component inside the App.view.xml file but not inside the Master.view.xml file.

![image](https://user-images.githubusercontent.com/71737745/213773184-ba8159d8-41cd-4b0e-82c8-540c7388f1c3.png)

This is the error in the terminal once the test runs,  the path "com.acc.cio.zerotouchbillingrequestor.view.Master" doesn't seem to reach the view.
![image](https://user-images.githubusercontent.com/71737745/213774033-4dd15698-ee4e-4bdb-80b5-b2a97c3445ee.png)

Any help would be appreciated since we've been stuck with the error for some time. Thanks!

**Comment by vobu** [comment]
i would trust the error msg and assume that your selector is wrong. it should probably be
`viewName:
"com.acc.cio.zerotouchbillingrequestor.view.Master" `
also, no `interaction:“root“` on a `sap.m.Text` - the `interaction` property is usually only valid in composite controls or those composed with aggregations
