### ISSUE TITLE
Feature Request: Is it possible to support Selenium Java in Future ?

### ISSUE THREAD

**Issue by PavanMudigondaTR** [ui5-community/wdi5#413]
Hi All,

Could you please let us know if SAP UI5 Fiori test automation will be supported in Selenium Java. Teams in our organization wanted to use Selenium Java only but I am not seeing SAP Page Object Model Automation support for Selenium Java. 

Also if possible, could you also please  let us know how hard it would be write our own page object model  in Selenium Java for SAP UI5 Fiori Automation. I am trying to find out this info to assist our teams who are favouring to use Selenium Java for their test automation !

**Comment by vobu** [comment]
hi - this is Node.js-land we're working in. No Java :)
However, you can hook up `wdio` and thus `wdi5` to a Selenium cluster and run `wdi5` tests there: look at the `hostname`, `port` and `path` config options (https://webdriver.io/docs/configurationfile) to provide cluster config info.
