### ISSUE TITLE
Cannot read data from sap.m.Table

### ISSUE THREAD

**Issue by mocsa** [ui5-community/wdi5#416]
This is a continuation of #349 which was auto-closed.

I did some further debugging and noticed that when my test executes this step:

```js
rowcontext = await firstrow.getBindingContext('myModel')
```

I get the following error in the browser console:

```
Uncaught TypeError: crypto.randomUUID is not a function        VM1100:39
    at Object.window.wdi5.saveObject (eval at executeAsyncScript (index.html:552:26), <anonymous>:39:37)
    at eval (eval at executeAsyncScript (index.html:552:26), <anonymous>:55:58)
    at eval (eval at executeAsyncScript (index.html:552:26), <anonymous>:61:29)
    at a (_autoWaiterAsync-dbg.js:72:5)
    at _autoWaiterAsync-dbg.js:58:7
    at t (_timeoutWaiter-dbg.js:120:6)
```

I think it is coming from the code you added in 2bca472c792c7. If you need any more info about this, please send me instructions how can I obtain it.

Also, when my test executes this step:

```js
firstrow = await mytable.getItems(0)
```

I get the following debug message in the browser console:

```
2023-01-29 12:00:52.629899 Found a DOM reference for the control 'Element
sap.m.ColumnListItem#__item28-container-myapp---mytable--idProductsTable-2'.
Executing 'sap.ui.test.actions.Press' on the DOM element with ID '__item28-container
-myapp---mytable--idProductsTable-2' -  sap.ui.test.actions.Press
```

Why is it executing sap.ui.test.actions.Press? I did not instruct wdi5 to do that.

**Comment by vobu** [comment]
Hi, thanks for the detailed debugging and context 👍 
we‘ll look at the missing dependency for `crypto` asap.
will report back here in this issue

**Comment by vobu** [comment]
just had a look at the browser support for `crypto.randomUUID()` https://caniuse.com/?search=randomuuid
anf it is supported across all the major ones.
what‘s your runtime env here, meaning: what browser, OS and protocol (webdriver or devtools) are you executing your tests with?

**Comment by mocsa** [comment]
I think I've found the root cause. In short, the remark [at the top of this page](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) says that randomUUID() works "only in secure contexts", that is, when the webpage is served by HTTPS. The test in a575bd50c91436916944 probably works only because localhost is also regarded as a secure context, and during testing the test app is served at http://localhost:8888/.

My test did not work, because my app was served at http://192.168.0.20/ via a local Apache installation. Apparently, this was not regarded as a "secure context". After changing my settings to serve my app at localhost, getBindingContext() and then getObject() worked flawlessly.

I think, this would worth putting into the documentation in some form.

Long story:

I've found the root cause because I noticed a very strange behavior when I stopped my test before the getBindingContext() step. When I entered `crypto.` in the browser console, the autocompletion showed the following available methods:
<img width="158" alt="image" src="https://user-images.githubusercontent.com/13969648/215434933-6786af69-4ecf-4f3a-8c6e-5433275086a5.png">

However, when I started the browser normally (not as part of a test), and opened a secure website with HTTPS, the autocompletion contained randomUUID():
<img width="176" alt="image" src="https://user-images.githubusercontent.com/13969648/215435123-3c71ecfd-12fc-424a-8fcf-38cb5d671276.png">

**Comment by mocsa** [comment]
Alternatively, you can replace the randomUUID() call with something else to remove the "secure context" restriction.

**Comment by vobu** [comment]
> Alternatively, you can replace the randomUUID() call with something else to remove the "secure context" restriction.

or this would of course also work.
a quick test on a `http`-only domain showed that
```js
const UUIDGeneratorBrowser = () =>
  ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, c =>
    (c ^ (crypto.getRandomValues(new Uint8Array(1))[0] & (15 >> (c / 4)))).toString(16)
  );
console.log(UUIDGeneratorBrowser());
``` 
from https://www.w3resource.com/javascript-exercises/fundamental/javascript-fundamental-exercise-253.php
worked well.
as an alternative to my above suggestion for a docs-PR, this could also go in as an alternative to the `crypto.randomUUID()` call via a code-PR... *hint hint, nudge nudge* 😄

**Comment by mocsa** [comment]
Created a PR. Feel free to modify it, if necessary.

By the way, is there any reason the new test in branch [fix/349](https://github.com/ui5-community/wdi5/blob/fix/349/examples/ui5-js-app/webapp/test/e2e/aggregation.test.js#L14-L21) related to this issue is not merged to main, yet?

**Comment by vobu** [comment]
> Created a PR. Feel free to modify it, if necessary.

thanks a lot, great!

> By the way, is there any reason the new test in branch [fix/349](https://github.com/ui5-community/wdi5/blob/fix/349/examples/ui5-js-app/webapp/test/e2e/aggregation.test.js#L14-L21) related to this issue is not merged to main, yet?

there was/is no PR for that yet.
would you mind adding that test to your PR #419? then we'd get in all the goodies at once :)

**Comment by mocsa** [comment]
I've added the test to the PR.
