### ISSUE TITLE
async controller functions are not resolved

### ISSUE THREAD

**Issue by freakadunse** [ui5-community/wdi5#417]
**Describe the bug**
Asynchronous functions in UI5 Controller are callable, but the promise will not be fulfilled.
The await of the promise results in a timeout.

**To Reproduce**
Create a UI5 application with only one view and create the following method in the controller:
```TypeScript
    public async getBusinessPartners() {
        return this.query({ entitySet: '/BusinessPartnerSet' });
    }
```
Create a WDI5 Test suite with the following test:
This would result either in errors or unresolved promises or timeout.
```TypeScript
        const selector = {
            selector: {
                controlType: "sap.ui.core.mvc.XMLView",
            }
        }
        const view = await (browser as any).asControl(selector);
        const controller = await view.getController();
        const businessPartners = await controller.getBusinessPartners();
```
Using sync controller functions will return the correct value.

**Expected behavior**
The Promise of the controller function would be resolved.

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 1.1.0
- `UI5` version: 1.109.0
- `wdio`-version (output of `wdio --version`): 7.30.0
- `node`-version (output of `node --version`): v16.13.2
- OS: Windows 
- Browser + Version: chrome 109.0

**Comment by vobu** [comment]
hi, as we're in Node.js land with `wdi5,` `await`ing regular Promises should be no issue. Could you please elaborate on what `this.query()` does? Maybe a network issue/auth issue? Also, a minimal reproducible sample would work wonders here 😄

**Comment by dominikfeininger** [comment]
Maybe this line causes indeed the issue: https://github.com/ui5-community/wdi5/blob/eb44619cf7251c8767bf34e7fe9d5aa076b66b00/client-side-js/executeObjectMethod.js#L12 further investigation is needed.

**Comment by freakadunse** [comment]
@vobu 
`this.query()` is an async function that promisifies the read/query operation of a odata call. 
so `ODatamodel.read('/EntitySet')` for example.

But that doesn't really matter, as async functions in general might be an issue at least with me :D

Little example controller:
```TypeScript
export default class App extends BaseController {
    public async onInit(): Promise<void> {
        console.log("App controller onInit");
    }

    public getSyncNumber(): number{
        return 10;
    }

    public async getAsyncNumber(): Promise<number> {
        return new Promise((resolve,reject) => {
            resolve(10);
        })
    }

    public async getBusinessPartners() {
        return this.query({ entitySet: '/BusinessPartnerSet' });
    }
}
```

and the corresponding test case:
```TypeScript
describe("binding", () => {
    it("Odata create", async () => {
        const selector = {
            selector: {
                controlType: "sap.ui.core.mvc.XMLView",
            }
        }
        const view = await (browser as any).asControl(selector);
        const controller = await view.getController();

        console.log("sync number", await controller.getSyncNumber());

        const number = await controller.getAsyncNumber();
        console.log(number)
    })
})
```

This will result in the following messages/log:
```
[0-0] sync number 10
[0-0] WDI5Object {
[0-0]   _uuid: 'e5accab5-3ded-425f-895a-f6045584ecb3',
[0-0]   _aProtoFunctions: [
[0-0]     'then',
[0-0]     'catch',
[0-0]     'finally',
[0-0]     'hasOwnProperty',
[0-0]     'isPrototypeOf',
[0-0]     'propertyIsEnumerable',
[0-0]     'toString',
[0-0]     'valueOf',
[0-0]     'toLocaleString'
[0-0]   ],
[0-0]   _baseObject: {},
[0-0]   then: [Function: bound ],
[0-0]   catch: [Function: bound ],
[0-0]   finally: [Function: bound ],
[0-0]   hasOwnProperty: [Function: bound ],
[0-0]   isPrototypeOf: [Function: bound ],
[0-0]   propertyIsEnumerable: [Function: bound ],
[0-0]   toString: [Function: bound ],
[0-0]   valueOf: [Function: bound ],
[0-0]   toLocaleString: [Function: bound ]
[0-0] }
```

if i await for this promise like `const number = await( await controller.getAsyncNumber() );` it will end in a timeout.

**Comment by freakadunse** [comment]
you are right @vobu, this is closer to unit testing. But what i test is a controller i extend for all view controllers which gives me methods for application handling like async query and reads, that i need with detail-view data collection on route navigations.
So this is a huge part in my application and would be used in e2e application tests also :slightly_smiling_face:

but anyways: thanks for taking a look into it and providing a new version in the near future :blush:
