### ISSUE TITLE
ERROR: connect ECONNRESET 127.0.0.1:9515

### ISSUE THREAD

**Issue by CosminPascal** [ui5-community/wdi5#418]
**Describe the bug**
When I try to run a test I keep getting the same error(connect ECONNRESET 127.0.0.1:9515). I don't know what is causing it because this is only happening to me. I tested this with one of my colleagues and for him, it's working as expected and we have the same environment.

**To Reproduce**
I didn't find a way to reproduce it.

**Expected behavior**
The test should run without getting this error. 

**Logs/Console Output**
[chrome 109.0.5414.119 mac os x #0-0] **connect ECONNRESET 127.0.0.1:9515**
[chrome 109.0.5414.119 mac os x #0-0] RequestError: connect ECONNRESET 127.0.0.1:9515
[chrome 109.0.5414.119 mac os x #0-0]     at ClientRequest.<anonymous> (/Users/I516540/Projects/ETD/Testing/etd-cloud-wdio-e2e-tests/node_modules/got/dist/source/core/index.js:970:111)
[chrome 109.0.5414.119 mac os x #0-0]     at Object.onceWrapper (events.js:483:26)
[chrome 109.0.5414.119 mac os x #0-0]     at ClientRequest.emit (events.js:388:22)
[chrome 109.0.5414.119 mac os x #0-0]     at ClientRequest.emit (domain.js:470:12)
[chrome 109.0.5414.119 mac os x #0-0]     at ClientRequest.origin.emit (/Users/I516540/Projects/ETD/Testing/etd-cloud-wdio-e2e-tests/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
[chrome 109.0.5414.119 mac os x #0-0]     at Socket.socketErrorListener (_http_client.js:475:9)
[chrome 109.0.5414.119 mac os x #0-0]     at Socket.emit (events.js:376:20)
[chrome 109.0.5414.119 mac os x #0-0]     at Socket.emit (domain.js:470:12)
[chrome 109.0.5414.119 mac os x #0-0]     at emitErrorNT (internal/streams/destroy.js:106:8)
[chrome 109.0.5414.119 mac os x #0-0]     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
[chrome 109.0.5414.119 mac os x #0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

**Screenshots**
<img width="1228" alt="Screenshot 2023-02-02 at 11 09 42" src="https://user-images.githubusercontent.com/78705434/216280684-bf814552-6e8f-44e3-81a9-11228f7379a8.png">

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: [1.0.0]
- `UI5` version: [1.96.0]
- `wdio`-version: [7.24.0]
- `node`-version: [14.17.0]
- OS: [macOS Ventura 13.2]
- Browser + Version [Chrome 109.0.5414.119]

**Comment by vobu** [comment]
do you have `chromedriver` in your wdio.conf in the „services“ array?

**Comment by CosminPascal** [comment]
yes I have

**Comment by vobu** [comment]
your issue is somehow related to the chromedriver as this is the service running w/ default settings on `localhost:9515`.
however, if there's no reproducible minimal sample, it's kind of 🔮 for us to guesstimate...sorry :(
if you want to go through with this, please provide additional info in the form of said reproducible minimal sample; otherwise please close this issue.
btw: all [core contributors](https://github.com/ui5-community/wdi5/graphs/contributors) offer paid consulting services for `wdi5` 😄
