### ISSUE TITLE
How can I run the tests from a browser?

### ISSUE THREAD

**Issue by krisho007** [ui5-community/wdi5#425]
I want our functional resources to run the automated tests. They are not comfortable with CLI. 
Is there a way to run this without CLI? 
We also have AzureDevOps. May be I should create a ADO Pipeline? Any other strategies?

**Comment by vobu** [comment]
Are „functional resources“ actual people or some sort of CI deity :godmode: 🤣 ?
Anyway, @marcellourbani has already done a first version of a VS Code testrunner (that has yet tomreceive some love akak contributions from our side, but grmpf, time and such) https://github.com/marcellourbani/vscode-wdio 
there are many projects running wdi5 in CI, an inspiration could be our own pipelines at https://github.com/ui5-community/wdi5/blob/main/.github/workflows/wdi5-tests_ts-app.yml
we‘re publishing docker images for every version too. they could be a starting point as well: https://github.com/ui5-community/wdi5/pkgs/container/wdi5
having said this, an actual „wdi5 Github Action“ would be cool 😎…if this is up your sleeve, mind giving it a shot? 😸

**Comment by krisho007** [comment]
Thanks, 
Actually, when you use RAP/Fiori elements projects, there are very few UI5 changes that happen and it is mainly backend-heavy (ABAP, BOPF, CDS, Classes). These backend changes are not linked to git yet. I am looking for something like a "Selenium IDE" with more UI5 specific features.
Hope my requirements made sense.

**Comment by vobu** [comment]
then use Visual Studio Code, put in the UI5 extensions that you need, and you're good to go IMO.
from the `wdi5` perspective, you only need Node.js installed and the browser you want to run the tests in.
I'll close this issue for now.
