### ISSUE TITLE
Please support pnpm

### ISSUE THREAD

**Issue by OTTOxMarc** [ui5-community/wdi5#426]
We are using pnpm as a package manager. With pnpm the setup should be very similar.

Instead of `npm init wdi5@latest -- --ts` one has to execute `pnpm create wdi5@latest -- --ts`.

The config files are created but I am then getting the following error:

```bash
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
node:internal/errors:856
  const err = new Error(message);
              ^

Error: Command failed: npm i @wdio/cli@7 @wdio/local-runner@7 @wdio/mocha-framework@7 @wdio/spec-reporter@7 wdio-chromedriver-service@7 wdio-ui5-service chromedriver ts-node typescript --save-dev     
    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at C:\Users\me\AppData\Local\pnpm\store\v3\tmp\dlx-30028\node_modules\.pnpm\create-wdi5@0.3.0\node_modules\create-wdi5\dist\index.js:97:38
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\me\AppData\Local\pnpm\store\v3\tmp\dlx-30028\node_modules\.pnpm\create-wdi5@0.3.0\node_modules\create-wdi5\dist\index.js:5:58) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 36292,
  stdout: null,
  stderr: null
}
 ERROR  Command failed with exit code 1: C:\Users\me\AppData\Local\pnpm\store\v3\tmp\dlx-30028\node_modules\.bin\create-wdi5.CMD -- --ts
```

After that I had to manually install the devDependencies with 

```bash
pnpm i @wdio/cli@7 @wdio/local-runner@7 @wdio/mocha-framework@7 @wdio/spec-reporter@7 wdio-chromedriver-service@7 wdio-ui5-service chromedriver ts-node typescript --save-dev
```

**Comment by vobu** [comment]
this is for https://github.com/ui5-community/create-wdi5 rather than `wdi5` itself.
but my guess is that it would mean variable-izing the `npm` calls e.g. in https://github.com/ui5-community/create-wdi5/blob/82fffcb9f770ddeea7a40b374222a3ece4ff9f3c/src/index.ts#L74 in the sense of detecting the package manager used...would you mind giving this a shot with a Pull Request in `create-wdi5` repo 😸 ?

**Comment by OTTOxMarc** [comment]
Determining the used package manager seems like a tricky task, at least there are no google results, but I will give it a try.

**Comment by vobu** [comment]
probably this could help or at least be a starting point: https://www.npmjs.com/package/detect-package-manager

**Comment by OTTOxMarc** [comment]
I saw your comment too late. I found a different solution which checks a certain `env` var. Feel free to review my PR 😊

**Comment by vobu** [comment]
thanks for this enhancement! review done. closing this as we're continuing in https://github.com/ui5-community/create-wdi5/pull/6
