### ISSUE TITLE
waitForUI5Timeout has no effect on OPA time out in Test Library

### ISSUE THREAD

**Issue by nair-sumesh** [ui5-community/wdi5#438]
**Describe the bug**
When using Test Library via WDI5, the config.wdi5.waitForUI5Timeout dies not reflect the OPA timeout.
 
```json
  wdi5: {
    screenshotPath: path.join('wdio-ui5-service', 'test', 'report', 'screenshots'),
    logLevel: 'verbose', // error | verbose | silent
    platform: 'browser', // electron, browser, android, ios
    skipInjectUI5OnStart: true,
    deviceType: 'web',
    waitForUI5Timeout: 270000
  },
```

Steps:
```js
  await oFioriElementsFacade.execute((Given, When, Then) => {
    Given.onTheMainPage.onTable().iPressRow({ ID: 'TestID' });
    Then.onTheDetailPage.iSeeThisPage();
  });
```
**Expected behavior**
OPA timeout should be 270 seconds.

**Screenshots**
![image](https://user-images.githubusercontent.com/12034160/222012409-9abd296a-e309-4d22-aff5-b6868fd0b5b3.png)

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: `1.1.0`
- `UI5` version: `[1.111.0-SNAPSHOT]`
- `wdio`-version (output of `wdio --version`): `7.30.1`
- `node`-version (output of `node --version`): `19.2.0`
- OS:`macOS 13.2.1`
- Browser + Version : ` chrome (v109.0.5414.120)`

**Additional context**
This test was executed a very slow SAP system.

**Comment by vobu** [comment]
thanks for the detailed description and context 👍
could you as a first step please update to the latest wdi5 version?

**Comment by nair-sumesh** [comment]
Upgraded to 
``` json
 "name": "wdio-ui5-service",
  "version": "1.3.1"
```
Still same error.

**Comment by nair-sumesh** [comment]
Easy to replicate on any Test Library step. Just add below code to simulate a slow responding system.
```js
    // Use different download (25kb/s) and upload (50kb/s) throughput values for throttling with a latency of 1000ms
    browser.setNetworkConditions({
      latency: 1000,
      download_throughput: 25600,
      upload_throughput: 51200,
    });
```
