### ISSUE TITLE
Same UI5 control not identified via Test Library twice

### ISSUE THREAD

**Issue by nair-sumesh** [ui5-community/wdi5#439]
**Describe the bug**
When using Test Library via WDI5, accessing the same UI5 control returns error 
```cmd 
TypeError: Cannot read properties of undefined
```
 
**What I do (via WDI5 automation)  to encounter the issue:**
1. Login and open a OData V4 FE app.
2. On the Main page click on an item using Test Library
3. Logout and login again on the same browser.
4. Open the same app and click on the same item using Test Library

Test Steps:
```js
    await oFioriElementsFacade.execute((Given, When, Then) => {
      Given.onTheMainPage
        .iCollapseExpandPageHeader(true)
        .and.iCollapseExpandPageHeader();
      When.onTheMainPage
        .onFilterBar()
        .iChangeSearchField('someid' )
        .and.iExecuteSearch();
      Then.onTheMainPage.iSeeThisPage();
      When.onTheMainPage.onTable().iSelectRows({ ID:'someid' });
    });
  }
```
**Expected behavior**
The controls should be returned always.

**Screenshots**
![image](https://user-images.githubusercontent.com/12034160/222014200-2e507869-e4de-4dd8-a3f8-ca2132a7736a.png)

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: `1.1.0`
- `UI5` version: `[1.111.0-SNAPSHOT]`
- `wdio`-version (output of `wdio --version`): `7.30.1`
- `node`-version (output of `node --version`): `19.2.0`
- OS:`macOS 13.2.1`
- Browser + Version : ` chrome (v109.0.5414.120)`

**Additional context**
The UI5 controls are successfully returned on accessing multiple times when remained logged in the same session.
As soon as the test logoff from the SAP system and perform login again, the UI5 controls are returned as undefined.

**Comment by nair-sumesh** [comment]
BTW, in my test automation  the initialization of the FioriElementsFacade is not done in the `before` hook.      
Rather I do it on the run, when and where required.

**Comment by vobu** [comment]
thanks for the detailed description and context - again 😄👍
same request as in your other issue: could you as a first step please update to the latest wdi5 version?

**Comment by nair-sumesh** [comment]
Upgraded. 
Still reproducible like in other [issue](https://github.com/ui5-community/wdi5/issues/438#issuecomment-1450643771) 😀

**Comment by Siolto** [comment]
Hi @nair-sumesh,

could you maybe try to reinitialize the facade again after you log back in? I guess the testLibrary loses the context to the Fiori Elements application for some reason (maybe the generic IDs are not the same anymore).

Regards
Simon

**Comment by nair-sumesh** [comment]
Thanks @Siolto. Your suggestion worked.          
Since my test was executed in the same browser session ,  I assumed initialization at the beginning of the test  was enough.(inspired as per the before hook implementation in wdi5  test library documentation).
