### ISSUE TITLE
Browserstack iOS testing - Error converting element ID for using in WD atoms

### ISSUE THREAD

**Issue by benskov95** [ui5-community/wdi5#442]
Hello,

Sorry if this is the wrong place to post this, but it seems wdi5-related. If it is not, I would appreciate it if you could tell me where to ask instead.

I have been trying to run some wdi5 tests on Browserstack, and they work just fine across different browsers and operating systems, but I keep running into issues with iOS specifically. When I try to run wdi5 tests in iOS, I get the following error:

Error converting element ID for using in WD atoms: ':wdc:1678092332762'

It doesn't occur immediately (other controls are used before the error without any issues), so maybe there's some other underlying issue with the specific test it crashes on. It just doesn't make sense to me that it would work just fine in other browsers and operating systems if that were the case.

Has anyone else had this issue, or something similar? Any help is appreciated. Also, let me know if you need any additional information.

Thank you for reading.

**Comment by vobu** [comment]
Hi 🙋‍♂️ first of all, I think it‘s great that wdi5 is working well for you cross-browser and -OS!
if you‘d share more details on the test(s) that cause above output, then we‘d be more likely to get a grasp on things ⚙️

**Comment by benskov95** [comment]
Hello again,

Thank you for the reply. I have written the tests using the mocha framework and here's the test where the error occurs:

```
    it("should open the settings popover when the settings button is clicked", async () => {
        const settingsBtn = await Dashboard.getSettingsButton();

        await settingsBtn.press();

        const selectedLangBtn = await Dashboard.getSelectedLanguageButton();
        expect(await selectedLangBtn.getVisible()).toBeTruthy();
    })
        
```

The methods used on the Dashboard page object are using the browser object and the asControl method with selectors to retrieve the controls. The mentioned error seems to occur specifically when the getSelectedLanguageButton() method is called. Here's a screenshot of the error from Browserstack:

<img width="1000" alt="Screenshot 2023-03-06 at 14 21 44" src="https://user-images.githubusercontent.com/59828245/223121888-75ce5dd8-9cc6-47b0-af9b-a9c2bd5c2d09.png">

Just now as I'm writing this I noticed that there's a difference between the id of the control which causes the error and the others:

<img width="418" alt="Screenshot 2023-03-06 at 14 26 48" src="https://user-images.githubusercontent.com/59828245/223123059-b8922849-d2c5-447f-9619-3f094a0f24bf.png">

This is from a different control, and here you can see 'xml-view' is part of the id (presumably because the view name is specified in the selector for that control). I have not specified it in the selector for the other control since it's in a fragment and I didn't seem to need it while testing locally, but I will try to include it and report back.

**Comment by benskov95** [comment]
Hello,

I have now tried some different things out and I still get the same error when running the tests on iOS. In the tests I have been trying to run to fix the issue, the error first occurs when trying to use one of the getter methods on a button control (getVisible). 

The tests continue to run (and work correctly, despite the errors in the terminal) after this, though, but eventually fail completely when trying to use the getContent() method on a dialog control. I'm not sure where to go from here, so if anyone has any suggestions, please let me know. Also, if

**Comment by benskov95** [comment]
Tried now on some other testing platforms (Sauce Labs & LambdaTest), and the issue doesn't seem to occur there.
