### ISSUE TITLE
I can't find the element using browser.asControl function

### ISSUE THREAD

**Issue by MikhailDryk** [ui5-community/wdi5#449]
**Describe the bug**

While I was writing tests to the one of our application [Digital Twin](https://bigbuild-performance-copin.internal.cfapps.sap.hana.ondemand.com/cp.portal/site?sap-language=en#CollbtvProjectDigitalTwin-manage?sap-ui-app-id-hint=com.sap.copin.digitaltwin.ui&/DigitalTwins/fe070b5b-79e3-4d61-b7b5-5654bd52bf8c/a720d9e5-637c-422c-9eee-1eb35ef68f3f/f639a53a-f601-465c-9104-6d006f24dfa8/true)

I faced an issue, that I am not able to find control by launching [browser.as Control](https://ui5-community.github.io/wdi5/#/locators?id=locators) function. 

Just below, I will give a couple of examples of how I tried to find SAPUI5 control (I highlighted on the screenshot)
![image](https://user-images.githubusercontent.com/64844079/230319138-02eab75c-1b74-440d-a34a-950cd18196e3.png)
 using different selectors:
 
 1) I tried to find it by **ID** + **controlType** +  **viewName**
![image](https://user-images.githubusercontent.com/64844079/230322017-e8c1027b-dee9-442c-abf9-5b605da44567.png)
 2) I tried to find it by **controlType** +  **ancestor**
![image](https://user-images.githubusercontent.com/64844079/230322515-b05a4615-20ed-4dac-8bac-49b718356466.png)

I show you one of several UI5 elements which I don't find in application. 

**To Reproduce**

1. Go to the application by [link](https://bigbuild-performance-copin.internal.cfapps.sap.hana.ondemand.com/cp.portal/site?sap-language=en#CollbtvProjectDigitalTwin-manage?sap-ui-app-id-hint=com.sap.copin.digitaltwin.ui&/DigitalTwins/fe070b5b-79e3-4d61-b7b5-5654bd52bf8c/a720d9e5-637c-422c-9eee-1eb35ef68f3f/f639a53a-f601-465c-9104-6d006f24dfa8/true)
2. Please, get in touch with me (mikhail.dryk@sap.com) to get creditionals to the application, 
3. After logging in and clicking the link, you will see the same application shown in the screenshot.

**Expected behavior**
I wanted to be able to find UI5 controls using the **browser.asControl** function.

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: [^0.9.15]
- `UI5` version: [1.108.4]
- `wdio-cli`-version: [ 7.26.0]
- `node`-version (output of `node --version`): [18.14.0]
- OS: [Windows 10 Enterprise]
- Browser + Version [chrome 111.0.5563.111]

**Comment by Siolto** [comment]
Hi @MikhailDryk,

did you already tried to use the [Test Recorder](https://sapui5.hana.ondemand.com/sdk/#/topic/2535ef9272064cb6bd6b44e5402d531d.html) to identify the controls?

**Comment by MikhailDryk** [comment]
> Hi @MikhailDryk,
> 
> did you already tried to use the [Test Recorder](https://sapui5.hana.ondemand.com/sdk/#/topic/2535ef9272064cb6bd6b44e5402d531d.html) to identify the controls? There is a also a special dialect for `wdi5`.

Hello @Siolto 

I have tried to use selector was provided by Test Recorder, but It didn't help me

**Comment by vobu** [comment]
as a prerequisite before we start digging deeper, please also update `wdi5` to its' latest version - you're still running a pre^1 version, many improvements went in since then.

**Comment by MikhailDryk** [comment]
Hello @vobu 

I updated version of  [wdio-ui5-service](https://www.npmjs.com/package/wdio-ui5-service) to the 1.3.2
![image](https://user-images.githubusercontent.com/64844079/230381655-b7535cb5-8ff7-4a43-8ed3-2748ed6c6d84.png)

Without any success

**Comment by Siolto** [comment]
As discussed with @MikhailDryk: Most of his issues will be solved when #355 is resolved. Some other problems with identifying specific controls require more analysis.
