### ISSUE TITLE
Cannot integrate ui5 service with wdio

### ISSUE THREAD

**Issue by diya-dhan** [ui5-community/wdi5#453]
Hi,

I've been trying to use the ui5 service as : 
services: ['chromedriver', 'ui5']

But while running the tests I am running into the following error :
**Error: Failed to initilialise launcher service unknown: Error: Couldn't initialise "wdio-ui5-service".
Error: Cannot find module '/Users/I584814/Diya/bp-validation/cloud-extension-s4hana-business-process/app/BusinessPartners/node_modules/webdriverio/build/multiremote/index.js'**

Please do advice on how this could be resolved.

**Comment by dominikfeininger** [comment]
Hi @diya-dhan, can you please provide more information about your environment and used versions.

**Comment by diya-dhan** [comment]
Hey @dominikfeininger ,

So these are dependencies I am using. 
    "@sap/ui5-builder-webide-extension": "1.0.x",
    "@ui5/cli": "1.13.0",
    "@wdio/cli": "8.8.2",
    "@wdio/local-runner": "8.8.2",
    "@wdio/mocha-framework": "8.8.0",
    "@wdio/spec-reporter": "8.8.0",
    "chromedriver": "112.0.0",
    "ui5-task-zipper": "^0.3.1",
    "wdio-chromedriver-service": "8.1.1",
    "wdio-ui5-service": "1.3.2"

Additionally the node version is v18.14.0 and npm version is 9.6.2.

**Comment by vobu** [comment]
the culprit is wdio^8 - as of now, wdi5 is compatible with wdio^7 only. so please downgrade webdriverio to v7 and you should be good to go!
ps: we're currently working on the wdio^8 enablement!

**Comment by diya-dhan** [comment]
Hey @vobu ,

So I did downgrade the version like suggested. Here are the current package versions.
  "devDependencies": {
    "@sap/ui5-builder-webide-extension": "1.0.x",
    "@ui5/cli": "1.13.0",
    "@wdio/cli": "7.31.1",
    "@wdio/local-runner": "7.31.1",
    "@wdio/mocha-framework": "7.30.2",
    "@wdio/spec-reporter": "7.31.1",
    "chromedriver": "112.0.0",
    "ui5-task-zipper": "^0.3.1",
    "wdio-chromedriver-service": "8.1.1",
    "wdio-ui5-service": "1.3.2",
    "wdio-wait-for": "3.0.3"
  }

But I am still running into a similar error.
ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "wdio-ui5-service".
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './build/multiremote' is not defined by "exports" in /Users/I584814/Diya/bp-validation/cloud-extension-s4hana-business-process/app/BusinessPartners/node_modules/webdriverio/package.json

**Comment by vobu** [comment]
wdio-chromedriver-service is still at 8.x
you might also try removing node_modules entirely and doing npm i again

**Comment by diya-dhan** [comment]
ah yess. changed it now and all is fine. Thank you very much for your help!

**Comment by vobu** [comment]
excellent 👍👍👍
