### ISSUE TITLE
wdi5 authentication on multiremote in jenkins

### ISSUE THREAD

**Issue by sangeeta298** [ui5-community/wdi5#457]
Hi, I am using BTP + custom authentication and multiremote features of wdi5. The tests work fine locally. But when I try to execute the same on jenkins, I am facing issues. On few browser instances the login works fine and for others I get various issues (invalid session id / Invalid Version: null / invalid cookie domain). I am doing the same actions on all browser instances (only login with different username/password). And I execute the tests 3 times with different platforms and authentication. Below code is part of my before block and the tests fail here itself:

        await browserInstanceEnduser1.url(config.url);
        await browserInstanceEnduser2.url(config.url);
        await browserInstanceKeyuser.url(config.url);

        const trigger = {
            selector: {
                id: /vm-trigger/
            }
        };
        const buttonTrigger1 = await browserInstanceEnduser1.asControl(trigger);
        await browser.waitUntil(() => buttonTrigger1.$().isDisplayed());
        const buttonTrigger2 = await browserInstanceEnduser2.asControl(trigger);
        await browser.waitUntil(() => buttonTrigger2.$().isDisplayed());
        const buttonTrigger3 = await browserInstanceKeyuser.asControl(trigger);
        await browser.waitUntil(() => buttonTrigger3.$().isDisplayed());

Execution 1: Platform = Cloud foundry
Here I use BTP authentication and this execution sometimes works but breaks other times, e.g.:
18:00:19  [0-0] [34m[wdi5][0m creating internal control map
18:00:19  [0-0] [34m[wdi5][0m creating internal control map
18:00:19  [0-0] [34m[wdi5][0m creating internal control map
18:00:19  [0-0] [34m[wdi5][0m setup complete
18:00:23  [0-0] [32m[wdi5][0m successfully initialized wdio-ui5 bridge
18:00:35  [0-0] [32m[wdi5][0m successfully initialized wdio-ui5 bridge
18:00:50  [0-0] [32m[wdi5][0m successfully initialized wdio-ui5 bridge
18:00:50  [0-0] [34m[wdi5][0m creating internal control with id vm-trigger/
18:00:58  [0-0] [32m[wdi5][0m call of function _getControl() returned: "sap.ui.demoapps.rta.fiorielements::sap.suite.ui.generic.template.ListReport.view.ListReport::SEPMRA_C_PD_Product--template::PageVariant-vm-trigger"
18:00:58  [0-0] [34m[wdi5][0m _asControl() needed 7812.369561970234 for vm-trigger/
18:00:58  [0-0] [34m[wdi5][0m creating internal control with id vm-trigger/
18:00:58  [0-0] 2023-04-26T16:00:57.865Z ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id
18:00:58  [0-0] invalid session id in "Multi Remote."before all" hook for "click Avatar""
18:00:58  invalid session id: invalid session id
18:00:58      at processTicksAndRejections (node:internal/process/task_queues:96:5)
18:00:58      at async clientSide_getControl (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/wdio-ui5-service/client-side-js/getControl.js:3:12)
18:00:58  [0-0] 2023-04-26T16:00:57.956Z ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id
18:00:58  [0-0] invalid session id in "Multi Remote."after all" hook for "click Avatar""
18:00:58  invalid session id: invalid session id
18:00:58      at processTicksAndRejections (node:internal/process/task_queues:96:5)
18:00:58      at async Context.<anonymous> (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/test/variantManagement/variantManagement.test.js:273:9)
18:00:58  [0-0] FAILED in MultiRemote - /test/variantManagement/variantManagement.test.js

Execution 2: Platform = S/4 HANA OnPremise
Here I use custom authentication and I still see the app login screen in the screenshots. So, no authentication happens here. Logs:
17:44:06  [0-0] [34m[wdi5][0m creating internal control map
17:44:06  [0-0] [34m[wdi5][0m creating internal control map
17:44:06  [0-0] [34m[wdi5][0m creating internal control map
17:44:06  [0-0] [34m[wdi5][0m setup complete
17:44:07  [0-0] 2023-04-26T15:44:07.571Z ERROR @wdio/utils:shim: TypeError: Invalid Version: null
17:44:07  [0-0]     at new SemVer (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/semver/classes/semver.js:19:13)
17:44:07  [0-0]     at compare (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/semver/functions/compare.js:3:3)
17:44:07  [0-0]     at Object.lt (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/semver/functions/lt.js:2:29)
17:44:07  [0-0]     at checkUI5Version (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/wdio-ui5-service/dist/lib/wdi5-bridge.js:218:16)
17:44:07  [0-0]     at /home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/wdio-ui5-service/dist/lib/wdi5-bridge.js:240:42
17:44:07  [0-0]     at step (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/wdio-ui5-service/dist/lib/wdi5-bridge.js:56:23)
17:44:07  [0-0]     at Object.next (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/wdio-ui5-service/dist/lib/wdi5-bridge.js:37:53)
17:44:07  [0-0]     at fulfilled (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/wdio-ui5-service/dist/lib/wdi5-bridge.js:28:58)
17:44:07  [0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
17:44:07  [0-0] [34m[wdi5][0m creating internal control with id vm-trigger/
17:44:07  [0-0] 2023-04-26T15:44:07.618Z ERROR webdriver: Request failed with status 500 due to javascript error: javascript error: Cannot read properties of undefined (reading 'waitForUI5Options')
17:44:07  [0-0] JavaScript stack:
17:44:07  [0-0] TypeError: Cannot read properties of undefined (reading 'waitForUI5Options')
17:44:07  [0-0]     at eval (eval at executeAsyncScript (:553:26), <anonymous>:4:65)
17:44:07  [0-0]     at eval (eval at executeAsyncScript (:553:26), <anonymous>:33:8)
17:44:07  [0-0]     at eval (eval at executeAsyncScript (:553:26), <anonymous>:33:33)
17:44:07  [0-0]     at executeAsyncScript (<anonymous>:553:47)
17:44:07  [0-0]     at apply.selector.id (<anonymous>:568:29)
17:44:07  [0-0]     at callFunction (<anonymous>:447:22)
17:44:07  [0-0]     at <anonymous>:461:23
17:44:07  [0-0]     at <anonymous>:462:3
17:44:07  [0-0]   (Session info: headless chrome=112.0.5615.138)
17:44:07  [0-0] javascript error in "Multi Remote."before all" hook for "click Avatar""
17:44:07  javascript error: javascript error: Cannot read properties of undefined (reading 'waitForUI5Options')
17:44:07  JavaScript stack:
17:44:07  TypeError: Cannot read properties of undefined (reading 'waitForUI5Options')
17:44:07      at eval (eval at executeAsyncScript (:553:26), <anonymous>:4:65)
17:44:07      at eval (eval at executeAsyncScript (:553:26), <anonymous>:33:8)
17:44:07      at eval (eval at executeAsyncScript (:553:26), <anonymous>:33:33)
17:44:07      at executeAsyncScript (<anonymous>:553:47)
17:44:07      at apply.selector.id (<anonymous>:568:29)
17:44:07      at callFunction (<anonymous>:447:22)
17:44:07      at <anonymous>:461:23
17:44:07      at <anonymous>:462:3
17:44:07    (Session info: headless chrome=112.0.5615.138)
17:44:07      at processTicksAndRejections (node:internal/process/task_queues:96:5)
17:44:07      at async clientSide_getControl (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/wdio-ui5-service/client-side-js/getControl.js:3:12)
17:44:08  [0-0] FAILED in MultiRemote - /test/variantManagement/variantManagement.test.js

Execution 3: Platform = S/4 HANA OnCloud
Here also I use custom authentication and sometimes the login is successful, but other times I get error like below one:
17:44:11  [0-0] RUNNING in MultiRemote - /test/variantManagement/variantManagement.test.js
17:44:12  [0-0] [34m[wdi5][0m creating internal control map
17:44:12  [0-0] [34m[wdi5][0m creating internal control map
17:44:12  [0-0] [34m[wdi5][0m creating internal control map
17:44:12  [0-0] [34m[wdi5][0m setup complete
17:44:15  [0-0] [32m[wdi5][0m successfully initialized wdio-ui5 bridge
17:44:18  [0-0] [32m[wdi5][0m successfully initialized wdio-ui5 bridge
17:44:18  [0-0] 2023-04-26T15:44:18.613Z ERROR webdriver: Request failed with status 400 due to invalid cookie domain: invalid cookie domain
17:44:18  [0-0]   (Session info: headless chrome=112.0.5615.138)
17:44:18  [0-0] /home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/webdriver/build/utils.js:198
17:44:18  [0-0]     return new CustomRequestError(body, requestOptions);
17:44:18  [0-0]            ^
17:44:18  [0-0] 
17:44:18  [0-0] invalid cookie domain: invalid cookie domain
17:44:18  [0-0]   (Session info: headless chrome=112.0.5615.138)
17:44:18  [0-0]     at getErrorFromResponseBody (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/webdriver/build/utils.js:198:12)
17:44:18  [0-0]     at NodeJSRequest._request (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/webdriver/build/request/index.js:166:60)
17:44:18  [0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
17:44:18  [0-0]     at async Browser.wrapCommandFn (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/@wdio/utils/build/shim.js:137:29)
17:44:18  [0-0]     at async Browser.setCookies (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/webdriverio/build/commands/browser/setCookies.js:63:9)
17:44:18  [0-0]     at async Browser.wrapCommandFn (/home/jenkins/agent/workspace/Flex-e2e_flex-e2e_publicView/node_modules/@wdio/utils/build/shim.js:137:29)
17:44:18  [0-0] FAILED in MultiRemote - /test/variantManagement/variantManagement.test.js

Here are the dependencies from package.json:

    "@ui5/cli": "^3.0.4",
    "@wdio/cli": "^7",
    "@wdio/local-runner": "^7",
    "@wdio/mocha-framework": "^7",
    "@wdio/spec-reporter": "^7",
    "chromedriver": "latest",
    "wdio-chromedriver-service": "^7",
    "wdio-ui5-service": "*"

**Comment by vobu** [comment]
hi, if you observe different behavior between local and CI/pipeline execution, the root cause of flakiness is almost always slight differences in the environment. 
In your case: what `chrome` and what `node` version is run on Jenkins?

**Comment by dominikfeininger** [comment]
Might be a good idea to use docker?

**Comment by sangeeta298** [comment]
node version is: v18.16.0 and chrome version is 113.0.5672.126 in Jenkins and running on docker image: atlassianlabs/docker-node-jdk-chrome-firefox:latest
