### ISSUE TITLE
Unable to launch browser

### ISSUE THREAD

**Issue by diya-dhan** [ui5-community/wdi5#460]
Hi,

Whenever I try to run the command to execute my tests, I am running into the following error.

unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=112.0.5615.137)

Please do advice as to how this can be resolved.

Thank you

**Comment by vobu** [comment]
Hi Diya,
can you please provide more context, e.g. by using the Issue template we provide?
Only then can we not guesstimate 🔮, but actually help.
Thanks!
(ps: you're UI5 app under test is running before you execute the tests, right? Right?!? 😸)

**Comment by diya-dhan** [comment]
Hey Volker,

Yes I'll surely provide more context. Now the template that you are talking about, is it the one for the bug report?
Please let me know if I am required to follow some other template.

And yes my app does run 😂
It's just that my tests aren't getting executed.

Thank you!

**Comment by vobu** [comment]
> Yes I'll surely provide more context. Now the template that you are talking about, is it the one for the bug report? Please let me know if I am required to follow some other template.

just use the standard template that shows up when you do `issues` → `New issue` → (Bug Report) `Get started` in this repo:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/6573426/235854960-fc89ab8f-1613-43bf-afb2-e983294d7647.png">
