### ISSUE TITLE
Unable to launch browser

### ISSUE THREAD

**Issue by diya-dhan** [ui5-community/wdi5#462]
**Describe the bug**
I am trying to execute my tests with the command : wdio run wdio.conf.js which is in package.json as a wdio script
But I keep running into the error : unknown error: net::ERR_CONNECTION_REFUSED (Session info: chrome=112.0.5615.137)
And thus the app doesn't run on my browser as expected,

**To Reproduce**
Not exactly sure how the error could be reproduced because I can't really share the source code. Let me know if you would like to have a look at the wdio config file if needed.

**Expected behavior**
I expect the chrome browser to launch and execute my tests without any errors.

**Logs/Console Output**
[chrome 112.0.5615.137 mac os x #0-0] unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=112.0.5615.137)
[chrome 112.0.5615.137 mac os x #0-0] unknown error: unknown error: net::ERR_CONNECTION_REFUSED
[chrome 112.0.5615.137 mac os x #0-0]   (Session info: chrome=112.0.5615.137)
[chrome 112.0.5615.137 mac os x #0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[chrome 112.0.5615.137 mac os x #0-0]     at async Context.<anonymous> (/Users/I584814/Diya/bp-validation/cloud-extension-s4hana-business-process/app/BusinessPartners/webapp/wdi5-test/specs/firstPage.spec.js:3:9)

**Runtime Env 
- `wdi5/wdio-ui5-service`-version: 1.3.2
- `@ui5/cli` version: 1.13.0
- `@wdio/cli`-version : 7.31.1
- `node`-version : 18.4.0
- OS: MacOS Ventura
- Browser + Version : Chrome, Version : 112.0.5615.137

**Comment by vobu** [comment]
what port is your UI5 app running on?
and does that match `baseUrl` your `wdio.conf.js`?
and do you have any custom config in your `wdio.conf.js` for the chromedriver, specifically the port?
