### ISSUE TITLE
Question: Do your tests still work in headless mode with chromedriver 113

### ISSUE THREAD

**Issue by borceacristiann** [ui5-community/wdi5#470]
**Describe the bug**
After increasing the chromedriver version to 113, I can no longer run my tests in headless mode. In headful mode everything works fine as before. From the error logs it can be seen that the UI controls are no longer found and the Timeout error is thrown.

**To Reproduce**

1. increase the chromedriver version to 113
2. run the tests in headless mode

**Runtime Env (please complete the following information):**
- `wdi5/wdio-ui5-service`-version: 1.5.0
- `UI5` version: 1.96.0
- `wdio`-version: 7.31.1
- `node`-version: 16.16.0 & 18.14.0
- `OS`: macOS Ventura 13.3.1
- `Browser + Version`: Chrome 113.0.5672.92

**Comment by vobu** [comment]
i just tested this with [our example js app](https://github.com/ui5-community/wdi5/tree/main/examples/ui5-js-app) and it "works for me"™

my env:
- `wdi5/wdio-ui5-service-version`: 1.5.0
- `UI5` version: latest
- `node-version`: 16.20.0
- OS: macOS Ventura 13.3.1
- Browser + Version: Chrome Version 113.0.5672.92

**Comment by borceacristiann** [comment]
Hi, I ran the tests again using the same versions as in your examples but unfortunately it still doesn't work.

Based on the screenshots, I can see that the test user is redirected to a blank page after authentication.

The following error is logged in the terminal: 
             script timeout: script timeout
            (Session info: headless chrome=113.0.5672.126)
             at processTicksAndRejections (node:internal/process/task_queues:96:5)
             at async **clientSide__checkForUI5Ready** (/node_modules/wdio-ui5-service/client-side-js/_checkForUI5Ready.js:2:12

Do you have any idea why it crashes?

**Comment by borceacristiann** [comment]
I tried different approaches today and noticed that the tests pass if I consume the application directly from the HTML5 Application Repository Service through the app-router.

This makes me think that there is a problem with the portal or with injectUI5...

Do you have any test where the user accesses the UI app from a launchpad/porta?

**Comment by borceacristiann** [comment]
Hi,

I would like to mention that I have been using wdio with ```wdi5```for more than 6 months and so far I  did not have any problems with the ```portal```(```Cloud Portal Service``` provided by ```BTP```) or with accessing UI apps through the ```portal``` tiles.

Also in ```headful``` mode everything works fine as before, there is no problem with the ```portal```, all the tiles are displayed and can be clicked in order to access the apps.
Only in ```headless``` mode the user is redirected to a blank page instead of the ```portal```.

I checked the elements of the portal page and did not find any ```iframe```...

So I really don't understand how until now the tests were working without any problem and now they don't work anymore and why in ```headfull``` mode the tests can interact with the ```portal``` apps and in ```headless``` mode a blank is shown instead of the ```portal``` tiles.

**Comment by Siolto** [comment]
This error:
```shell
the following error is logged in the terminal:
script timeout: script timeout
(Session info: headless chrome=113.0.5672.126)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async clientSide__checkForUI5Ready (/node_modules/wdio-ui5-service/client-side-js/_checkForUI5Ready.js:2:12
```
just tells us that there is no UI5 Application present in the browser. As you already mentioned the redirection is somehow failing.
Could you maybe try to add following flag in your `capabilities`: `--ignore-certificate-errors`. Maybe there are some bad certificates in the portal or so, which are blocking the redirection in the headless mode.

**Comment by borceacristiann** [comment]
It didn't help.

I checked the URL after the login step and it's ok, it's the URL that would normally show the portal. 

I also saved a screenshot after the login step and it's a blank/white page, nothing related to the portal.
![screenshot after authentication](https://github.com/ui5-community/wdi5/assets/40524367/11c52595-cb64-4e88-98fe-6870867c69ca)

I increased the timeout and made the browser wait a few minutes before interacting with the portal, but regardless of the waiting time it still shows a blank page.

**Comment by borceacristiann** [comment]
Hi, any idea what I could do? As I mentioned, within a year the tests were working without a problem, and the fact that it no longer works slows the whole team down to deliver because we have to manually test….

**Comment by vobu** [comment]
hi @borceacristiann, I'm sorry to hear that your issues still persist. However, this doesn't seem to have anything to do with `wdi5`: as mentioned above, our samples work w/o issues with Chrome >= 113. 
So your problem is related to the BTP Cloud Portal Service. Have you tried approaching the colleagues there whether they changed anything on their end? We unfortunately have no sample Cloud Portal Service environment at hand to replicate the issue.

Another idea that came to my mind was whether this might have anything to do with the `User-Agent` being reported by headless Chrome to whatever webserver software is running behind Cloud Portal Service.
v112 headless: https://explore.whatismybrowser.com/useragents/parse/384165669-headless-chrome-linux-webkit
v112 headful: https://whatmyuseragent.com/browser/ch/chrome/112
v113 headless: https://explore.whatismybrowser.com/useragents/parse/369052700-headless-chrome-linux-webkit
v113 headful: https://whatmyuseragent.com/browser/ch/chrome/113

So you might try providing a custom user agent string to chrome headless in your config file:
```js
capabilities: [
    {
      browserName: 'chrome',
      acceptInsecureCerts: true,
      'goog:chromeOptions': {
        args: ['user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36.0 (KHTML, like Gecko) Chrome/112.0.5615.165 Safari/537.36.0'],
      },
    },
  ]
```

**Comment by borceacristiann** [comment]
Hi @vobu, you are right it seems my problem is related to ```BTP Cloud Portal Service```, I will ask them if they have changed anything on their end. If I get a response from the ```BTP Cloud Portal Service``` team, I will let you know.

FYI: I specified a custom user agent but it didn't help.

**Comment by borceacristiann** [comment]
Hello, I received a response from the portal team, this is as follows:
Dear Colleagues, 
It seems that this issue appeared about two weeks ago, and as nothing was changed on our side, this issue is not coming from our end. 
Maybe something within your test environments has changed, or something within the chrome headless version. 
Unfortunately, this is out of our scope and there is not much we could do to help as you mentioned in other browsers this is working and there is no known issue for chrome headless."

**Comment by vobu** [comment]
oh man, I'm sorry to hear this...remindes me of https://giphy.com/gifs/reaction-bcrOR2stk6tKIxqPOZ 🤣 
However, as the steering committee has voted in favor of it: soon it will be possible to offer commercial support for `wdi5`, also for SAP-internal repos. It will be endorsed via GitHub sponsors. 
Then it should be possible to also look at your codebase and get this thing resolved...
