### ISSUE TITLE
Testing sap.m.MessageToast

### ISSUE THREAD

**Issue by Rchn1907** [ui5-community/wdi5#471]
**Describe the bug**
I am currently working on an application and would like to test it now.
When clicking a button the user gets a MessageToast as a response and I wanted to test this now.
I tried to initialize the control as follows:

```
const messageToast = await browser.asControl({
selector: {
controlType: "sap.m.MessageToast",
viewId: "...testApp.view.Main",
id: "messageToast"
}
});
```
But now I noticed that this UI5 control was not found.
Therefore my question was, if it is not possible to test a MessageToast with `wdi5.` 

**To Reproduce**

 1. Use the Code above
 2. see the Error 

**Runtime Env:**

- `wdi5/wdio-ui5-service`-version: "^1.5.0"
- `UI5` version: "^2.0.1"
- `wdio`-version (output of `wdio --version`): "^7.31.1"
- `node`-version (output of `node --version`): "v18.15.0"
- OS: Windows 11
- Browser + Version Chrome Version 113.0.5672.93

**Comment by Siolto** [comment]
Hi @Rchn1907,

a message toast cannot be via wdi5. You have to use native `wdio` to identify and interact with the control.

Keep in mind that message toasts automatically disappear after a specific timeout and you have to match the timing correctly.

Best regards,
Simon

**Comment by Rchn1907** [comment]
Hi @Siolto,
Thank you for you fast answer.
To use the native `wdio` I have to use` .getWebElement()` or `.$()`
Am I right?

**Comment by Siolto** [comment]
you can do something like that:

```javascript

        const messageToast = await $('.sapMMessageToast') // css selector
        await expect(messageToast).toHaveText("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy\n eirmod.")
```
