### ISSUE TITLE
editing an object page

### ISSUE THREAD

**Issue by diya-dhan** [ui5-community/wdi5#476]
**Description**
This is less of a bug and more of a query. I want to edit and save the object page in my app. But I am unsure how to continue once I execute the edit button.

**To Reproduce**

1. When.onTheDetailPage.onHeader().iExecuteEdit()
I require some help with what functions I need to use following this. I assume I need to perform some onForm actions but my tests do not get executed, they stop abruptly.

**Expected behavior**
I want to be able to edit and save my changes to the object page

**Runtime Env:**
wdi5/wdio-ui5-service-version: 1.3.2
@ui5/cli version: 1.13.0
@wdio/cli-version : 7.31.1
node-version : 18.4.0
OS: MacOS Ventura
Browser + Version : Chrome, Version : 112.0.5615.137

**Comment by vaibhav0461** [comment]
Hi @diya-dhan, 

Were you able to solve this.. we are new in using wdi5 to write e2e tests for UI Screens which uses Fiori Elements and data v4. we are creating new Business Object so we are able to click on create button in list report and navigate to Object Page now we want to enter values in Header title, description and in Header Facets. We read through the documentation of sap.fe.test library but not able to make it success.  This is the code we tried.

![Screenshot 2024-03-16 at 3 47 23 PM](https://github.com/ui5-community/wdi5/assets/46601979/b385c9c8-ee57-435b-8947-06b4d5bfb788)
Screen looks like this
![Screenshot 2024-03-16 at 3 47 52 PM](https://github.com/ui5-community/wdi5/assets/46601979/fe728530-e8a8-43a0-a452-9c26607c4fbc)


This is the annotation file for the Object Page Header section
![Screenshot 2024-03-16 at 3 44 21 PM](https://github.com/ui5-community/wdi5/assets/46601979/4110d1cc-f2fd-4e40-ab56-39513313e3fc)
