### ISSUE TITLE
Question: Scrolling in sap.ui.table.Table

### ISSUE THREAD

**Issue by ThePylaa** [ui5-community/wdi5#477]
Hey!

I'm currently trying to scroll inside a sap.ui.table.Table. Most of the tutorials out there tend to use the scrollIntoView() method, which unfortunately doesn't work for these SAP tables ([API Ref](https://sapui5.hana.ondemand.com/#/api/sap.ui.table.Table%23overview): "When the user scrolls, only the row contexts are changed, but the rendered controls remain the same"). I've tried other things like scroll() and scrollBy() described in the [mdn web docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/scroll) but haven't been able to get them to work. Is there something I'm missing?

Thanks in advance :)

**Comment by ThePylaa** [comment]
OK, so I've found a solution, but I don't think it's very nice:

`it("should scroll with arrowDown", async () => {
    let firstCell = await browser.asControl(firstRowFirstCell)
    await firstCell .press()
    for (let i = 0; i < 80; i++) {
      browser.keys("ArrowDown")
    }
    expect(await firstCell .getText()).toEqual("templateName 43")
  })`

If there's a cleaner solution, I'd like to hear it :)

**Comment by dominikfeininger** [comment]
Since this is very specific to this table control, maybe the OPA5 team knows a cleaner solution.

**Comment by vobu** [comment]
> OK, so I've found a solution, but I don't think it's very nice:
> 
> `it("should scroll with arrowDown", async () => {` ` let firstCell = await browser.asControl(firstRowFirstCell)` ` await firstCell .press()` ` for (let i = 0; i < 80; i++) {` ` browser.keys("ArrowDown")` ` }` ` expect(await firstCell .getText()).toEqual("templateName 43")` ` })`
> 
> If there's a cleaner solution, I'd like to hear it :)

na man, i think you're good here 😄 - we never had the use case before. 
Looking at your code, the only remark I have is that you want to make sure your browser always starts with the same `width x height` ratio, so that pressing ⬇️ 80 times reliably gets you to the `templateName 43` point.
