### ISSUE TITLE
feature request in Office365Authenticator skip the Pick and Account screen

### ISSUE THREAD

**Issue by jasper07** [ui5-community/wdi5#480]
Description
When testing BTP apps using MicrosoftEdge I am faced with the "Pick an Account" screen see pic below,
![ms](https://github.com/ui5-community/wdi5/assets/837243/1a2fbfa6-8442-4443-98ea-18e9dba2a9e8)

this isnt an issue more of a feature request to skip that screen if it shows up, if i find time to test i will do a PR

I dont get this screen with either Chrome or FireFox, it looks like both start a browser with a temporary profile for each session which doesnt know who i am, MicrosoftEdge however opens with a temporary profile that does know all my AAD logins and so  I see the "Pick an Account" screen 

the work around is to add the arg --InPrivate in the options

To Reproduce
have multiple MS accounts and try and access a BTP app using Office365 authentication 

The solution is to click on the line in Office365Authenticator

 ```js
...
this.useAnotherAccountSelector = "[id=otherTileText]"

async login() {
    if (!(await this.getIsLoggedIn())) {
      const useAnotherAccountDiv = await $(this.useAnotherAccountSelector)
      if (useAnotherAccountDiv) {
        useAnotherAccountDiv.click()
      }

 ```

Runtime Env:
wdi5/wdio-ui5-service-version: 1.5.0
@ui5/cli version: 1.13.0
@wdio/cli-version : 7.31.1
node-version : 18.4.0
OS: Windows 10
Browser + Version : MicrosoftEdge, Version : 114.0.1823.43

**Comment by vobu** [comment]
still on the todo list :)

**Comment by dominikfeininger** [comment]
@jasper07 is the provided workaround working for you'? 

Would be nice to have, but it is quite a corner case.
Anyways, not seeing any capacity to implement this feature request in the near future.

@jasper07 you are more than welcome to create an PR for this. Have a look into the [contribution guide](https://ui5-community.github.io/wdi5/#/contributing) to get startet.

**Comment by jasper07** [comment]
agree a corner case
