### ISSUE TITLE
Question: Automate wdi5 tests in bitbucket

### ISSUE THREAD

**Issue by Rchn1907** [ui5-community/wdi5#482]
Hello Guys,

I wanted to automate my wdi5 tests using a pipeline in bitbucket.

Then, unfortunately, I ran into a problem because my tests fail immediately without executing them properly.

That's why I wanted to ask how I can automate my tests. In my version attached I used a normal "atlassian/default-image:4" image and installed chrome on it, but unfortunately this didn't work.

What kind of Docker image do I need to use?

What additional things do I need to install?

![2174526-image](https://github.com/ui5-community/wdi5/assets/116603031/306bfb3b-4086-4134-802b-67424b674bd8)
![2174527-image](https://github.com/ui5-community/wdi5/assets/116603031/d3f7daab-f18b-479c-be6e-cbb1cf94202c)

**Comment by Siolto** [comment]
Hi @Rchn1907,

maybe you can have a [look](https://github.com/ui5-community/wdi5/blob/main/.github/workflows/wdi5-tests_js-app.yml) how we do things in the pipeline.
We are using the `ubuntu-latest` image and before we start the tests we also update chrome to the newest version.
