### ISSUE TITLE
Documentation about installation misleading

### ISSUE THREAD

**Issue by tobiashofmann** [ui5-community/wdi5#485]
Going through the installation document (https://github.com/ui5-community/wdi5/blob/main/docs/installation.md) I came across a situation where there is a slight difference between docu and reality.

I opted for quickstart and TypeScript. 

Documentation: add config files (wdio.conf.ts + tsconfig.json) to a folder test in your current working directory

I read this that both files will be created under a folder test. What I got was wdio.conf.ts in the root folder of my project, and only tsconfig.json in a folder test.

/wdio.conf.ts
/test/tsconfig.json

**Comment by vobu** [comment]
`ACK` - `tsconfig.json` needs to go into the `test` folder as not to mess up transpliation scopes with the actual ts app.
Would you mind putting your finding into a PR for the documentation 😄 ?
(https://ui5-community.github.io/wdi5/#/contributing?id=work-on-the-docs)
