### ISSUE TITLE
Test failing with javascript error 'undefined (reading 'waitForUI5Options')'

### ISSUE THREAD

**Issue by Rchn1907** [ui5-community/wdi5#490]
**Describe the bug**
I have the Problem that my tests arre failing sometimes at the start with this error above in screenshot section.
I don`t know why.
We have a sap Fiori App with CAP.

**Expected behavior**
My other Apps start normal with the same tests, but in this app it becomes every time this error.

**Logs/Console Output**
[chrome 114.0.5735.134 windows #0-0] javascript error: Cannot read properties of undefined (reading 'waitForUI5Options')
JavaScript stack:
TypeError: Cannot read properties of undefined (reading 'waitForUI5Options')
    at eval (eval at executeAsyncScript (:443:26), <anonymous>:4:65)
    at eval (eval at executeAsyncScript (:443:26), <anonymous>:33:8)
    at eval (eval at executeAsyncScript (:443:26), <anonymous>:33:33)
    at executeAsyncScript (<anonymous>:443:47)
    at apply.selector.id (<anonymous>:458:29)
    at callFunction (<anonymous>:338:22)

**Screenshots**
![image](https://github.com/ui5-community/wdi5/assets/116603031/3c108d82-3235-4a12-886d-06c480fd258d)
**My Wdio.conf.js-File:**
![image](https://github.com/ui5-community/wdi5/assets/116603031/d7f18d1f-5b73-49ac-92af-cad26dfb1944)
![image](https://github.com/ui5-community/wdi5/assets/116603031/84a59d09-5123-470d-a640-9f0e0e52f8ea)
![image](https://github.com/ui5-community/wdi5/assets/116603031/12edf767-98f6-4a08-b4cb-fa1de48f5604)

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: "^1.5.1"
- `UI5` version: "^2.11.1"
- `wdio`-version (output of `wdio --version`): ^7.31.1
- `node`-version (output of `node --version`): 18.5.0
- OS: Windows 11
- Browser + Version: Chrome ^114.0.2

**Comment by Siolto** [comment]
maybe the basic-authentication of the cap server is preventing the startup of the application sometimes?

**Comment by Rchn1907** [comment]
No the page loading proccess is sometimes too long but I fix it with waitforTimeout.
I want to know what this error means with waitForUI5Options.
Is there any Configuration, where I have to add it, because I added it myself in the wdio.conf.js, but I don`t know if it is the right place there

**Comment by MartaGolabek** [comment]
I receive the same error.

**Comment by Siolto** [comment]
Hi @MartaGolabek,

can you give us a little bit more context about your specific issue? Do you also have a UI5 Application with CAP? How does your current configuration look like?

Thanks!

**Comment by MartaGolabek** [comment]
Hi @Siolto.

I have a Fiori App with CAP
Runtime Env:

wdi5/wdio-ui5-service-version: "^2.0.6"
"wdio-chromedriver-service": "^8.1.1",
node-version (output of node --version): v20.11.0

I am running it on WSL.

**Comment by MartaGolabek** [comment]
My fault, I forgot to set variables for basic auth.
