### ISSUE TITLE
UI5 Selectors not found when executing the WDI5 script

### ISSUE THREAD

**Issue by Vikrant87-lego** [ui5-community/wdi5#495]
Hi All,

I am trying to use WDI5 on my SAP application , I tried recording the scenario using the UI5 journey recorder.
I have a Select list on my front end which i am trying to call but the element is never found.

[0-0] [wdi5] call of _getControl() failed because of: Error: No DOM element found using the control selector {"id":"application-tpsrfplanning-manage-component---Master--planbookfilter","interaction":"press","sOriginalControlType":"sap.m.Select"}
[0-0] [wdi5] error retrieving control: applicationtpsrfplanning-manage-component---Master--planbookfiltersap.m.Select
[0-0] [wdi5] cannot call press(), because control could not be found
[0-0] [wdi5] call of _getControl() failed because of: Error: No DOM element found using the control selector {"searchOpenDialogs":true,"viewId":"application-app-tile-component---Master","sOriginalControlType":"sap.m.SelectList"}
[0-0] [wdi5] error retrieving control: sapm.SelectList
[0-0] [wdi5] cannot call press(), because control could not be found

Test Script:const { assert } = require("chai");
const { wdi5 } = require("wdio-ui5-service");		
const Main = require("./pageObjects/Main")
const titleSelector = { selector: { id: "container-Sample---Main--Title::NoAction.h1" } }

describe("Test", async ()=>{

    beforeEach(async () => {
        await browser.screenshot("Interactions before")
    })

    afterEach(async () => {
        await browser.screenshot("Interactions-after")
    })

	it("should have the right title", async () => {
        const title = await browser.getTitle()
        expect(title).toEqual("TPS : PlanbookName 1 MGDesc 1")
    })
	it("Should select planbook",async()=>{

		const selector= {
			selector: {
				controlType: "sap.m.Select",
				id: "application-tpsrfplanning-manage-component---Master--planbookfilter",
				interaction:"press"
			}
		
		}
		
		const planbooklist = await browser.asControl(selector)

		await planbooklist.press()

		const selector1={
			
			selector: {
				controlType: "sap.m.SelectList",
				viewId: "application-app-tile-component---Master",
				searchOpenDialogs: true,
				
			}
		}
		const selectplanbook=await browser.asControl(selector1).press()		
	})

	it("Should Click Go button",async()=>{
		const selector= {
			selector: {
				id: "application-app-tile-component---Master--smartFilterBar-btnGo",
			}
		
		}
		

		const gobtn = await browser.asControl(selector)

		await gobtn.press()

		await browser.pause(5000)
		
	})

	
})

		
I wanted to understand where am i going wrong.
Config:
"@sapui5/sap.ui.comp": "^1.108.14",
 "wdio-ui5-service": "^1.5.1"

**Comment by vobu** [comment]
hi, config and syntax all reading/looking legit here 😸 
and the error message is pretty descriptive if you ask me:  `No DOM element found using the control selector {"searchOpenDialogs":true,"viewId":"application-app-tile-component---Master","sOriginalControlType":"sap.m.SelectList"}`
have you tried retrieving the control you're aiming for via the Test Recorder https://ui5.sap.com/sdk/#/topic/2535ef9272064cb6bd6b44e5402d531d.html?

**Comment by Vikrant87-lego** [comment]
Hi Volker,

So i intially started using the UI5 journey recorder but it seems like some of the steps that i try to record for my application are not recorded in the journey. So i switched to UI5 Test Recorder and found the right selectors and created my test but when i try to use the Baseurl as "http://localhost:8080/index.html" i get this issue where the selctors are not found error is thrown.

I had word with my devteam and they suggested me to  change the base url to http://localhost:8080/test/flpSandbox.html and when i used this URL my script started working.

So i want to know that i should continue using the sanbox url or there are some configuration that i am missing to work with index.html ?

Regards,
Vikrant

**Comment by dominikfeininger** [comment]
This just depends on you application under test. Usually it works like:
- `index.html` is used to start the app standalone
- `flpSandbox.html` is used to simulate a Fiori Launchpad environment to launch the application

Hope this helps.

ps. I am closing this issue. Feel free to ask any further questions
- regarding [wdi5](https://openui5.slack.com/archives/C01E6UUU0R4)
- regarding [ui5](https://openui5.slack.com/archives/C0R5DSPDL)

in these slack channels
