### ISSUE TITLE
WDI5 is not triggering the LiveChange event of sap.m.Input control

### ISSUE THREAD

**Issue by alvinisabboy** [ui5-community/wdi5#496]
**Describe the bug**
In our test codes,  we call setValue to assign text value for the control, event "LiveChange" of sap.m.Input control is not triggered, the function of handling the event is not executed.

**To Reproduce**
	1	Find the sap.m.Input control by selector, and call .setValue("textValue") to assign value for this control
	2	LiveChange event of the Input control is not triggered, the function of handling the event is not executed.

**Expected behavior**
The event "LiveChange" of the Input control is triggered, and event handling function is executed

**Screenshots**
<img width="737" alt="image" src="https://github.com/ui5-community/wdi5/assets/41322911/a8d25eaa-b13b-4e3e-94c1-8b3921c2158f">
<img width="1122" alt="image" src="https://github.com/ui5-community/wdi5/assets/41322911/70ce39b6-570a-4694-8e36-597bcfb87fda">

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 1.5.1
- `node`-version (output of `node --version`): 18.15.0

**Comment by Siolto** [comment]
I guess we still have the same problem here as we had with: #355. We still have to sync with the OPA guys how we can solve this issue.
