### ISSUE TITLE
Multiremote:  fluent async API and browser.asControl does not work

### ISSUE THREAD

**Issue by Siolto** [ui5-community/wdi5#500]
When using the multiremote feature of wdio the method chaining like:
```javascript
await browser.one.asControl({
  selector: {...}
}).press()
```
does not work. The control is retrieved correctly from **browser.one** but wdio tries to press the control in both browsers.

When using the multiremote feature interacting with the same control over multiple browser at once via `await browser.asControl()...` does not work properly.

**Comment by vobu** [comment]
this is still a shortcoming...

**Comment by vobu** [comment]
nooo, unfortunately not

**Comment by vobu** [comment]
this is still relevant
