### ISSUE TITLE
cap + basic auth

### ISSUE THREAD

**Issue by mpah** [ui5-community/wdi5#502]
Im running a local CAP project with cds watch. The ui5 apps in "app/..." can be accessed with no issues at:

[http://localhost:4004/appname/webapp/test/flpSandbox.html](http://localhost:4004/appname/webapp/test/flpSandbox.html)

wdi5 works as well, the issue is however Im using basic auth (CAP mock strategy defined in top lvl package.json).

I tried supplying the credentials both 

1. through dotenv and also 
2. directly when runnign wdi:

`set wdi5_username=a&& set wdi5_password=a&& wdio run ./wdio.conf.js`

When I 

`console.log(process.env) `

inside the test.js file I can see the credentials listed properly

`[0-0]   wdi5_password: 'a',
[0-0]   wdi5_username: 'a',`

I can see the basic auth window pop up twice but the ui5 page itself does not load.

Ive used BTP auth and that worked without issues, the login happens immediatly.

**Runtime Env:**

- `wdi5/wdio-ui5-service`-version: 1.5.1
- `UI5` version: 1.112.1
- `node`-version: 18.12.1
- OS: Windows 11
- Chrome

**Comment by vobu** [comment]
yep, this is a tricky one and already tracked in https://github.com/orgs/ui5-community/projects/2/views/1?pane=issue&itemId=18873812 - there is movement on this, together with some colleagues from PwC.
Do you want to chime in, coding-wise? Then I'd hook you up for the upcoming meeting.

**Comment by mpah** [comment]
Yes sure

**Comment by mpah** [comment]
> yep, this is a tricky one and already tracked in https://github.com/orgs/ui5-community/projects/2/views/1?pane=issue&itemId=18873812 - there is movement on this, together with some colleagues from PwC. Do you want to chime in, coding-wise? Then I'd hook you up for the upcoming meeting.
Yes sure

**Comment by vobu** [comment]
> > yep, this is a tricky one and already tracked in https://github.com/orgs/ui5-community/projects/2/views/1?pane=issue&itemId=18873812 - there is movement on this, together with some colleagues from PwC. Do you want to chime in, coding-wise? Then I'd hook you up for the upcoming meeting.
> 
> Yes sure

then shoot me an e-mail to volker.buzek@js-soft.com and I'll forward the meeting invite!

**Comment by dominikfeininger** [comment]
@mpah any updates on this after our meeting? Eagerly awaiting your PR ;)
