### ISSUE TITLE
wdi5 not waiting until sap build work zone, standard edition ui5 content is loaded

### ISSUE THREAD

**Issue by mpah** [ui5-community/wdi5#503]
Writing a wdi5 script to ensure the deployed ui5 apps work fine on sap build work zone, standard edition.
Ive set as baseUrl the app directly:

`https://customer.launchpad.cfapps.eu20.hana.ondemand.com/site/flp?sap-language=de-DE#admin-display`

Auth works fine. Afterward Im only testing the visibility of the ListReport

```
describe("test suite description", () => {
  before(async () => {
    await browser.screenshot("0 - start")
  })

  it("should do this", async () => {
    await browser.screenshot("1 - before check")

    const visible = await browser.asControl({
    	selector: {
            controlType: "sap.m.ColumnListItem",
            viewName: "sap.fe.templates.ListReport.ListReport",
            viewId: "customer.app.admin::TenantsList",
            bindingPath: {
                    value: "navigatedRow"
            }
    }}).getVisible();
    expect(visible).toBeTruthy();
    await browser.screenshot("2 - after check")  
  })
```
})

The test fails and the Screenshots look like the following:
**0 - start**
![image](https://github.com/ui5-community/wdi5/assets/15245583/4a750f65-ce05-4bf9-9c14-c2638791a7dc)
**1 - before check**
![image](https://github.com/ui5-community/wdi5/assets/15245583/c6b4a5a5-8846-4a15-a7b1-77e02cadd11b)

**2 - after check** 
not screenshoted due to test fail.

wdi5/wdio-ui5-service-version: 1.5.1
UI5 version: 1.112.1
node-version: 18.12.1
OS: Windows 11
Chrome

**Comment by vobu** [comment]
and yet you've hit another tricky one. this is due to workzone's `iframe` usage for pulling in UI5 apps. 
but for the workzone enablement, we're almost there: https://github.com/ui5-community/wdi5/pull/447
we still need to finalize the api and write adequate tests. 
as a remedy for now, please use the wz apps full uri as `baseUrl` in the config - just like you've already done

**Comment by mpah** [comment]
> and yet you've hit another tricky one. this is due to workzone's `iframe` usage for pulling in UI5 apps. but for the workzone enablement, we're almost there: #447 we still need to finalize the api and write adequate tests. as a remedy for now, please use the wz apps full uri as `baseUrl` in the config - just like you've already done

All green with the base url, thank you! Appreciate the fast responses and looking forward to the real fix eventually.

**Comment by mpah** [comment]
> and yet you've hit another tricky one. this is due to workzone's `iframe` usage for pulling in UI5 apps. but for the workzone enablement, we're almost there: #447 we still need to finalize the api and write adequate tests. as a remedy for now, please use the wz apps full uri as `baseUrl` in the config - just like you've already done

I have another (maybe) related issue to this. Ive spend hours assuming something wrong with my setup as the deployed github action did not work, while the local one works. This is usually and indicator of Environment differences.

However it turns out there was no problem with my setup, as soon as i run against a public ui5 app, everything is fine.

This is the only thing that changed to result in green tests on github actions:

![image](https://github.com/ui5-community/wdi5/assets/15245583/85662363-264c-4e5d-aff6-c3bcfb1aad77)

![image](https://github.com/ui5-community/wdi5/assets/15245583/a5b073c2-30cf-4aff-b100-24b3ed30b0ef)


And this is the verbose error from the previous run:

![image](https://github.com/ui5-community/wdi5/assets/15245583/86405952-cbc0-42db-8d28-880d98f6e455)

I was digging into waitForUI5Options for a bit and my assumption here is that wdi5 cant find the ui5 (bootsrap) here.

**Comment by dominikfeininger** [comment]
This is usually the case when something is not right with the connection from webdriver to browser. Could be some config, loading modules like `chromedriver` missing or timing related.

Probably happens here
https://github.com/ui5-community/wdi5/blob/a4f7ef9568e5b15968f177e53a92c06e3f1c1c5d/src/lib/wdi5-bridge.ts#L136

Hope this helps for your further investigation.

ps. I am closing this issue, feel free to open another regarding this topic.
