### ISSUE TITLE
WDI5 doesn't work correctly together with 3D model viewer

### ISSUE THREAD

**Issue by MikhailDryk** [ui5-community/wdi5#504]
**Describe the bug**
After upgrading SAPUI5 version from 1.108 to 1.114 some specs which includes [reusable component](https://github.wdf.sap.corp/SAPPIN/copin-uilib/tree/master/src/com/sap/copin/uilib/dtwincomponent) with 3D viewer go wrong.

All WDI5 locators end with an element search error after the reusable component with 3D viewer appears on the screen. As a result, the only way to locate elements is by searching through DOM elements. 

I have investigated failed tests and saw that it go wrong in [should navigate back to FLP](https://github.wdf.sap.corp/SAPPIN/C4P-WDI5/blob/69c50fa9bbc5a28928d1228d2edbc47f7878e13f/test/specs/performance/test_cases_scenarios/scenario_common.js#L60) step. After running all the tests, I found a common issue for all the failed tests – the 3D Viewer appeared on the screen

Added screenshots of failed tests
[F3136_DigitalTwinQuery](https://github.wdf.sap.corp/SAPPIN/C4P-WDI5/blob/master/test/specs/performance/F3136_DigitalTwinQuery.js)
![image](https://github.com/ui5-community/wdi5/assets/64844079/555c2658-001a-471e-8159-b04a6e24ead0)

[F3136_DigitalTwinObjectReferences](https://github.wdf.sap.corp/SAPPIN/C4P-WDI5/blob/master/test/specs/performance/F3136_DigitalTwinObjectReferences.js)
![image](https://github.com/ui5-community/wdi5/assets/64844079/ef442399-7643-4727-a0aa-a3f38c76a023)

[F3136_DigitalTwinObjectDetails](https://github.wdf.sap.corp/SAPPIN/C4P-WDI5/blob/master/test/specs/performance/F3136_DigitalTwinObjectDetails.js)
![image](https://github.com/ui5-community/wdi5/assets/64844079/d29a0feb-a055-45ed-92a9-ff3fae19949c)

I have already created the issue #449 related to this case before but without any updates

**To Reproduce**

1. Go to the application by [link](https://bigbuild-performance-copin.internal.cfapps.sap.hana.ondemand.com/cp.portal/site?sap-language=en#CollbtvProjectDigitalTwin-manage?sap-ui-app-id-hint=com.sap.copin.digitaltwin.ui&/DigitalTwins/fe070b5b-79e3-4d61-b7b5-5654bd52bf8c/a720d9e5-637c-422c-9eee-1eb35ef68f3f/f639a53a-f601-465c-9104-6d006f24dfa8/true)
2. Please, get in touch with me ([mikhail.dryk@sap.com](mailto:mikhail.dryk@sap.com)) to get creditionals to the application,
3. Clone [repository](https://github.wdf.sap.corp/SAPPIN/C4P-WDI5)
4. Execute in console command
```shell
$> wdio run wdio.perf.conf.js --spec ./test/specs/performance/<FILE NAME>.js --baseUrl=https://bigbuild-performance-copin.internal.cfapps.sap.hana.ondemand.com/ --params.pass=**** --params.user=**** 
```
I will provide `--params.pass` and `--params.user`

**Expected behavior**
All tests should complete successfully

**Runtime Env (please complete the following information):**

- `wdio-ui5-service`-version: `^1.5.1`
- `UI5` version: `1.114.1`
- `wdio`-version (output of `wdio --version`): `^7.26.0`
- `node`-version (output of `node --version`): `18.16.1`
- OS: `Linux`
- Browser + Version `chrome 114.0.5735.133`

**Comment by vobu** [comment]
hi, thanks for the detailed error report! that makes evaluating the situation easier 👍 
however, as you wrote in the opening paragraph: the failed tests seem to stem from _upgrading UI5 from 1.108 to 1.114_, not from `wdi5` itself → your tests do work when the app bootstraps UI5 1.108, correct?
(also, internal SAP links are not accessible for us. there'll soon be commercial support available for `wdi5`, but we're not there yet)

**Comment by dominikfeininger** [comment]
Hi, you are more than welcome to create an 3D model viewer example where this issue is reproduceable so we can investigate this issue.

**Comment by MikhailDryk** [comment]
Hello @dominikfeininger 

Thanks for reply. Do you have access to the SAP environment? I can provide you conditionals to the page where we have 3D Viewer

like this

![image](https://github.com/ui5-community/wdi5/assets/64844079/1e0d79b6-844a-465c-8938-4edd4b8da3da)

**Comment by MikhailDryk** [comment]
Hello colleagues

Do you have any updates about my issue?

**Comment by vobu** [comment]
hi and sorry, currently all efforts go toward wdi5^2. Once this is done (hopefully mid next week), let's get back to your issue here. Thanks for your understanding!

**Comment by MikhailDryk** [comment]
Hello @vobu 

Do you have any updates about my issue?

**Comment by vobu** [comment]
📫 "you have mail" 😸

**Comment by MikhailDryk** [comment]
Hello (Volker)@vobu 

Can we reopen this issue, because my issue wasn't fixed.
