### ISSUE TITLE
Unable to Click on sap.suite.ui.commons.networkgraph.ActionButton

### ISSUE THREAD

**Issue by borceacristiann** [ui5-community/wdi5#507]
**Describe the bug**
I encountered an issue where I am unable to click on the sap.suite.ui.commons.networkgraph.ActionButton element. 
Instead of pressing the action button, its parent element (sap.suite.ui.commons.networkgraph.Node) gets clicked.

**Steps to Reproduce**

1. Use the following selector to locate and press the action button:
```
    const actionButtonSelector = {
        selector: {
            controlType: "sap.suite.ui.commons.networkgraph.ActionButton",
            properties: {
                icon: "sap-icon://menu"
            }
        }
    }
    const actionButton = await browser.asControl(actionButtonSelector);
    
    const $actionButton = await actionButton.getWebElement()
    await $actionButton.click()
```

Actual Behavior:
The parent element (sap.suite.ui.commons.networkgraph.Node) is clicked instead of the intended sap.suite.ui.commons.networkgraph.ActionButton.

Additional Information:
When debugging, I noticed that the _metadata of the control obtained based on the selector contains the following discrepancies:
- The className is reported as sap.suite.ui.commons.networkgraph.Node instead of sap.suite.ui.commons.networkgraph.ActionButton.
- The id is associated with Node rather than ActionButton (verified through DOM inspection).

Please refer to the attached screenshot for visual representation of these properties.

**Expected behavior**
The sap.suite.ui.commons.networkgraph.ActionButton should be clickable.

**Screenshots**
![image](https://github.com/ui5-community/wdi5/assets/40524367/5780d8e5-b6d0-4a34-aac2-5667d703cf37)

**Runtime Env:**

- `wdi5/wdio-ui5-service`-version: 1.5.1
- `UI5` -version: 1.96.0
- `wdio`-version: 7.32.1
- `node`-version: 18.12.1
- `OS`: macOS Monterey 12.6
- `Browser + Version`: Chrome 106.0.0

Please let me know if any further information is required to address this bug

**Comment by dominikfeininger** [comment]
I am not familiar with the NetworkGraph but had a look into this [sample](https://sapui5.hana.ondemand.com/sdk/#/entity/sap.suite.ui.commons.networkgraph.Graph/sample/sap.suite.ui.commons.sample.NetworkGraph). Are you aware of the click order? Like "first click on the node to expand the action buttons and click the buttons secondly"?

**Comment by borceacristiann** [comment]
Hi @dominikfeininger, yes I am aware, and I respected the order in my test.

**Comment by Siolto** [comment]
Hi @borceacristiann,

maybe the [interaction](https://ui5-community.github.io/wdi5/#/recipes?id=using-interaction-on-a-selector) selector could help you here. So maybe try something like this:

```javascript
    const actionButtonSelector = {
        selector: {
            controlType: "sap.suite.ui.commons.networkgraph.ActionButton",
            properties: {
                icon: "sap-icon://menu"
            },
            interaction: "press"
        }
    }
```

One question: Why are you using the Webdriver.IO native `click` instead of the built in [press](https://ui5-community.github.io/wdi5/#/usage?id=press) event of wdi5?

**Comment by borceacristiann** [comment]
Hi @Siolto!

It still doesn't work even if I use the press method.

As I mentioned in the bug description, the problem is that I can't even locate the action button of the node.

The _metadata of the control obtained based on the selector contains the following discrepancies:

1. The className is reported as sap.suite.ui.commons.networkgraph.Node instead of sap.suite.ui.commons.networkgraph.ActionButton.
2. The id is associated with Node rather than ActionButton (verified through DOM inspection).

Please refer to the attached screenshot for visual representation of these properties.
<img width="1716" alt="image" src="https://github.com/ui5-community/wdi5/assets/40524367/a8028bf5-a72d-4243-bc73-d8de01e99af0">
