### ISSUE TITLE
Performance after migrating to Wdi5 

### ISSUE THREAD

**Issue by abdelhaknezzari** [ui5-community/wdi5#508]
**Describe the bug**
We are migrating from OPAE2E to Wdi5, and we noticed that the performance of our pull request is not better, it is even taking 10 minutes more to run our scenarios.

**To Reproduce**
Before the migration, it is taking 29 minutes:
<img width="436" alt="image" src="https://github.com/ui5-community/wdi5/assets/36274787/5ac73bc6-7b8b-471b-9344-7a592b1b680d">

After the first migration:

<img width="351" alt="image" src="https://github.com/ui5-community/wdi5/assets/36274787/7faf6c6d-86de-4afd-bca3-d9bbf192d58f">

After the second migration, even worse:
<img width="364" alt="image" src="https://github.com/ui5-community/wdi5/assets/36274787/6ce731b1-8344-4801-92a5-554dc7f64cd3">

we can show the pull request to our SAP internal colleagues involved in this project,

In the First migration we mainly did the following change:
<img width="817" alt="image" src="https://github.com/ui5-community/wdi5/assets/36274787/c64d6619-faca-4119-a449-73aac19eeec0">

To check the visibility and text of button we are doing to calls, and every call is doing a round trip to the browser to retrieve the information.

We think that this can be improved to retrieve the text and the visibility properties of the control, at the time when we retrieve it 
<img width="702" alt="image" src="https://github.com/ui5-community/wdi5/assets/36274787/f4d883da-019a-45b8-a097-27f6dbc27595">
Doing it this way, we think it can save us the two round trip, Do you think this can be achieved ?

In the second migration:
We switched to retrieve all the controls via method:
<img width="909" alt="image" src="https://github.com/ui5-community/wdi5/assets/36274787/d840d978-0efb-4ac1-86b7-5ea4c9a42874">
instead of OPAE2E:
<img width="810" alt="image" src="https://github.com/ui5-community/wdi5/assets/36274787/2381aa99-422a-4f97-9789-ea586fd7cb62">

and we lost 5 minutes more, no idea how we can get better in time.

**Expected behavior**
Better time than OPAE2E but it is worse

**Logs/Console Output**

**Screenshots**

**Runtime Env (please complete the following information):**

W can show it to SAP colleagues involved in this project,

**Additional context**

**Comment by dominikfeininger** [comment]
wdi5 is more the replacement for UIveri5

`OPA5 is the fastest of the three, as it shares the runtime with UI5, saving infrastructure overhead such as launching the browser itself.` - https://blogs.sap.com/2020/11/19/state-of-testing-in-ui5-opa5-uiveri5-and-wdi5/

wdi5 is known to be about a third slower  since it operates the UI as an external user.

**Comment by Siolto** [comment]
Hi,

what @dominikfeininger said. Maybe you could send a link(via Mail) to your PR, that we could have a look if there is room of improvement.

What could save a lot of time if you run multiple tests in parallel via the `maxInstances` in your `.conf.js` file. Could you try that out?

Regards,
Simon

**Comment by abdelhaknezzari** [comment]
Hi @dominikfeininger @Siolto, 
We have measured the duration of all steps in our feature files for two pull requests, one using OPA and the other WDI5, and we compiled the results to a CSV file where you can see the name of the step, and the three columns: duration_opa, duration_wdi5, and diff, We are still looking to the result of the steps. where we can see big difference, if we can improve the performance with wdi5, I can share the PRs and results via internal email,
Thank you,
Best regards,
Abdelhak
