### ISSUE TITLE
UI5 component methods not available in WDI5

### ISSUE THREAD

**Issue by VoskanGrigoryan** [ui5-community/wdi5#511]
I'm writing a WDI5 script to test the sort and filter functionality of a table using the ViewSettingsDialog component. 

This is how I'm retrieving the dialog and I make sure it's actually open when trying to interact with it

```
const oFilterButton = await browser.asControl({
      selector: {
          interaction: "press",
          id: "/.*filterButtonDocDetailsId$/",
      },
});

await oFilterButton.press()

const oFilterDialogDocDetails = await browser.asControl({
    selector: {
        interaction: "root",
        id: "/.*idFilterDocDetailsDialog$/",
    },
});

await oFilterDialogDocDetails.open()
```

When using the isOpen method on oFilterDialogDocDetails, the result is true
`const isOpen = await oFilterDialogDocDetails.isOpen()` <- returns true

When debugging the object we get we can't find the methods we need inside the generatedUI5Methods nor the generatedWdioMethods.
![image](https://github.com/ui5-community/wdi5/assets/71737745/d6eadbf6-9612-491c-9adf-cda86f938e33)

For example, when trying to search for methods that are available in the SDK documentation for the ViewSettingsDialog such as getFilterItems, getSelectedFilterItems, etc, I cannot find the methods we need for interacting with the filter dialog inside the generatedUI5Methods array provided.

We also tried retrieving all the methods of the ViewSettingsDialog via the `oFilterDialogDocDetails.getControlInfo().methods`  line but the result is the same, the methods used in the SDK are not available. 

Is there a solution for testing a sort/filter functionality in a viewSettingsDialog currently in WDI5 or is this missing?

**Comment by dominikfeininger** [comment]
Please try to double check in browser within the running application to get the dialog via eg. `sap.ui.getCore().byId("idFilterDocDetailsDialog-dialog")`  and find the methods.

It sems not possible  in the example here: https://sapui5.hana.ondemand.com/sdk/#/entity/sap.m.ViewSettingsDialog/sample/sap.m.sample.ViewSettingsDialog

Which leads to the conclusion that UI5 is doing some stuff under the hood which needs further investigation.

**Comment by Siolto** [comment]
Most likely UI5 is doing some magic under the hood.

Nevertheless, to test your dialog you should not depend on internal functions of the control. Simply "press" on the buttons or items you want to press and assert on the results (e.g. the number of items in a list is now less)

**Comment by dominikfeininger** [comment]
Does this solve your issue?

Otherwise, @VoskanGrigoryan support is welcome. Can you please create a working example for this issue. Even better would be a suggestion about the issue in UI5

**Comment by VoskanGrigoryan** [comment]
Hello, we have tried getting the items by id and pressing them directly, 

// Get the Descending option
         ```
const oDescRB = await browser.asControl({
             selector: {
                 controlType: "sap.m.RadioButton",
                 viewId: "application-comaccciozerotouchbillingrequestor-display-component---master",
                 properties: {
                     editable: true
                 },
                 searchOpenDialogs: true,
                 ancestor: {
                     controlType: "sap.m.StandardListItem",
                     viewId: "application-comaccciozerotouchbillingrequestor-display-component---master",
                     properties: {
                         title: "Descending"
                    },
                     searchOpenDialogs: true
                 }
             }
        });
```

After this we just select the item with 
` await oDescRB.setSelected(true);`

However this does not seem to work because the test still fails because even tho we are selecting the item manually, that does not get translated to the app therefore no changes are applied to the sorting order in the list for example.

**Comment by FranciscoLaurino** [comment]
hi, any chance you can help us with this?
