### ISSUE TITLE
Incorrect order of columnListItems

### ISSUE THREAD

**Issue by helenamann** [ui5-community/wdi5#515]
**Describe the bug**
When fetching the sap.m.ColumnListItems of a sap.m.Table, the order of the columnListItems seem to be incorrect. 
I have a table with four ColumnListItems. Then I want to check the content of each columnListItem assuming that the index 0 has the content of the first entry (in the UI), index 1 has the content of the second entry and so on. Unfortunately this is not the case. It seems that index 0 has the content of the fourth entry, index 1 has the content of the first entry, index 2 has the content of the second entry and index 3 has the content of the third entry.
I am not able to manually reproduce this issue in the browser. There, I receive the columnListItems in the correct order.

**To Reproduce**

**Expected behavior**
Same order of the columnListItems as it is shown in the UI

**Screenshots**
```
it("should sort according to the maintenance status", async () => {
      await ListReport.iShouldSeeTable();
      await ListReport.iShouldSeeXInTableRowNumber(entry1, 1);
      await ListReport.iShouldSeeXInTableRowNumber(entry2, 2);
      await ListReport.iShouldSeeXInTableRowNumber(entry3, 3);
      await ListReport.iShouldSeeXInTableRowNumber(entry4 0);
});
```

```
public static async iShouldSeeXInTableRowNumber(entry: string, number: number) {
    const columnListItems = await browser.allControls<ColumnListItem>({
      selector: {
        controlType: "sap.m.ColumnListItem",
      },
    });

    const columnListItemId = await columnListItems[number].getId();

    const objectIdentifier = await browser.asWrappedControl<ObjectIdentifier>({
      selector: {
        controlType: "sap.m.ObjectIdentifier",
        ancestor: {
          controlType: "sap.m.ColumnListItem",
          properties: { id: columnListItemId },
        },
      },
    });

    const objectIdentifierTitle = await objectIdentifier.getTitle();

    expect(objectIdentifierTitle).toBe(entry);
}
```

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 1.5.2
- `UI5` version: [e.g. 1.98.0]
- `wdio`-version (output of `wdio --version`): [e.g. 7.16.12]
- `node`-version (output of `node --version`): v18.17.0
- OS: [e.g. Linux openSuSE]
- Browser + Version: chrome version 116

**Additional context**
Add any other context about the problem here,
e.g. any options the target browser is started with like `--headless` or
if the tests run in a CI environment

**Comment by Siolto** [comment]
Unfortunately with our dummy application I can not reproduce your issue. We would have to look together on your issue.

What you could try in the meantime as a workaround is following:

```javascript
const table = await browser.asControl({
    selector: {
        id: "idOfMyTable"
    }
})

const columnListItem = await table.getItems(number) // shorthand
const columnListItemId = await columnListItem.getId()
```

Regards,
Simon

**Comment by helenamann** [comment]
Issue was solved by using a workaround:
To get the columnListItems in the right order, we get the sap.m.table and call the method getAggregation("items")

See these two issues for reference:
https://github.com/SAP/ui5-uiveri5/issues/211
https://github.com/ui5-community/wdi5/issues/283
