### ISSUE TITLE
Does the wdio/cli only install the latest dependencies?

### ISSUE THREAD

**Issue by diya-dhan** [ui5-community/wdi5#521]
Issue:
I tried to setup my testing environment by using the wdio/cli. Here I made sure to choose the ui5 service. I assumed since wdi5 is currently only supported by wdio v7, all the dependencies would be installed in the compatible versions. But all the wdio packages were installed with version 8. I would like to know if this is the expected behavior, even when using wdio/cli v7?

1. Install wdio/cli : npm i @wdio/cli@7
2. Run npx wdio config
3. Choose: local runner, mocha framework, spec reporter, chrome browser, ui5 service
4. All dependencies in the package.json file will be of version 8

Expected behavior:
Since the wdi5 service is being added, expected all webdriverio dependencies to be of version 7.

**Comment by vobu** [comment]
Hi, the intended way to get started with `wdi5` is to do `npm init wdi5@latest` - it will install the "ui5"-service along with all matching `wdio`-dependencies for you. Also see https://ui5-community.github.io/wdi5/#/installation.
That being said, `wdi5` 2.0 is in beta and about to be released in the next couple of days. Amongst other things it will bring full `wdio`^8 compatability.

**Comment by diya-dhan** [comment]
Ah I see. Assumed the same support was available with the cli. Thank you @vobu!
