### ISSUE TITLE
Normal mode and headless mode don't act the same way

### ISSUE THREAD

**Issue by XiangShotray** [ui5-community/wdi5#526]
**Describe the bug**
A clear and concise description of what the bug :

As I want to run script in pipeline which using headless mode, I noticed that the normal mode and headless mode don't act the same way. While normal mode can run successfully as following, headless mode will report some errors.

<img width="726" alt="image" src="https://github.com/ui5-community/wdi5/assets/143694646/e6b3b91d-086e-4822-ac17-0fdb509ac835">

The error mostly appear when clicking or pressing, and sometimes shows element cannot interact.

<img width="2097" alt="image" src="https://github.com/ui5-community/wdi5/assets/143694646/15281434-115c-4fbe-91ca-c5cf0c7e3fcb">

I have tried to change view port(1440,800 & 1920 1280), but it doesn't work.

**To Reproduce**

1. Please get in touch with dongdong(dongdong.zheng@sap.com) for credential

2.  try and see log on pipeline [pipeline](https://jenkins.copin.c.eu-de-1.cloud.sap/view/Master%20(Team%20Dragon)/job/SAPPIN/job/c4p-project-plan/job/master/)

or

1. Clone [repository](https://github.wdf.sap.corp/SAPPIN/C4P-WDI5)

2. Execute in console command

$$>npx wdio run wdio.conf.js --spec ./test/c4p-project-plan-ui/specs/<FILE NAME>.spec.js  --params.user=**** --params.pass=**** --headless$
$$>npx wdio run wdio.conf.js --spec ./test/c4p-project-plan-ui/specs/<FILE NAME>.spec.js  --params.user=**** --params.pass=****$

**Expected behavior**
All tests should complete successfully

**Logs/Console Output**
if applicable, please copypasta _code-fenced_ log output, e.g.

```shell
$> ...
```

**Screenshots**
if applicable, add screenshots to help explain your problem.

The error that headless mode reports.

<img width="2100" alt="image" src="https://github.com/ui5-community/wdi5/assets/143694646/dad5099f-e77e-45f6-8426-22f84425f94e">

**Runtime Env (please complete the following information):**

- `wdio-ui5-service`-version: ^1.5.1
- `UI5` version: 1.114.1
- `wdio`-version (output of `wdio --version`): ^7.26.0
- `node`-version (output of `node --version`): 18.16.1
- OS: Linux & macos
- Browser + Version :  chrome 116.0.5845.110

**Additional context**
Add any other context about the problem here,
e.g. any options the target browser is started with like `--headless` or
if the tests run in a CI environment

**Comment by Shotray** [comment]
The problem has been solved now.

**Comment by XiangShotray** [comment]
The problem has been solved now.
