### ISSUE TITLE
getting fraction value of HarveyBallMicroChart control

### ISSUE THREAD

**Issue by MarkR87** [ui5-community/wdi5#532]
**Describe the bug**
We are using the HarveyBallMicroChart control to show some data in a table.
In the xml view its looks like that, where you configure the chart itself and one item, defining the fraction of the chart:

```XML
<HarveyBallMicroChart size="XS" total="100" totalScale="Mrd" press="press">
		<items>
			<HarveyBallMicroChartItem fraction="63.5" color="Good" fractionScale="Mrd"/>
		</items>
</HarveyBallMicroChart>
```

In a test-case, where we manipulate the bound data, we would like to check the value of the fraction (part of the HarveyBallMicroChartItem).

If I access the properties of the control via ui5, I can easily get the values of the fraction properties.
```sap.ui.getCore().getElementById("IdOfTheChart").getItems()[0].getFraction()```

Unfortunately, if I try the same in WDI5 with a selector like that:

```Typescript
    const charts = await browser.allControls<HarveyBallMicroChart>({
      selector: {
        controlType: "sap.suite.ui.microchart.HarveyBallMicroChart",
      },
    });

    const chartItem = await charts[0].getAggregation("items"); 
    const chart = await chartItem[0] as HarveyBallMicroChartItem;
    const fraction = chart.getFraction();
    expect(fraction).toEqual(number);
```

**Expected behavior**
Can get the fraction value via getFraction().

**Logs/Console Output**
I'm getting a:
 `[0-0] [wdi5] call of _getControl() failed because of: Error: No DOM element found using the control selector {"id":"__item6-__clone1"}` as soon as I execute the `const chartItem = await charts[0].getAggregation("items");`.

`__item6-__clone1` is indeed the id of the item I`m looking for.

**Screenshots**
![image](https://github.com/ui5-community/wdi5/assets/110391426/20064f5f-c15c-4c9c-9b8c-4f1b7de829ae)

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 1.5.5
- `UI5` version: 1.117.1
- `wdio`-version (output of `wdio --version`): 7.32.4
- `node`-version (output of `node --version`): v18.14.0

**Comment by MarkR87** [comment]
maybe one possible solution is to use wdio.

```Typescript
    const chart = $$(".sapSuiteHBMCValue")[0];
    const fraction = await chart.getText();
    expect(fraction).toEqual(number.toString());
```

**Comment by Siolto** [comment]
It looks like the `HarveyBallMicroChart` behaves a little bit weird. When you take a look at the control with the UI5 Inspector there is no `HarveyBallMicroChartItem` we can identify with wdi5.
<img width="919" alt="image" src="https://github.com/ui5-community/wdi5/assets/32054457/330de3e1-3990-469d-a5ad-410f44117991">
 Maybe you could create an Issue for the SAPUI5/OpenUI5 colleagues.

Your workaround with wdio looks promising.
