### ISSUE TITLE
WDI5 Script failing when run in Jenkins

### ISSUE THREAD

**Issue by Afsar-Hussain-088** [ui5-community/wdi5#537]
- A wdi5 script when run in local environment runs perfectly without failing, but when the same script runs in the jenkins, it fails.
- The Script is giving error that it's not able to find the particular selector, but when the same code is run locally it locates successfully.
- We tried different ways like changing the selectors, we used different standard WDI5 selectors, but it doesn't work.

**Expected behavior**
The Script should run in jenkins too.

**Screenshots**
1. jenkins console with the error :
![image](https://github.com/ui5-community/wdi5/assets/127526990/bc66a487-b44a-45ef-a9b6-006a9625d963)

- `wdi5/wdio-ui5-service`-version: [1.5.5]
- `UI5` version: 1.114.1
- `wdio`-version (output of `wdio --version`): [7.26.0]
- `node`-version (output of `node --version`): [v18.16.0]
- OS: [Linux]
- Browser + Version [chrome  v114.0.5735.133]

2.result in console when run in local : 
![image](https://github.com/ui5-community/wdi5/assets/127526990/915f579a-14f2-4e58-966d-a5c61ae151a3)

- `wdi5/wdio-ui5-service`-version: [^1.5.1]
- `UI5` version: 1.114.1
- `wdio`-version (output of `wdio --version`): [^7.26.0]
- `node`-version (output of `node --version`): [v18.17.1]
- OS: [Windows]
- Browser + Version [chrome ^113.0.0]

Please let us know if you need any further information.

**Comment by vobu** [comment]
well, it seems the obvious difference is in how things are run on Jenkins as opposed to the local setup.
You're positive that you can access the UI5 app under test from Jenkins?
How about doing a `await browser.screenshot()` and see what the app looks like from the Jenkins perspective?

**Comment by Afsar-Hussain-088** [comment]
yes, the test starts running on jenkins till some step, and after some steps, it fails. So yeah We can access UI5 app under jenkins.

**Comment by vobu** [comment]
then this clearly indicates an issue w/ Jenkins rather than w/ `wdi5`.
if you need specific, in-detail support, please consider booking a contingent of commercial support via GitHub sponsors: https://github.com/ui5-community/wdi5/blob/main/SUPPORT.md

**Comment by Afsar-Hussain-088** [comment]
Initially we had used Standard wdi5 functions for selectors and in one of our UI Components we have issue using those functions, So we had to use DOM selectors instead. The step where its failing is using Standard function. So we are thinking this might be WDI5 issue itself.

**Comment by Afsar-Hussain-088** [comment]
We tried by running it on Jenkins using different Docker Images and different versions of it, Now I tried using selenium/standalone-chrome image(tried beta, dev, 107, 114, 115)  and somehow its unable to start the Chromedriver. 

screenshot : 

![image](https://github.com/ui5-community/wdi5/assets/127526990/1830aab1-6aac-47fe-8d79-037f45f5e313)


please let us know if you have any suggestions why this might be failing. Is it because of some chromedriver version issue? or something else.

**Comment by nair-sumesh** [comment]
Did you try upgrade the wdi5 to version 2. This will allow you to use the binary version of chromedriver. May that resolves your issue.
