### ISSUE TITLE
Element has no focus error

### ISSUE THREAD

**Issue by diya-dhan** [ui5-community/wdi5#545]
I've been testing my fiori app and thus have been making use of the OData V4 test library. I am trying to change the row of a table using the ObjectPage.onTable().iChangeRow() function. But I keep running into the following error:

 **the string "Changing row values of table '{id: fe::table::conversations::LineItem::i18nConversations}' with old values='0' to new values='{Message: ABCDEFGHIJK, Timestamp: 19 Nov 2023, 20:57:38}' - FAILURE\nFailure in Opa success function\nException thrown by the testcode:'Error: DOM representation of control 'Element sap.m.Input#__input0-__clone40-__clone41' has no focus DOM reference**

NOTE : until yesterday this code worked fine when running the script in non-headless mode. this problem first occurred when running it headless and now I am facing the same problem when running it normally as well.

Here is the function call:
<img width="611" alt="image" src="https://github.com/ui5-community/wdi5/assets/77057240/2c7c6ee4-731d-4e97-8b59-bdc98e6cfadc">

The intention is to create a new row in the table Conversations (as shown below). Here are the corresponding elements:
<img width="1764" alt="image" src="https://github.com/ui5-community/wdi5/assets/77057240/397a19a4-38f3-433e-8fe2-bf6e05357ac8">

Here are the corresponding error logs received:
<img width="1297" alt="image" src="https://github.com/ui5-community/wdi5/assets/77057240/d8c9bc28-911e-4dc8-bfb9-988b5b3534c6">

Runtime Env :

wdi5/wdio-ui5-service : 1.5.0
@ui5/cli : "12.14.10",
@wdio/cli: "8.16.11",
node : v18.14.0
OS: MacOS Ventura
Browser + Version : Firefox, Version : 116.0.0

**Comment by bkrencker** [comment]
Have same error here.. maybe somebody can pick this issue up and have a look at it?
