### ISSUE TITLE
Q: Where does 'browser script timeout set to 16000' comes from

### ISSUE THREAD

**Issue by nair-sumesh** [ui5-community/wdi5#551]
**Describe the bug**
How to overwrite the timeout in wdi5.

I tried several ways like below
```
browser.asControl({
      selector: {
        id: "",
      },
      timeout: 90000,
      forceSelect: true,
    });
```
in config as
```
  wdi5: {
   ....
    waitForUI5Timeout: 270000
  },
...
  waitforTimeout: 270000,
...
  cucumberOpts: {
 ...
    // <number> timeout for step definitions
    timeout: process.env.DEBUG === 'true' ? 999999 : 270000,
    
  },

```
**Expected behavior**
Should be able to set timeout out from the config file.

- `wdi5/wdio-ui5-service`-version: `2.0.2`
- `UI5` version: `[1.119.0]`
- `wdio`-version (output of `wdio --version`): `8.16.12`
- `node`-version (output of `node --version`): `v18.16.1`
- OS:`macOS 13.5.2 `
- Browser + Version : ` Chrome version 117.0.5938.92`

**Comment by vobu** [comment]
what you're asking in the subject of this is in https://github.com/ui5-community/wdi5/blob/9d6cff1af0a922eca5c1ef01ab4a197a5de58808/src/lib/wdi5-bridge.ts#L123

so `wdi5.waitForUI5Timeout` and `wdio`'s [script timeout](https://webdriver.io/docs/timeouts/#session-script-timeout) are aligned.

there is no `timeout` option in the `browser.asControl`-selector: https://github.com/ui5-community/wdi5/blob/9d6cff1af0a922eca5c1ef01ab4a197a5de58808/src/types/wdi5.types.ts#L186

**Comment by nair-sumesh** [comment]
as per the calculation for 

```js
const timeout = waitForUI5Timeout + 1000 
```
the timeout should be 271000.
However, why do i see the console log with timeout set to 16000?

**Comment by nair-sumesh** [comment]
### TEMPORARY SOLUTION

https://github.com/ui5-community/wdi5/blob/9d6cff1af0a922eca5c1ef01ab4a197a5de58808/examples/ui5-js-app/webapp/test/e2e/ui5-late.test.js#L3C1-L3C37

```js
const ui5Service = new _ui5Service(undefined,undefined,{wdi5:{waitForUI5Timeout:270000}});
```

**Comment by vobu** [comment]
ahhh, this means that programmatic instantiation of the `ui5` service (aka `wdi5` core) doesn't pull any existing config per default!
we could change this and make [the constructor](https://github.com/ui5-community/wdi5/blob/9d6cff1af0a922eca5c1ef01ab4a197a5de58808/src/service.ts#L15) pull the [config that was provided for starting `wdi5`](https://github.com/ui5-community/wdi5/blob/9d6cff1af0a922eca5c1ef01ab4a197a5de58808/examples/ui5-js-app/package.json#L14) when late-injected. 
Think this makes sense and you wanna give it a shot, @nair-sumesh 😸 ?

**Comment by nair-sumesh** [comment]
While I debugged , I couldn't find the config data. The ˋbrowserInstance` does have few config properties but not the specific ˋwdi5` one.

Is the config already being persisted in any global variable?

**Comment by vobu** [comment]
fixed with https://github.com/ui5-community/wdi5/pull/552

**Comment by vobu** [comment]
here's the migration guide: https://ui5-community.github.io/wdi5/#/migration?id=from-1-to-2
this is where all the config lives: https://ui5-community.github.io/wdi5/#/configuration
and programmatically, there's 
- `browser.options`
- and as a last resort: `global.__wdi5Config`
