### ISSUE TITLE
unknown error: cannot deserialize the result value received from Runtime.callFunctionOn

### ISSUE THREAD

**Issue by marianfoo** [ui5-community/wdi5#557]
**Describe the bug**
Error thrown with FE V4 SAPUI5 1.120 on method `getBindingContext()` https://github.com/marianfoo/ui5-cc-spreadsheetimporter/blob/4dd811a70272fc6171555436c8c065bf0c4829bc/examples/test/specs/Objects/FEV4.js#L60

see github action run:
https://github.com/marianfoo/ui5-cc-spreadsheetimporter/actions/runs/6816727497/job/18538689782

It seems error only for Fiori Elements OData V4 with SAPUI5 Version 1.120

**To Reproduce**

1. `git clone https://github.com/marianfoo/ui5-cc-spreadsheetimporter`
2. `git checkout test/120`
3. `pnpm i`
4. `pnpm start:server`
5. `pnpm start:v4fe:120`
6. `cd examples`
7. `npm run test -- ordersv4fe  120 --spec ./test/specs/all/UploadFileObjectPage.test.js`

**Expected behavior**
No error

**Logs/Console Output**
if applicable, please copypasta _code-fenced_ log output, e.g.

```shell
[chrome 118.0.5993.117 linux #0-4] 1) Upload File Object Page check Field: validFrom
[chrome 118.0.5993.117 linux #0-4] unknown error: cannot deserialize the result value received from Runtime.callFunctionOn
  (Session info: chrome=118.0.5993.117)
[chrome 118.0.5993.117 linux #0-4] unknown error: unknown error: cannot deserialize the result value received from Runtime.callFunctionOn
[chrome 118.0.5993.117 linux #0-4]   (Session info: chrome=118.0.5993.117)
[chrome 118.0.5993.117 linux #0-4]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[chrome 118.0.5993.117 linux #0-4]     at async executeControlMethod (/home/runner/work/ui5-cc-spreadsheetimporter/ui5-cc-spreadsheetimporter/node_modules/.pnpm/wdio-ui5-service@2.0.2_@wdio+cli@8.18.2_@wdio+local-runner@8.18.2_@wdio+mocha-framework@8.18._dqzhjicgm7f2oljenbbv2lawui/node_modules/wdio-ui5-service/client-side-js/executeControlMethod.cjs:14:12)
[chrome 118.0.5993.117 linux #0-4]     at async clientSide_executeControlMethod (/home/runner/work/ui5-cc-spreadsheetimporter/ui5-cc-spreadsheetimporter/node_modules/.pnpm/wdio-ui5-service@2.0.2_@wdio+cli@8.18.2_@wdio+local-runner@8.18.2_@wdio+mocha-framework@8.18._dqzhjicgm7f2oljenbbv2lawui/node_modules/wdio-ui5-service/client-side-js/executeControlMethod.cjs:143:18)
[chrome 118.0.5993.117 linux #0-4]     at async WDI5Control._executeControlMethod (file:///home/runner/work/ui5-cc-spreadsheetimporter/ui5-cc-spreadsheetimporter/node_modules/.pnpm/wdio-ui5-service@2.0.2_@wdio+cli@8.18.2_@wdio+local-runner@8.18.2_@wdio+mocha-framework@8.18._dqzhjicgm7f2oljenbbv2lawui/node_modules/wdio-ui5-service/src/lib/wdi5-control.ts:515:25)
[chrome 118.0.5993.117 linux #0-4]     at async FEV4.getDateFields (/home/runner/work/ui5-cc-spreadsheetimporter/ui5-cc-spreadsheetimporter/examples/test/specs/Objects/FEV4.js:60:19)
[chrome 118.0.5993.117 linux #0-4]     at async Context.<anonymous> (/home/runner/work/ui5-cc-spreadsheetimporter/ui5-cc-spreadsheetimporter/examples/test/specs/all/UploadFileObjectPage.test.js:129:24)
```

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 2.0.2
- `UI5` version: 1.120.0
- `wdio`-version (output of `wdio --version`): 8.18.2
- `node`-version (output of `node --version`): 18.4
- OS: mac/Linux
- Browser + Version chrome 1.119

**Comment by vobu** [comment]
ping to FE lib integration specialist @Siolto on this one :)

**Comment by Siolto** [comment]
Error exists since SAPUI5 Version 1.115.0 on Fiori Elements v4 applications. Further analysis needed

**Comment by marianfoo** [comment]
Ok, thanks for looking into it.
But it doesn't sound like there is a quick solution.
Any workaround?

**Comment by Siolto** [comment]
not yet... I am more confused by the issue than i really understand it. I will keep you in the loop.

**Comment by marianfoo** [comment]
fix helped me, all tests are green :)
https://github.com/marianfoo/ui5-cc-spreadsheetimporter/actions/runs/7292241157
