### ISSUE TITLE
Cannot read properties of undefined (reading 'wdi5') after upgrade to 2.0.3

### ISSUE THREAD

**Issue by robertiqkkk** [ui5-community/wdi5#563]
**Describe the bug**
We are getting the error: **Cannot read properties of undefined (reading 'wdi5'**) after the `wdio-ui5-service` upgrade to `2.0.3`.
**PS:** On the `wdio-ui5-service` `2.0.2` there is no issue.
As a result, that [PR](https://github.com/ui5-community/wdi5/pull/552/files) seems to be the cause.
Specifically the changes `src/service.ts` -> `.injectUI5` -> `config["wdi5"] = global.__wdi5Config.wdi5`

In our [Jenkins run](https://jenkins.copin.c.eu-de-1.cloud.sap/view/Performance/job/CoPM_SupaPerformanceTests_ProjectManagement/130) we see the following behavior:
Right after the manual login into the FLP we are injecting the UI5 dependencies:

The function that we are using for that manual log in:
```js
const _ui5Service = require("wdio-ui5-service").default;
const ui5Service = new _ui5Service();
module.exports = {
	login: function () {
		it("should login to the system", async () => {
			const username = browser.options.capabilities["custom:params"].user;
			const password = browser.options.capabilities["custom:params"].pass;

			const link = await browser.$(
				`a[href$='copin.accounts400.ondemand.com&isPassive=true']`
			);
			if (await link.isExisting()) {
				await link.click();
			}

			const usernameInput = await browser.$('//input[@id="j_username"]');
			if (await usernameInput.isExisting()) {
				await usernameInput.setValue(username);
				await $('//input[@id="j_password"]').setValue(password);
				await $('//button[@id="logOnFormSubmit"]').click();
			}

			await ui5Service.injectUI5(); !!! <- The call of the UI5 dependencies injection !!!
			console.log("Successfully logged in to the system.");
		});
	},
};

```

After that call there is an error that blocks the tests execution:
```
TypeError: Cannot read properties of undefined (reading 'wdi5')
12:23:33  info  sapSUPAExecuteTests -     at Service.<anonymous> (/home/jenkins/workspace/CoPM_SupaPerformanceTests_ProjectManagement/C4P-WDI5/node_modules/wdio-ui5-service/cjs/service.js:208:66)
12:23:33  info  sapSUPAExecuteTests -     at step (/home/jenkins/workspace/CoPM_SupaPerformanceTests_ProjectManagement/C4P-WDI5/node_modules/wdio-ui5-service/cjs/service.js:33:23)
12:23:33  info  sapSUPAExecuteTests -     at Object.next (/home/jenkins/workspace/CoPM_SupaPerformanceTests_ProjectManagement/C4P-WDI5/node_modules/wdio-ui5-service/cjs/service.js:14:53)
12:23:33  info  sapSUPAExecuteTests -     at fulfilled (/home/jenkins/workspace/CoPM_SupaPerformanceTests_ProjectManagement/C4P-WDI5/node_modules/wdio-ui5-service/cjs/service.js:5:58)
12:23:33  info  sapSUPAExecuteTests -     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

You can see that the error is coming from the `services.js` function on line 208, here is that function (basically compilied and minified TS code from the PR I've shared above)
Here is that function (taken from node_modules `wdio-ui5-service` `2.0.3` version )
```js
    Service.prototype.injectUI5 = function (browserInstance) {
        if (browserInstance === void 0) { browserInstance = browser; }
        return __awaiter(this, void 0, void 0, function () {
            var config;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, (0, wdi5_bridge_js_1.checkForUI5Page)(browserInstance)];
                    case 1:
                        if (!_a.sent()) return [3 /*break*/, 3];
                        config = this._config ? this._config : browserInstance.options;
                        if (!config["wdi5"]) {
                            //Fetching config from global variable
                            config["wdi5"] = global.__wdi5Config.wdi5; !!! <- The line that causes the error !!!
                        }
                        return [4 /*yield*/, (0, wdi5_bridge_js_1.injectUI5)(config, browserInstance)];
                    case 2:
                        _a.sent();
                        return [3 /*break*/, 4];
                    case 3: throw new Error("wdi5: no UI5 page/app present to work on :(");
                    case 4: return [2 /*return*/];
                }
            });
        });
    };
```
Honestly not sure why `global.__wdi5Config` is `undefined` in our case and only when we run in Jenkins.
Locally the issue doesn't seem to appear...

**To Reproduce**

1. Go to one of our Jenkins Runs - https://jenkins.copin.c.eu-de-1.cloud.sap/view/Performance/job/CoPM_SupaPerformanceTests_ProjectManagement/130/
2. Click on 'Rebuild', do not change the settings, it has specifically the branch with `"wdio-ui5-service": "^2.0.0"` in package.json
3. Check the Pipeline logs

**Expected behavior**
Ther is no error when we call `.injectUI5`

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service` version: `2.0.3`
- `UI5` version: `1.114.9`
- `wdio` version: `8.23.1`
- `node` version: `20.5.1`
- `OS`: `Jenkins`
- `chrome as chromedriver` + `118.0.1.`

**Comment by dominikfeininger** [comment]
Hi @nair-sumesh, could you please have a glance at this issue?

**Comment by nair-sumesh** [comment]
> Hi @nair-sumesh, could you please have a glance at this issue?

Works fine in Jenkins jobs for JS based test.     
I will not be able to verify for TS version, however, AFAIK, both should behave same.

**Comment by robertiqkkk** [comment]
Hello @dominikfeininger, @nair-sumesh 

Then any hints on what might be wrong in our setup that it fails to get the wdi5 config during the ui5 injection?

BR,
Robert

**Comment by Siolto** [comment]
@robertiqkkk: we don't have access to your Jenkins pipelines (no SAP employees). Could you maybe share your configuration file?

**Comment by robertiqkkk** [comment]
I've been contacted by @nair-sumesh with the ask to run on the newer SAPUI5 version.
But in the end also executed all our specs on the current version we use and now it doesn't fail.
Honestly confused what was the root cause then, maybe the docker image from the performance team we are obliged to use, but now it's impossible to check.

Anyway, closing as there are no issues anymore.
