### ISSUE TITLE
Unable to select ComboBox after updated UI5 lib to 1.120

### ISSUE THREAD

**Issue by jump912** [ui5-community/wdi5#564]
We are trying to pick up the empty ComboBox during testing.

![Screenshot 2023-11-20 at 11 54 46 AM](https://github.com/ui5-community/wdi5/assets/1579308/66b04af7-ce12-44f7-ac1a-5971aff55503)

![Screenshot 2023-11-20 at 11 56 27 AM](https://github.com/ui5-community/wdi5/assets/1579308/5f564364-2ccb-4540-a08f-65dcc59e9011)

Looking at the recorder, we drafted the selector below. 
_Note: the viewName is changed on purpose. the actual selector matches the one in the recorder._

``` javascript
await browser.asControl({
    	selector: {
            controlType: "sap.ui.comp.smartfield.ComboBox",
            viewName: “com.app.main.LinkageCriterias",
            bindingPath: {
                    propertyPath: "type_ID"
            },
            interaction: {
                    idSuffix: "inner"
            },
	    properties: {
	    	    selectedKey: “”
	    }
    }});
```

When the test run, we will get error No DOM element found. This was working in UI5 version 1.111. It stopped working after updating to 1.120 and we need to update the UI5 lib to the latest maintenance version for support purpose. we also tried using the next lower maintenance version 1.114 but yield the same error.

We also tried other more elaborated way to try to select it (which we can discuss if required) but those has its own set of unique issue. e.g. it works on one page but doesn't on another page. both pages are fiori element generated table of the same entity with same properties, even the DOM is the same. However, this is where the problem started. So let's see if there's a solution to the root problem here.

**Comment by dominikfeininger** [comment]
Hi @hmanchev, do you have some insides to help identify the root cause? I didn't find anything in the changelog.

**Comment by Siolto** [comment]
Maybe this issue and #557 have the same root cause?

**Comment by jdichev** [comment]
Hello @jump912,

What would be the recommended reproduce sequence? Right now I am trying the following
1. Open a sap.m.ComboBox sample at https://sdk.openui5.org/resources/sap/ui/documentation/sdk/index.html?sap-ui-xx-sample-id=sap.m.sample.ComboBox&sap-ui-xx-sample-lib=sap.m&sap-ui-xx-sample-origin=.&sap-ui-xx-dk-origin=https%3A%2F%2Fsdk.openui5.org&sap-ui-theme=sap_horizon&sap-ui-rtl=false&sap-ui-density=sapUiSizeCompact
2. Activate Test Recorder
3. Right button click on the ComboBox and select Press
The result is as expected - a test snippet is generated as follows
```
iPressTheControl: function () {
    this.waitFor({
        controlType: "sap.m.ComboBox",
        viewName: "sap.m.sample.ComboBox.view.ComboBox",
        bindingPath: {
            path: "",
            propertyPath: "/CountriesCollection"
        },
        actions: new Press({
                idSuffix: "inner"
            })
    });
}
```

Thanks and best regards,
Jordan

**Comment by jdichev** [comment]
Hello @vobu,

Sure. Updated my comment respectively.

Best regards,
Jordan

**Comment by jdichev** [comment]
Hello,

Seems the generated selector for some reason causes issue with WDI5 but I am no expert. @vobu could we get a hint what is wrong with this selector so we can address that in the Test Recorder code?

Best regards,
Jordan

**Comment by Siolto** [comment]
@jump912 can you give us a reproducible example? Than we can have a detailed look!
