### ISSUE TITLE
Failed to load sap/ui/core/SortOrder.js when running OPA5 Tests with the wdio-qunit-service

### ISSUE THREAD

**Issue by meindla** [ui5-community/wdi5#567]
**Describe the bug**
We are running OPA5 tests using the OPA5 Test library for Fiori Elements V4 and the wdio-qunit-service.
The sap resources are served statically by the tooling extension ui5-middleware-servestatic. The resources are downloaded from https://tools.hana.ondemand.com/#sapui5.
Starting the test results in following error:
![image](https://github.com/ui5-community/wdi5/assets/121859054/cd66d173-d670-4eac-8605-713e5659e4cc)

In the opaTests.qunit.html, I reference the static resources:
![image](https://github.com/ui5-community/wdi5/assets/121859054/f11c6665-2240-434d-bc23-45e53a8860d5)

Following the dependencies in the error log 
 -> 'sap/fe/test/ListReport.js'
  -> 'sap/fe/test/TemplatePage.js'
   -> 'sap/fe/test/builder/MdcTableBuilder.js'
    -> 'sap/ui/core/SortOrder.js'
I wonder where I can find the SortOrder.js in the sap/ui/core folder. There is no such file. 
Using the resources from https://sapui5.hana.ondemand.com/resources/sap-ui-core.js, I don´t get the error, although I 
use the same UI5 verison (1.120.0).

When I start the server, open the Browser and open opaTests.qunit.html, I dont get the error.

Could you help here?
Why is the SortOrder.js file missing in the sap/ui/core folder?

**Expected behavior**
I expect the ui5 resouces correctly loaded. 

**Logs/Console Output**
if applicable, please copypasta _code-fenced_ log output, e.g.

```shell
$> ...
```

**Screenshots**
if applicable, add screenshots to help explain your problem.

**Runtime Env (please complete the following information):**

- `UI5` version: 1.120.0
- `wdio-qunit-service` version: 0.1.1
- `wdio`-version (output of `wdio --version`): 8.26.1
- `node`-version (output of `node --version`): 18.16.1
- Browser + Version: Chrome 120.0.6099.71

**Comment by vobu** [comment]
Hi, appreciate your thorough report - but unfortunately, you're in the wrong repo 😄 
Head over to https://github.com/mauriciolauffer/wdio-qunit-service and copypasta 🍝 your issue there!

**Comment by meindla** [comment]
Hi, thanks for the hint😄. Issue is now opened at the right place.
