### ISSUE TITLE
Issues with WebdriverIO's `devtools` protocol

### ISSUE THREAD

**Issue by LukasHeimann** [ui5-community/wdi5#572]
Updating to wdi5 v2 requires users to switch to the `devtools` automation protocol. This protocol has slight differences to WebdriverIO's default Webdriver protocol (compare https://github.com/webdriverio/webdriverio/issues/11984), which is why the team recommends against using it: https://github.com/webdriverio/webdriverio/issues/11984#issuecomment-1883319415

In fact, they want to even remove support for `devtools` with the next major version of WebdriverIO, v9: https://github.com/webdriverio/webdriverio/issues/11860

An additional reason for considering to _not_ use the `devtools` protocol is integration with remote test runners. Both SauceLabs and other hosted offers of Selenium grid are not supported with `devtools`, and even integration with non-Chromium browsers seems fragile at best, making wdi5 unusable for cross-browser testing: https://webdriver.io/docs/automationProtocols/#disadvantages-1

I don't know the reasons why the `devtools` protocol is now required by wdi5, but I'd suggest removing that requirement again and falling back to the WebDriver protocol unless end users explicitly choose to.

**Comment by Siolto** [comment]
Hi @LukasHeimann,

when using wdi5 v2 we don't force users to switch to `devtools`. You can use both and the Webdriver protocol is still the default. Since wdio v8 we just don't need to take care of the different drivers anymore as [wdio is now handling that](https://webdriver.io/blog/2023/07/31/driver-management/) for us.

Do you have issues running wdi5 v2 with the WebDriver protocol?

**Comment by LukasHeimann** [comment]
Hi @Siolto,

hm is the migration guide faulty in this case? https://ui5-community.github.io/wdi5/#/migration?id=usage-of-devtools-automation-protocol

Or did I perhaps just misunderstand it?
> Now requires using the devtools package (which is now a dependency of wdi5) and explicit configuration in the *.conf.(j|t)s-file

I thought this meant that we'd have to use `devtools`, which is why this now is a dependency explicitly. But I guess this could also mean that _(only) if you want to use the devtools protocol_ you'll have to do that

**Comment by Siolto** [comment]
you're right, we could clarify that a little bit more, that you have to do that **only** when you want to use the devtools protocol

**Comment by LukasHeimann** [comment]
That makes sense :)
Especially given that it also explicitly states that it bundles the necessary dependency, which I guess you'd normally have to install yourself.

Switching to webdriver proxies all browser logs to the wdio runner for some reason, even though I have disabled all logging... I'll try to reproduce in a minimal example though
