### ISSUE TITLE
Unable to select CheckBox in ValueHelp Dialog after updated UI5 lib to 1.120.3

### ISSUE THREAD

**Issue by gerganasuv** [ui5-community/wdi5#578]
**Describe the bug**
We are trying to click a check box on a ValueHelp dialog 
<img width="1704" alt="Screenshot 2024-01-12 at 17 08 07" src="https://github.com/ui5-community/wdi5/assets/18216096/2c715eea-e5cb-4896-b4cc-19c989ed86dd">

We copy the press from the test recorder as it is : 

```
iPressTheControl: async () => {
    await browser.asControl({
    	selector: {
            id: "grantAccess--userId-mInput-valueHelpDialog-table",
            searchOpenDialogs: true,
            interaction: {
                    idSuffix: "rowsel0"
            }
    }}).press();
}
```

and we add it in Javascript accordingly 

```javascript
static async iPressTheFirstRowCheckBox(){
  await browser.asControl({
    forceSelect:true,
    selector: {
          id: "grantAccess--userId-mInput-valueHelpDialog-table",
          searchOpenDialogs: true,
          interaction: {
                  idSuffix: "rowsel0"
          }
  }}).press();
}
```

**To Reproduce**

1. Run the test 
2. Click on checkBox of the row in the value help

**Expected behavior**
The checkBox is not actually clicked but there is no thrown exception. 
The test execution fails on the next step

**Comment by dominikfeininger** [comment]
Related to https://github.com/ui5-community/wdi5/issues/564 ?

**Comment by gerganasuv** [comment]
It could be, but i couldn`t find any solution of the other issue as well
