### ISSUE TITLE
Send GET X-CSRF-Token request with the Browser.executeAsyc

### ISSUE THREAD

**Issue by tamara-fuchs** [ui5-community/wdi5#580]
Hi,
 it is not clear for me, should it be possible in wdi5 to send the HEAD request using Browser.executeAsyc to get the session X-CSRF token. I tried different variants, but never get the Promise with the value.
I tried HEAD request and GET request, because we do have special endpoint to get the token in our service.

**Variant with GET**
it('should execute async JavaScript on the page', async () => {
    let consentsUrl = https://uicsconsumertest--flextestapp-con-dev.cfapps.sap.hana.ondemand.com/flex/personalization/v1/actions/getcsrftoken;

    const result = browser.executeAsync(
        (url, done) => {
            fetch(url, {
                method: 'GET',
                credentials: 'same-origin',
                headers: {
                    'Content-Type': 'application/json',
                }
            })
                .then(response => done(response));
        },consentsUrl);
    assert.strictEqual(result.status, 500 );
});

**Variant with HEAD**
 it("delete enduser personalization", async () => {
       
        const reqInstance = axios.create({
            headers: {
                'X-Csrf-Token': 'fetch'
            }
        });
        const res = await browser.executeAsync(  function ( reqInstance, done) {
            let url = "https://uicsconsumertest--flextestapp-con-dev.cfapps.sap.hana.ondemand.com/flexPersonalization/flex/personalization/v1/settings";
            reqInstance.head(url).then(response => done(response)).catch(e=>done(e))

        }, reqInstance);

        assert.strictEqual(res.status, 500 );
    })

        }, reqInstance);

        assert.strictEqual(res.status, 500 );
    })

In the both cases the PromisResult is not defined and there is no value to analyse.

Please advice if the executeAsync could be used for this purpose in wdi5 .
Best regards, Tamara
<img width="556" alt="Screenshot 2024-01-15 at 11 10 33" src="https://github.com/ui5-community/wdi5/assets/81688835/9b191997-9098-48ab-acbe-59f01213ddb4">

**Comment by vobu** [comment]
in your `GET` variant, you either need to `await` the `browser.executeAsync` call. Or move your `assert.strictEqual(result.status, 500 )` into the final `then`- clause (or `.catch`, depending on the test logic).

similar, in you `HEAD` variant, the `reqInstance.head(url)` needs to be `await`ed (or you need to overall rework the Promise `then` chain in your test).

**Comment by mauriciolauffer** [comment]
@tamara-fuchs your problem is due to the async nature of nodejs, you can see your **PromiseState** is **pending**... Check these links out to understand how it works:
[Overview of Blocking vs Non-Blocking](https://nodejs.org/en/learn/asynchronous-work/overview-of-blocking-vs-non-blocking) and [Async Await in Node.js – How to Master it?](https://blog.risingstack.com/mastering-async-await-in-nodejs/)
