### ISSUE TITLE
BAS Firefox cant find geckodriver 

### ISSUE THREAD

**Issue by Klabautter** [ui5-community/wdi5#584]
**Describe the bug**
After closing and reopening a Devspace in the BAS environment and attempting to rerun the WDI5 tests, I encounter the following error: "Failed to download binary (statusCode 404): Not Found" at download (file:///home/user/projects/wdi5test/node_modules/geckodriver/dist/install.js:46:15).
I don't know if this is an error with the WDI5 Framework or the Headless Testing add-on for the BAS Devspace.

**To Reproduce**
ALL in BAS enviroment
1. Add Headless Testing to your Devspace.
2. Install WDI5 and update the Capabilities with those from the Headless Testing Firefox.
3. Run your tests and then restart your Devspace.
4. Now, you should encounter the same error.

**Expected behavior**
The test should run normally.

**Logs/Console Output**
Error: Error: Failed to download binary (statusCode 404): Not Found
    at download (file:///home/user/projects/wdi5test/node_modules/geckodriver/dist/install.js:46:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Launcher.run (file:///home/user/projects/wdi5test/node_modules/@wdio/cli/build/launcher.js:102:13)

**Comment by Siolto** [comment]
Hi @NetaMolcho,

could you have a look? Thanks!

**Comment by vobu** [comment]
ping @NetaMolcho again

**Comment by NetaMolcho** [comment]
Hello @Klabautter ,
did you define the version and path of the Firefox (as I described here: https://ui5-community.github.io/wdi5/#/usage?id=using-bas-with-wdi5)? 
In that case, can you remove the node_modules folder and run 'npm i'? After that, try running the test again.

Please let me know if you still face this error.
Regards,
Neta.

**Comment by Klabautter** [comment]
Hi @NetaMolcho,
yes, I configured it as described, and it works. Sorry, there might have been a slight misunderstanding. My question was more about the need to delete the node_modules and run npm install every time after I stop and restart the dev space. I wanted to know if this is intentional or an error on my end.

best Regards, 
linus.

**Comment by NetaMolcho** [comment]
Hi @Klabautter,
The node_modules folder is not persistent, every stop-start It should be deleted in order to keep versions always up to date.

Regards,
Neta.

**Comment by Klabautter** [comment]
Hi @NetaMolcho,
Ah, okay, thank you. Then it was a misunderstanding on my part. So, the node_modules should be cleared every new session (DevSpaces Start). Thanks, that clears my question.

Best regards,
Linus

**Comment by Klabautter** [comment]
solved
