### ISSUE TITLE
How to get code coverage for UI5 apps?

### ISSUE THREAD

**Issue by navisarv** [ui5-community/wdi5#590]
Hi Team, I would like to get coverage report for UI5 app and I am looking for similar to [https://webdriver.io/docs/component-testing/coverage/](url)

your help is much appreciated!!

**Comment by vobu** [comment]
AFAIK, `wdio` (and thus `wdi5`) supports this out of the box: https://webdriver.io/docs/runner/#coverage
Disclaimer: haven't used it personally

**Comment by PavlinaCherkezova** [comment]
I am looking as well for a way to get a coverage report of the UI5 e2e tests. I have tried to enable the coverage as described in the docs, but I get the following error: 
![image](https://github.com/ui5-community/wdi5/assets/32837566/6fcfba3e-b188-4ef2-8173-b4b84663717b)

This is based on the default e2e tests after generating a UI5 typescript app with [generator-ui5-ts-app](https://github.com/ui5-community/generator-ui5-ts-app). I have added the following settings to the wdio.conf.ts: `runner: [
		"browser",
		{
			coverage: {
				enabled: true,
				extension: "ts",
				reporter: ["text", "html"],
			},
		},
	],`

Is this a problem with the configuration or with the wdio and ui5?  
Thanks in advance!

**Comment by vobu** [comment]
hi pavlina, if you've used the latest version of the ts app generator, it comes with wdi5 preinstalled. but judging by the error msg you've attached, wdi5 doesn't seem to be enabled in your wdio.conf.ts : `services: ['ui5']` (see https://ui5-community.github.io/wdi5/#/installation?id=c-manual-installation)

**Comment by Moh-Adel-Aly** [comment]
Hi Vobu, 

I had the same issue as Pavlina, I also tried using the local runner but code coverage is not supported for the local runners. the tests run fine but there nothing happens and no coverage report is being shown or files being created.

From my understanding the WDIO framework uses Istanbul for code coverage, is there any workarounds for this?

**Comment by Siolto** [comment]
Hi,

coverage reports do not work for e2e tests and it also does not make any sense. If you want to have coverage you need to use [Component Testing](https://webdriver.io/docs/component-testing) which is simply not possible with wdi5.

Code Coverage in UI5 applications is currently possible on the unit and integration test layer.

Regards
Simon
