### ISSUE TITLE
Error: DOM representation of control 'Element sap.m.Input#__input2-__clone54-__clone83' has no focus DOM reference

### ISSUE THREAD

**Issue by bkrencker** [ui5-community/wdi5#592]
When changing a cell value of a table using iChangeRow() there is an error message when test script is running headless in pipeline. When running locally in browser there is no error.

This is the same Error as in auto-closed issue #545 where you find more details and screenshots:
[Issue 545](https://github.com/ui5-community/wdi5/issues/545)

I was trying both options of iChangeRow() with and without optional parameter bInputNotFinalized
`When.onTheDetailPage.onTable({property: "orderLines", qualifier: "Positionen"}).iChangeRow({product_productNr: "1000801", quantity: "3"}, {quantity: "6"}, true)`

`When.onTheDetailPage.onTable({property: "orderLines", qualifier: "Positionen"}).iChangeRow({product_productNr: "1000801", quantity: "3"}, {quantity: "6"})`

**Error Message:**

`"Changing row values of table '{id: fe::table::orderLines::LineItem::Positionen}' with old values='{product_productNr: 1000801, quantity: 3}' to new values='{quantity: 6}' - FAILURE
Failure in Opa success function
Exception thrown by the testcode:'Error: DOM representation of control 'Element sap.m.Input#__input2-__clone54-__clone83' has no focus DOM reference
Error: DOM representation of control 'Element sap.m.Input#__input2-__clone54-__clone83' has no focus DOM reference
    at constructor.$ ([https://ui5.sap.com/1.120.1/resources/sap/ui/test/actions/Action.js:6:1158)
](https://ui5.sap.com/1.120.1/resources/sap/ui/test/actions/Action.js:6:1158)/n)    at constructor.executeOn ([https://ui5.sap.com/1.120.1/resources/sap/ui/test/actions/EnterText.js:6:719)
](https://ui5.sap.com/1.120.1/resources/sap/ui/test/actions/EnterText.js:6:719)/n)    at Object.executeOn ([https://ui5.sap.com/1.120.1/resources/sap/fe/test/builder/MdcTableBuilder.js:1202:20)
](https://ui5.sap.com/1.120.1/resources/sap/fe/test/builder/MdcTableBuilder.js:1202:20)/n)    at [https://ui5.sap.com/1.120.1/resources/sap/ui/test/pipelines/ActionPipeline.js:6:353
](https://ui5.sap.com/1.120.1/resources/sap/ui/test/pipelines/ActionPipeline.js:6:353/n)    at Array.forEach (<anonymous>)
    at [https://ui5.sap.com/1.120.1/resources/sap/ui/test/pipelines/ActionPipeline.js:6:331
](https://ui5.sap.com/1.120.1/resources/sap/ui/test/pipelines/ActionPipeline.js:6:331/n)    at Array.forEach (<anonymous>)
    at c.process ([https://ui5.sap.com/1.120.1/resources/sap/ui/test/pipelines/ActionPipeline.js:6:309)
](https://ui5.sap.com/1.120.1/resources/sap/ui/test/pipelines/ActionPipeline.js:6:309)/n)    at O ([https://ui5.sap.com/1.120.1/resources/sap/ui/test/OpaBuilder.js:6:2151)
](https://ui5.sap.com/1.120.1/resources/sap/ui/test/OpaBuilder.js:6:2151)/n)    at Object.executeOn ([https://ui5.sap.com/1.120.1/resources/sap/ui/test/OpaBuilder.js:6:10873)'
This](https://ui5.sap.com/1.120.1/resources/sap/ui/test/OpaBuilder.js:6:10873)'/nThis) is what Opa logged:
Found 0 blocking out of 1106 tracked timeouts -  sap.ui.test.autowaiter._timeoutWaiter#hasPending
AutoWaiter syncpoint -  sap.ui.test.autowaiter._autoWaiter
Found view with ID 'orders::OrdersObjectPage' and viewName 'undefined' -  sap.ui.test.Opa5
Found control with ID 'fe::table::orderLines::LineItem::Positionen' and controlType 'sap.ui.mdc.Table' in view 'sap.fe.templates.ObjectPage.ObjectPage' -  sap.ui.test.Opa5
1 out of 1 controls met the matchers pipeline requirements`

**Comment by Siolto** [comment]
Hi,

when it is only failing in the [headless mode](https://ui5-community.github.io/wdi5/#/recipes?id=chrome-run-headless), could you please check the window-size? If you don't define something specifically the "invisible" browser starts with a viewport of only 800x600px which is to small for most of the responsive applications.

Regards
Simon

**Comment by bkrencker** [comment]
Hi @Siolto thank you for your response. In the meantime I was checking different ways and what I found out that iChangeRow() is under no circumstances working on the ubuntu image.

When changing to the windows image or running locally on my windows machine it is working.

The window size is set to 1920, 1080. Also when it is set to lower resolution it is working on a windows machine.

Must be something that is different on ubuntu..
