### ISSUE TITLE
3D Viewer doesn't display model in Jenkins Pipline

### ISSUE THREAD

**Issue by MikhailDryk** [ui5-community/wdi5#593]
**Describe the bug**
We have a script that executes within a pipeline. There is a step in which a digital twin model is loaded, and it should become visible on the screen once imported. It works fine when we run it locally. However, when it is executed in the pipeline, the model takes 5-6 minutes to load. During this time, the busy indicator remains on the screen, and then the script fails.

![image](https://github.com/ui5-community/wdi5/assets/64844079/7bba0fa6-5764-4043-b114-206575fa88f7)

We suspect the issue may be related to a configuration problem within WDI5. We've attempted several solutions, such as commenting out the '[disable_gpu](https://peter.sh/experiments/chromium-command-line-switches/)' option and running it in headless mode locally, and it continued to work fine in the local environment.

**Expected behavior**
It is necessary for the 3D model viewer to load successfully and then to proceed with test after test.

**Logs/Console Output**
```
Error: waitUntil condition timed out after 50000ms    
at async DigitalTwinPageObject.iClickOnShowSceneTreeButton (/home/jenkins/workspace/C4P-checkDtwinScript-blr1sandbox/wdi5/test/copin-digital-twin-ui/pages/digitalTwinObjectPage.js:73:3)     
at async Context.anonymous (/home/jenkins/workspace/C4P-checkDtwinScript-blr1sandbox/wdi5/test/copin-digital-twin-ui/specs/digitalTwinApp.spec.js:206:3)
```

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: [v2.0.6]
- `UI5` version: [1.114.9]
- `wdio`-version (output of `wdio --version`): [8.24.12]
- `node`-version (output of `node --version`): [v20.11.0]
- OS: [linux]
- Browser + Version [v120.0.6099.224]

**Comment by nair-sumesh** [comment]
Did you try increasing the timeout greater than 50000.
From where I see it looks like the Jenkins agent's network through put causing this issue.

**Comment by MikhailDryk** [comment]
Hello @nair-sumesh 

Thanks for your advice, we tried to increase the timeout  earlier, but had the same result. It is very strange that local all goes well but in Jenkins we face the 3D model issue.

**Comment by nair-sumesh** [comment]
- Can you try again with a big number. In my test the minimum timeout I use is 300000 and for few of the steps even 10x more.
- Just to confirm the User, System and client are same in local as well as Jenkins execution.
