### ISSUE TITLE
REQUEST: Install git in wdi5 docker image

### ISSUE THREAD

**Issue by nair-sumesh** [ui5-community/wdi5#599]
- `wdi5/wdio-ui5-service`-version: `2.0.6`
- `UI5` version: `[1.121.1]`
- `wdio`-version (output of `wdio --version`): `8.16.12`
- `node`-version (output of `node --version`): `v18.16.1`
- OS:`macOS 13.5.2 `
- Browser + Version : ` Chrome version 123.0.6312.58`

**Comment by vobu** [comment]
it's coming in via #606

**Comment by vobu** [comment]
went in with #606
