### ISSUE TITLE
Interactable matcher has wrong type definition

### ISSUE THREAD

**Issue by heimwege** [ui5-community/wdi5#602]
Hey guys 👋🏻 ,

the `interactable` [matcher](https://ui5-community.github.io/wdi5/#/locators?id=interactable) is quite `boolean` but the [type definition](https://github.com/ui5-community/wdi5/blob/main/src/types/wdi5.types.ts#L170) insists on `Record<string, unknown>`.

**Comment by vobu** [comment]
argh, slipped through. PR fixing this pretty please 😸 ?!

**Comment by vobu** [comment]
this came in with #606
