### ISSUE TITLE
WebGL issues with WDI5 on Jenkins

### ISSUE THREAD

**Issue by apoorvavishwanatha** [ui5-community/wdi5#614]
Hi,

We are trying to run some WDI5 tests on Jenkins in a docker container that contain test cases on a 3D Viewer (this component: https://ui5.sap.com/#/entity/sap.ui.vk.tutorial.VIT/sample/sap.ui.vk.tutorial.VIT.06)

These do not seem to run on jenkins, and it seems like the root cause is that WebGL is not enabled with the chromedriver. Is there any specific wdio configuration that we can use to force the browser to run with WebGL enabled? 

These are the current flags we are using in the wdio.conf.js file under `goog:chromeOptions` for `browserName: "chrome"`
args:
```
"--headless",
"--incognito",
"--disable-dev-shm-usage",
"--window-size=1366,768",
"--no-sandbox",
"--disable-extensions",
"--ignore-certificate-errors",
"--disable-gpu",
"--ignore-urlfetcher-cert-requests"
```

These are the dev dependency versions:
```
"devDependencies": {
		"@wdio/cli": "^8.16.0",
		"@wdio/junit-reporter": "^8.24.2",
		"@wdio/local-runner": "^8.16.0",
		"@wdio/mocha-framework": "^8.16.0",
		"@wdio/spec-reporter": "^8.16.0",
		"@wdio/utils": "^8.16.0",
		"chromedriver": "^123.0.0",
		"prettier": "^3.1.1",
		"wdio-chromedriver-service": "^8.1.0",
		"wdio-docker-service": "^3.2.1",
		"wdio-timeline-reporter": "^5.1.0",
		"wdio-ui5-service": "^2.0.0",
		"xmlhttprequest-ssl": "^2.1.1"
}
```

**Comment by vobu** [comment]
never encountered this before, but did you try to _not_
`--disable-gpu`
?

**Comment by apoorvavishwanatha** [comment]
@vobu we did, but didn't seem to work. Even with the current configuration, it seems like WebGL was enabled at random. Are there any specific wdio configurations recommended for use with threejs/3D apis?

**Comment by vobu** [comment]
i never had to run tests headless on a d3/threejs app - sorry, can't help here. i'd suggest you hop over to the wdio discord channel - chances are you'll get some advice there...

**Comment by apoorvavishwanatha** [comment]
@vobu could you help me out with the channel link please?

**Comment by vobu** [comment]
https://discord.webdriver.io/

**Comment by nair-sumesh** [comment]
@apoorvavishwanatha : Can you please share the solution.
