### ISSUE TITLE
Selector for sap.m.Table returns sap.m.CustomListItem

### ISSUE THREAD

**Issue by gladklo** [ui5-community/wdi5#626]
**Describe the bug**
1. After I try to receive a sap.m.Table control, i get a sap.m.CustomListItem control.

2. Even after receiving the sap.ui.comp.smarttable.SmartTable and calling getTable() on it, the method returns a sap.m.CustomListItem 
    control.

**To Reproduce**
1.
            const tableSelector = {
                selector: {
                    id: "application-comcbseabusinessobjectoverview-tile-component---main--idContentFragment--idBOCountFragment-- 
            idCountTable"
            }};
            const table = await browser.asControl(tableSelector);
            const metadata = await table.getMetadata();
            const className = await metadata.getName();
            console.log(`Class name: ${className}`); //-->[0-0] Class name: sap.m.CustomListItem

2.
            const tableSelector = {
                selector: {
                    id: "application-comcbseabusinessobjectoverview-tile-component---main--idContentFragment--idBOCountFragment-- 
            idCountSmartTable"
            }};
            const table = await browser.asControl(tableSelector).getTable();
            const metadata = await table.getMetadata();
            const className = await metadata.getName();
            console.log(`Class name: ${className}`); //-->[0-0] Class name: sap.m.CustomListItem

**Expected behavior**
I want to receive the sap.m.Table control so I can look up the number of its entries.

**Screenshots**
![Screenshot 2024-07-08 122415](https://github.com/ui5-community/wdi5/assets/160245193/fe49c882-0d46-4cd7-bfcf-42b001388315)

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 2.0.9
- `UI5` version: 1.121.5
- `wdio`-version (output of `wdio --version`): 8.39.0
- `node`-version (output of `node --version`): v20.11.1
- OS: Windows11
- Browser + Version: edge 126.0.2592.81

**Comment by dominikfeininger** [comment]
can you try using  `interaction: "root"` as part of the selector?

**Comment by gladklo** [comment]
Thank you very much this worked!
