### ISSUE TITLE
WS package vulnerabilty in wdio/cli@8.39.1

### ISSUE THREAD

**Issue by mccmrunal** [ui5-community/wdi5#630]
WS package vulnerabilty in wdio/cli@8.39.1

we are using the latest version of wdio/cli , but in there WS (websocket package is used) version 8.13.0 which is marked as a high priority issue in our mendbolt scan if possible please upgrade the version of the websocket , as its marked as a severe threat in our mend bolt scan

Below are screenshot for the results
![image](https://github.com/user-attachments/assets/5ca13d40-66ce-42c8-b2b1-27db77172b6f)
![image](https://github.com/user-attachments/assets/ae16d863-704c-4055-acd2-eae8b3066a19)

**Comment by vobu** [comment]
if needed, please report this directly to the webdriverio repository. the cli is reused from wdio and not part of wdi5. thanks!

**Comment by elsauser** [comment]
![Image](https://github.com/user-attachments/assets/e68b9264-b54e-4b7a-bd1e-1d906841577b)

I see older version of webdriverio are used even tough latest patches are available , actually the WS used under this is causing a security vulnerability in my applicaton , If we can upgrade to latest version to fix this .
Thanks

**Comment by vobu** [comment]
happy to receive a pull request updating this dependency
