### ISSUE TITLE
TypeError: browser.asControl is not a function

### ISSUE THREAD

**Issue by woshihehao** [ui5-community/wdi5#632]
I am trying out wdi5 and it works fine on my local system but when I execute the tests in AZure pipeline, I get the below error:
![image](https://github.com/user-attachments/assets/02c52a78-0d73-471a-befe-74318c7f532d)
I have added below in wdi.conf.js:
<img width="1739" alt="image" src="https://github.com/user-attachments/assets/a2ba944b-dbf0-436e-ba23-1fe9f05a2c33">
I am using pageObjects, and I use below way to get UI5 controls:
<img width="1786" alt="image" src="https://github.com/user-attachments/assets/51a10a93-f0d7-4798-b1c4-78f1a196e5d8">
In pipeline console log, I also see below error for every control:
TypeError: browser.asControl is not a function.
In package.json, I have below devdependencies among others:
<img width="758" alt="image" src="https://github.com/user-attachments/assets/ce843576-5476-4fd2-a36a-fad1478ee74a">
All works fine locally but in AZure pipeline wdi5 tests break. Could colleagues help here?

**Comment by woshihehao** [comment]
Here is my wdi5 test repo: https://github.tools.sap/SelfBilling/e2e-tests-webdriverio
Is there a website for raising WDI5 issues within SAP? Such as 'https://github.tools.sap/deploy-with-confidence/issues'.

**Comment by Siolto** [comment]
Hi @woshihehao,

it looks like you are using `saucelabs` in your pipeline and you have a dedicated `saucelabs.conf.js`. Do you have configured wdi5 there as well?

Also have a look at the documentation and code snippets of wdi5. You are using a combination of deprecated configuration `url` and unnecessary operations: 

```javascript
*** unnecessary operation ***
const tile = await browser.asControl({...})
const tileElement = await tile.getWebElement()
await tileElement.click

*** wdi5 native press ***
await browser.asControl({...}).press()
```
