### ISSUE TITLE
compatibility with wdio version 9.*

### ISSUE THREAD

**Issue by rbhuva** [ui5-community/wdi5#633]
Hello,

WDIO has released the version 9.* and while upgrading the wdio version npm fails to install wdio-ui5-service.
wdio-ui5-service has wdio as a peer dependency with version.

Could you please do the needful to make it work with wdio version 9.*

![image](https://github.com/user-attachments/assets/f52b0485-f943-4a6e-9299-6f44f6d63583)

Thanks,
Rajdeep Bhuva

**Comment by vobu** [comment]
Hi, yep, `wdio^9` is out. And yes, until we get to check full compatibility of `wdi5` with it,  we need to pin any `wdio` dependencies in `wdi5` to `^8`. Given that this is a collab Open Source project, would you mind giving this a shot 😄 ?

**Comment by vobu** [comment]
resolved with https://github.com/ui5-community/wdi5/commit/0ae7e8d263f86cbabd862d4b8fae93bebe134054

**Comment by vobu** [comment]
and now tackled with #645
