### ISSUE TITLE
Dependency Conflict: wdio-ui5-service Incompatible with @wdio/cli Version 9.x.x

### ISSUE THREAD

**Issue by calin10** [ui5-community/wdi5#636]
Describe the bug
The wdio-ui5-service has a peer dependency on @wdio/cli that is locked to versions >=8.14.0 <9. However, @wdio/cli version 9 is already available (currently at 9.0.7), which leads to dependency resolution issues when trying to update to the latest version.

To Reproduce

Update @wdio/cli to version 9.x.x (e.g., 9.0.7).
Run npm install in the project.
Observe the dependency resolution error related to wdio-ui5-service.
Expected behavior
The wdio-ui5-service should support @wdio/cli version 9.x.x, allowing the package to be installed without any dependency issues.

Logs/Console Output
npm error Could not resolve dependency:
npm error peer @wdio/cli@" >=8.14.0 <9 " from wdio-ui5-service@2.0.10
npm error node_modules/wdio-ui5-service
npm error dev wdio-ui5-service@"^2.0.9" from @dct/dct-frontend@0.6.7
npm error packages/dct-frontend
npm error @dct/dct-frontend@0.6.7
npm error node_modules/@dct/dct-frontend
npm error workspace packages/dct-frontend from the root project

Runtime Env :

wdi5/wdio-ui5-service-version: 2.0.10
UI5 version: 1.126.0
wdio-version (output of wdio --version): 9.0.7
node-version (output of node --version): v20.16.0
OS: MacOS Sonoma 14.6.1
Browser + Version: Chrome - Version 127.0.6533.120 (Official Build) (arm64)

**Comment by fabiantschirschnitz** [comment]
Dear wdi5-Team,

we face this same issue currently in our dependabots-PR's and have to manually fix the wdi-dependencies to 8.x
Is there any chance, this will be updated soon?
Thanks for your efforts.

Kind regards, Fabian. 
fyi: @nlaenger

**Comment by Siolto** [comment]
Hi everyone, 

we are working on the [v9 support](https://github.com/ui5-community/wdi5/tree/v9-support). We need some time to fully support v9 as we heavily rely on the [executeAsync](https://webdriver.io/docs/api/browser/executeAsync/) function which is now deprecated. 

We will keep you up to date with our progress.

**Comment by RichieSap** [comment]
Any update?

**Comment by vobu** [comment]
RC is out, base code is #645 
https://www.npmjs.com/package/wdio-ui5-service/v/3.0.0-rc.0
