### ISSUE TITLE
Wdi5 tests are not able to select in value help and getting timed out

### ISSUE THREAD

**Issue by Divya-Shanmugamb** [ui5-community/wdi5#639]
Hi team, 

I am trying out wdi5 tests in cap-js/incidents-app, while selecting from value help, its not able to select. 

<img width="1082" alt="image" src="https://github.com/user-attachments/assets/7f56f804-74cc-4f60-8c7b-bfd0e5d6559a">
code snippet: 
<img width="522" alt="image" src="https://github.com/user-attachments/assets/31cf143f-b96f-4a90-a613-1fcb96dc546c">

As its unable to select from value help its getting timed out.

"@wdio/cli": "8.22.0",
"@wdio/local-runner": "8.17.0",
"@wdio/mocha-framework": "8.17.0",
"@wdio/spec-reporter": "8.17.0",
"wdio-chromedriver-service": "8.1.1",
"wdio-ui5-service": "2.0.10",
"dotenv": "^16.3.1"

**Comment by Siolto** [comment]
[iSelectRows](https://sapui5.hana.ondemand.com/#/api/sap.fe.test.api.DialogValueHelpActions%23methods/iSelectRows) only allows an **object** or **number** to be passed. 
If you want to select the first row you can do something like `iSelectRows(0)`. If you want to select the Row with an specific ID you could do something like this: `iSelectRows({'ID': 1000010})`

Also check that the type of this dialog really is `DialogType.ValueHelp`.
