### ISSUE TITLE
Request for support with migration to wdi5 and custom matchers

### ISSUE THREAD

**Issue by TrittyTang** [ui5-community/wdi5#643]
We have been using opa-e2e for E2E test automation for the past 3 years, and have developed custom matchers such as `bindingContextPropertyStrictEquals` and `cSSClassStrictEquals`, as well as a custom matcher function. Here are the examples
````
        selector: {
          controlType: 'sap.m.Button',
          searchOpenDialogs: true,
          // custom 
          bindingContextPropertyStrictEquals: [
            {
              model: 'portal',
              path: 'TEXT',
              value: sText
            },
            {
              model: 'portal',
              path: 'EXTENSION_POINT',
              value: sExtensionPoint
            }
          ],
          // custom
          cSSClassStrictEquals: {
            className: `sapMMessageBoxBtn${sAction}`
          },
          // custom
          matchers: {
            function: function (oButton, sMessageBoxType) {
              const bMessageBoxButton = oButton.getId().includes('mbox-btn-')
              const bExpectedMessageBoxType = !!oButton.getParent()?.hasStyleClass(`sapMMessageBox${sMessageBoxType}`)
              return bMessageBoxButton && bExpectedMessageBoxType
            },
            args: {
              sMessageBoxType
            }
          }
        }
      }
````

We are now exploring the possibility of migrating to wdi5 and are wondering if it is possible to use/support custom matchers in this transition. Any assistance or guidance on this matter would be greatly appreciated. Thank you.

**Comment by Siolto** [comment]
Hi @TrittyTang

currently we never thought about the possibility to add custom matchers to wdi5. We probably would have to add them to the [RecordReplayAPI](https://sapui5.hana.ondemand.com/#/api/sap.ui.test.RecordReplay). Let me think about that. 

At the moment we are all hard pressed on time and are focusing on the wdioV9 support so it could take some time.
