### ISSUE TITLE
wdi5 retrieves wrong Control when trying to get Variant Management Control from Filter Bar

### ISSUE THREAD

**Issue by zaid-tariq** [ui5-community/wdi5#651]
For my integration tests, I need to check the dirty state of the Variant. Therefore, I want to get the [Variant Management](https://sapui5.hana.ondemand.com/sdk/#/api/sap.m.VariantManagement) control. Once I have the variant management control, I can call the [getModified](https://sapui5.hana.ondemand.com/sdk/#/api/sap.m.VariantManagement%23methods/getModified) method to check the dirty state.

=\> But the problems is that wdi5 doesn't return the control correctly.

I tried the following ways to get the control:

First Approach: Get VM Control through Filter Bar

```
const filterbar = await browser.asControl({
            selector: {
                id: "application-test-displayTestCaseList-component---viewPreparationTestCasesOverviewBegin--filterBar"
            }
        });
//filterBar.getMetadata().getName() is sap.ui.comp.filterbar.FilterBar
const vm = await filterbar.getVariantManagement();
const isModified = await vm.getModified(); // Error: method not defined
// Because the vm.getMetadata().getName()is sap.m.Button instead of sap.m.VariantManagement
```

Second Approach: Use Control Type of VM Control

```
const vm = await browser.asControl({
            selector: {
                controlType: "sap.m.VariantManagement"
            }
        });

const isModified = await vm.getModified(); // Error: method not defined
const vmMetadata = await vm.getMetadata();
const vmClass = await vmMetadata.getName(); //should be sap.m.VariantManagement, but is sap.m.Button
```

Third Method: Using id of Variant Management Control

```
const vm = await browser.asControl({
            selector: {
                id: "application-test-displayTestCaseList-component---viewPreparationTestCasesOverviewBegin--filterBar-variantManagement-vm"
            }
        });

const isModified = await vm.getModified(); // Error: method not defined
const vmMetadata = await vm.getMetadata();
const vmClass = await vmMetadata.getName(); //should be sap.m.VariantManagement, but is sap.m.Button
```

<br>
Is this a bug in wdi5 or am I doing something wrong?

<br>
<hr>

**Runtime Env :**

- `wdi5/wdio-ui5-service`-version: 2.0.10
- `UI5` version:  1.124.6
- `wdio`-version (output of `wdio --version`): 8.40.5
- `node`-version (output of `node --version`): 20.17.0
- OS: Mac OS
- Browser + Version: Chrome  131.0.6778.85

**Comment by Siolto** [comment]
Hi @zaid-tariq,

could you try to add the interaction type `root` to your selector:

```javascript
selector: {
    ...
    interaction: "root",
}
```

**Comment by zaid-tariq** [comment]
@Siolto  Thanks for the tip! 

Yup, this resolves it if I retrieve the Variant Management control using its own matchers.

But it still provides wrong control when using `FilterBar's` `getVariantManagement` method.

For my current problem though I can just get the VM control directly instead of going through the FilterBar.

Thanks for the help.
